1354 srcapicomposition api helpersmd
vuejs-translations/docs-fr pull request #1355
Opened 2024-09-18 15:05 UTC by tisma95

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2024-09-18 15:20 UTC, edimitchel requested changes

2024-09-18 15:20 UTC, edimitchel commented on src/api/composition-api-helpers.md
> +# Composition API: Aides {#composition-api-helpers}
Pas sûr que aides soit le plus approprié, je pense qu'il faut laisser Helpers.

À voir avec le reste de la doc

2024-09-19 15:15 UTC, edimitchel commented on src/api/composition-api-helpers.md
> +C'est l'aide sous-jacente qui alimente [`defineModel()`](/api/sfc-script-setup#definemodel). Si vous utilisez `<script setup>`, `defineModel()` devrait être préféré.
plutôt le helper que l'helper

2024-09-19 15:21 UTC, tisma95 commented on src/api/composition-api-helpers.md
> +C'est l'helper sous-jacente qui alimente [`defineModel()`](/api/sfc-script-setup#definemodel). Si vous utilisez `<script setup>`, `defineModel()` devrait être préféré.
```suggestion
C'est le helper sous-jacente qui alimente [`defineModel()`](/api/sfc-script-setup#definemodel). Si vous utilisez `<script setup>`, `defineModel()` devrait être préféré.
```

2024-09-20 12:35 UTC, edimitchel commented on src/api/composition-api-helpers.md
> +C'est l'helper sous-jacente qui alimente [`defineModel()`](/api/sfc-script-setup#definemodel). Si vous utilisez `<script setup>`, `defineModel()` devrait être préféré.
sous-jacent

2024-09-20 14:25 UTC, tisma95 commented on src/api/composition-api-helpers.md
> +C'est le helper sous-jacente qui alimente [`defineModel()`](/api/sfc-script-setup#definemodel). Si vous utilisez `<script setup>`, `defineModel()` devrait être préféré.
```suggestion
C'est le helper sous-jacent qui alimente [`defineModel()`](/api/sfc-script-setup#definemodel). Si vous utilisez `<script setup>`, `defineModel()` devrait être préféré.
```

2024-09-20 18:41 UTC, edimitchel requested changes

2024-09-20 18:41 UTC, edimitchel commented on src/api/composition-api-helpers.md
> +- Disponible uniquement dans la version 3.4+
```suggestion
- Disponible à partir de la version 3.4
```

2024-09-20 18:41 UTC, edimitchel commented on src/api/composition-api-helpers.md
> +  - [Guide - Typer les refs du template d'un composant](/guide/typescript/composition-api#typing-component-template-refs) <sup class="vt-badge ts" />
```suggestion
  - [Guide - Typer les refs de template d'un composant](/guide/typescript/composition-api#typing-component-template-refs) <sup class="vt-badge ts" />
```

2024-09-21 22:37 UTC, edimitchel approved these changes

2024-09-21 22:37 UTC, merged