1356 srcapicustom elementsmd
vuejs-translations/docs-fr pull request #1357
Opened 2024-09-18 15:45 UTC by tisma95

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes # 
      
Remarques:
J'ai des doutes sur la traduction shadow root. Je pense qu'on peut avoir mieux que **la racine d'ombre** @edimitchel  as tu une idée ?

2024-09-18 17:32 UTC, edimitchel requested changes

2024-09-18 17:32 UTC, edimitchel commented on src/api/custom-elements.md
> +    // les options suivantes sont possibles 3.5+
```suggestion
    // les options suivantes sont possibles à partir de la version 3.5
```

2024-09-18 17:32 UTC, edimitchel commented on src/api/custom-elements.md
> +  > Les caractères sont simplifiés pour une meilleure lisibilité.
```suggestion
  > Les types sont simplifiés pour une meilleure lisibilité.
```

2024-09-18 17:32 UTC, edimitchel commented on src/api/custom-elements.md
> +  - Notez également que `defineCustomElement()` nécessite une [configuration spéciale](/guide/extras/web-components#sfc-as-custom-element) lorsqu'il est utilisé avec des composants à fichier unique.
```suggestion
  - Notez également que `defineCustomElement()` nécessite une [configuration spéciale](/guide/extras/web-components#sfc-as-custom-element) lorsqu'il est utilisé avec des composants monofichiers.
```

2024-09-18 17:32 UTC, edimitchel commented on src/api/custom-elements.md
> +Un assistant de la Composition API qui renvoie la racine d'ombre de l'élément personnalisé Vue actuel.
Helper

2024-09-19 15:05 UTC, tisma95 commented on src/api/custom-elements.md
> +Un assistant de la Composition API qui renvoie la racine d'ombre de l'élément personnalisé Vue actuel.
```suggestion
Un assistant d'aide de la Composition API qui renvoie la racine d'ombre de l'élément personnalisé Vue actuel.
```

2024-09-19 15:05 UTC, tisma95 commented on src/api/custom-elements.md
> +Un assistant de la Composition API qui renvoie l'élément hôte de l'élément personnalisé Vue actuel.
```suggestion
Un assistant d'aide de la Composition API qui renvoie l'élément hôte de l'élément personnalisé Vue actuel.
```

2024-09-19 15:05 UTC, tisma95 commented on src/api/custom-elements.md
> +Un assistant de la Composition API qui renvoie la racine d'ombre de l'élément personnalisé Vue actuel.
J'ai mis un assistant d'aide pour le helper

2024-09-19 15:09 UTC, tisma95 commented on src/api/custom-elements.md
> +Un assistant d'aide de la Composition API qui renvoie la racine d'ombre de l'élément personnalisé Vue actuel.
```suggestion
Un assistant helper de la Composition API qui renvoie la racine d'ombre de l'élément personnalisé Vue actuel.
```

2024-09-19 15:09 UTC, tisma95 commented on src/api/custom-elements.md
> +Un assistant d'aide de la Composition API qui renvoie l'élément hôte de l'élément personnalisé Vue actuel.
```suggestion
Un assistant helper de la Composition API qui renvoie l'élément hôte de l'élément personnalisé Vue actuel.
```

2024-09-19 15:09 UTC, edimitchel commented on src/api/custom-elements.md
> +Un assistant de la Composition API qui renvoie la racine d'ombre de l'élément personnalisé Vue actuel.
Non, on doit garder le terme Helper qui est un mot technique non traduisible

2024-09-19 15:10 UTC, tisma95 commented on src/api/custom-elements.md
> +Un assistant de la Composition API qui renvoie la racine d'ombre de l'élément personnalisé Vue actuel.
C'est fait j'ai mis Helper

2024-09-19 15:24 UTC, tisma95 commented on src/api/custom-elements.md
> +  - **`shadowRoot`** <sup class="vt-badge" data-text="3.5+"/>: `boolean`, par défaut `true`. Définir à `false` pour restituer l'élément personnalisé sans racine fantôme. Cela signifie que `<style>` d
```suggestion
  - **`shadowRoot`** <sup class="vt-badge" data-text="3.5+"/>: `boolean`, par défaut `true`. Définir à `false` pour restituer l'élément personnalisé sans shadow root. Cela signifie que `<style>` dans les SFC d'éléments personnalisés ne sera plus encapsulé.
```

2024-09-19 15:24 UTC, tisma95 commented on src/api/custom-elements.md
> +  - **`nonce`** <sup class="vt-badge" data-text="3.5+"/>: `string`, s'il est fourni, sera défini comme l'attribut `nonce` sur les tags de style injectés dans la racine de l'ombre.
```suggestion
  - **`nonce`** <sup class="vt-badge" data-text="3.5+"/>: `string`, s'il est fourni, sera défini comme l'attribut `nonce` sur les tags de style injectés dans la shadow root.
```

2024-09-19 15:24 UTC, tisma95 commented on src/api/custom-elements.md
> +  - **`styles`**: un tableau de chaînes CSS intégrées pour fournir du CSS à injecter dans la racine de l'ombre de l'élément.
```suggestion
  - **`styles`**: un tableau de chaînes CSS intégrées pour fournir du CSS à injecter dans la shadow root de l'élément.
```

2024-09-19 15:24 UTC, tisma95 commented on src/api/custom-elements.md
> +Un assistant helper de la Composition API qui renvoie la racine d'ombre de l'élément personnalisé Vue actuel.
```suggestion
Un assistant helper de la Composition API qui renvoie la shadow root de l'élément personnalisé Vue actuel.
```

2024-09-20 14:21 UTC, tisma95 reviewed
Changement racine d'ombre par shadow root

2024-09-20 18:43 UTC, edimitchel requested changes

2024-09-20 18:43 UTC, edimitchel commented on src/api/custom-elements.md
> +  - **`styles`**: un tableau de chaînes CSS intégrées pour fournir du CSS à injecter dans la shadow root de l'élément.
```suggestion
  - **`styles`**: un tableau de chaînes CSS  pour fournir du CSS à injecter dans la shadow root de l'élément.
```

2024-09-20 18:43 UTC, edimitchel commented on src/api/custom-elements.md
> +  Notez qu'au lieu d'être transmises dans le cadre du composant lui-même, ces options peuvent également être transmises via un deuxième argument :
```suggestion
  Notez qu'au lieu d'être transmises comme une partie du composant lui-même, ces options peuvent également être transmises via un deuxième argument :
```

2024-09-21 22:37 UTC, edimitchel approved these changes

2024-09-21 22:38 UTC, edimitchel requested changes

2024-09-21 22:38 UTC, edimitchel commented on src/api/custom-elements.md
> +  - **`styles`**: un tableau de chaînes CSS  pour fournir du CSS à injecter dans la shadow root de l'élément.
```suggestion
  - **`styles`**: un tableau de chaînes CSS pour fournir du CSS à injecter dans la shadow root de l'élément.
```

2024-09-21 22:38 UTC, edimitchel approved these changes

2024-09-21 22:39 UTC, merged