1403 srcguideessentialstemplate refsmd accessing the refs
vuejs-translations/docs-fr pull request #1404
Opened 2024-10-07 15:35 UTC by tisma95

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2024-10-08 07:40 UTC, edimitchel requested changes

2024-10-08 07:40 UTC, edimitchel commented on src/guide/essentials/template-refs.md
> +Pour obtenir la référence avec l'API Composition, nous pouvons utiliser l'aide [`useTemplateRef()`](/api/composition-api-helpers#usetemplateref) <sup class="vt-badge" data-text="3.5+" />:
```suggestion
Pour obtenir la référence avec l'API Composition, nous pouvons utiliser le helper [`useTemplateRef()`](/api/composition-api-helpers#usetemplateref) <sup class="vt-badge" data-text="3.5+" />:
```

2024-10-10 15:02 UTC, tisma95 reviewed
Apply Review

2024-10-10 20:40 UTC, edimitchel approved these changes

2024-10-10 20:40 UTC, merged