Feat(transition-group): Add custom transition group #1438
vuejs-translations/docs-fr pull request #1448
Opened 2024-10-31 15:56 UTC by tisma95

#1438

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2024-11-03 22:00 UTC, edimitchel requested changes

2024-11-03 22:00 UTC, edimitchel commented on src/guide/built-ins/transition-group.md
> +### Classes de TransitionGroup personnalisées
Tu peux ajouter l'ancre en anglais stp?

2024-11-03 22:00 UTC, edimitchel commented on src/guide/built-ins/transition-group.md
> +Vous pouvez également spécifier des classes de transition personnalisées pour l'élément mobile en passant la propriété `moveClass` à `<TransitionGroup>`, comme dans l'exemple suivant [Classes de tran
```suggestion
Vous pouvez également spécifier des classes de transition personnalisées pour l'élément mobile en passant la propriété `moveClass` à `<TransitionGroup>`, comme dans l'exemple suivant [Classes de transition personnalisées](/guide/built-ins/transition.html#custom-transition-classes).
```

2024-11-05 06:13 UTC, tisma95 commented on src/guide/built-ins/transition-group.md
> +### Classes de TransitionGroup personnalisées
Bien vu. Fait je vais reporter çà aussi sur le repo anglais parce que c'est fait là aussi.

2024-11-05 07:07 UTC, edimitchel approved these changes

2024-11-05 07:07 UTC, merged