docs: translation of async.md
vuejs-translations/docs-fr pull request #145
Opened 2022-10-28 14:22 UTC by 8HoLoN

Actions à vérifier 

- [ ] Ancres anglaises ajoutées à chaque titre traduits
- [ ] Nom de la page mise en cohérence avec les ancres qui pointe sur la page traduite 
  
- [ ] Lien de menu mis à jour
  
- [ ] PR liée à une issue
      Closes #

2022-10-29 00:58 UTC, kissu commented on src/guide/components/async.md
> +    // ...charger le component depuis le serveur
```suggestion
    // ...charger le composant depuis le serveur
```

2022-10-29 01:01 UTC, kissu reviewed
Small little thing to fix, LGTM otherwise 👍🏻

2022-11-02 22:36 UTC, edimitchel requested changes

2022-11-02 22:36 UTC, edimitchel commented on src/guide/components/async.md
> +Comme vous pouvez le voir, `defineAsyncComponent` accepte une fonction de chargement qui renvoie une Promise. La fonction `resolve` de la Promise doit être appelé lorsque vous avez récupéré la défini
```suggestion
Comme vous pouvez le voir, `defineAsyncComponent` accepte une fonction de chargement qui renvoie une promesse (Promise). La fonction `resolve` de la promesse doit être appelé lorsque vous avez récupéré la définition de votre composant à partir du serveur. Vous pouvez également appeler `reject(reason)` pour indiquer que le chargement a échoué.
```

2022-11-02 22:36 UTC, edimitchel commented on src/guide/components/async.md
> +Si un composant de chargement est fourni, il sera affiché en premier lors du chargement du composant sous-jacent. Il y a un délai par défaut de 200 ms avant que le composant de chargement ne s'affich
```suggestion
Si un composant de chargement est fourni, il sera affiché en premier lors du chargement du composant sous-jacent. Il y a un délai par défaut de 200ms avant que le composant de chargement ne s'affiche - car sur les réseaux rapides, un état de chargement instantané peut être remplacé trop rapidement et finir par apparaitre comme un effet de scintillement à l'écran.
```

2022-11-03 11:32 UTC, 8HoLoN commented on src/guide/components/async.md
> +Si un composant de chargement est fourni, il sera affiché en premier lors du chargement du composant sous-jacent. Il y a un délai par défaut de 200 ms avant que le composant de chargement ne s'affich
En français, il y a une espace avant les unités.

2022-11-03 12:38 UTC, edimitchel approved these changes

2022-11-08 09:20 UTC, edimitchel approved these changes

2022-11-08 09:21 UTC, merged