Add VueToronto banner to the docs

feat(*): add vuetoronto banner (#1456)
vuejs-translations/docs-fr pull request #1457
Opened 2024-11-08 08:26 UTC by edimitchel

resolves #1456
Cherry picked from https://github.com/vuejs/docs/commit/58c4b8992527c252b18b834e4712ebe682e43db2

2024-11-08 15:22 UTC, tisma95 commented on .vitepress/theme/components/Banner.vue
> +      <span class="vt-tagline"> - Join the premier Vue.js conference</span>
```suggestion
      <span class="vt-tagline"> - Rejoignez la première conférence Vue.js</span>
```

2024-11-08 15:23 UTC, tisma95 commented on .vitepress/theme/components/Banner.vue
> +      <span class="vt-text-primary">Use code</span> VUEJS
```suggestion
      <span class="vt-text-primary">Utiliser le code</span> VUEJS
```

2024-11-08 15:23 UTC, tisma95 commented on .vitepress/theme/components/Banner.vue
> +      <span class="vt-text-primary">to get 15% off</span>
```suggestion
      <span class="vt-text-primary">pour obtenir 15 % de réduction</span>
```

2024-11-08 15:24 UTC, tisma95 requested changes
Translation to do

2024-11-09 22:36 UTC, edimitchel commented on .vitepress/theme/components/Banner.vue
> +        Register
```suggestion
        S'inscrire
```

2024-11-09 22:37 UTC, merged