guide/components/registration.md
vuejs-translations/docs-fr pull request #147
Opened 2022-10-29 16:26 UTC by 8HoLoN

Actions à vérifier 

- [x] Ancres anglaises ajoutées à chaque titre traduits
- [x] Nom de la page mise en cohérence avec les ancres qui pointe sur la page traduite 
  
- [x] Lien de menu mis à jour
  
- [x] PR liée à une issue
      Closes #146

2022-10-29 16:28 UTC, kissu commented on src/guide/components/registration.md
> +> Cette page suppose que vous avez déjà lu les [bases à propos des composants](/guide/essentials/component-basics). Lisez-le d'abord si vous débutez avec les composants.
```suggestion
> Cette page suppose que vous avez déjà lu les [bases à propos des composants](/guide/essentials/component-basics). Lisez-la d'abord si vous débutez avec les composants.
```

2022-10-29 16:34 UTC, kissu requested changes
LGTM for the rest!

2022-10-29 16:34 UTC, kissu commented on src/guide/components/registration.md
> +> Cette page suppose que vous avez déjà lu les [bases à propos des composants](/guide/essentials/component-basics). Lisez-le d'abord si vous débutez avec les composants.
On parle de la page ici je pense non?

2022-10-29 16:37 UTC, 8HoLoN commented on src/guide/components/registration.md
> +> Cette page suppose que vous avez déjà lu les [bases à propos des composants](/guide/essentials/component-basics). Lisez-le d'abord si vous débutez avec les composants.
Well it's even "Lisez-les" since this refers to "les bases".

2022-10-29 16:42 UTC, kissu approved these changes

2022-11-02 22:30 UTC, edimitchel requested changes

2022-11-02 22:30 UTC, edimitchel commented on src/guide/components/registration.md
> +Dans une configuration autre que `<script setup>`, vous devrez utiliser l'option `components` :
```suggestion
Dans une configuration sans `<script setup>`, vous devrez utiliser l'option `components` :
```

2022-11-02 22:30 UTC, edimitchel commented on src/guide/components/registration.md
> +2. `<PascalCase />` rend plus évident qu'il s'agit d'un composant Vue au lieu d'un élément HTML natif dans les templates. Il différencie également les composants Vue des custom elements (web componen
```suggestion
2. `<PascalCase />` rend plus évident qu'il s'agit d'un composant Vue au lieu d'un élément HTML natif dans les templates. Il différencie également les composants Vue des custom elements (web components).
```

2022-11-02 22:30 UTC, edimitchel commented on src/guide/components/registration.md
> +Il s'agit du style recommandé lorsque vous travaillez avec des templates à base de SFC ou de chaînes de caratères. Cependant, comme indiqué dans [les mises en garde concernant le parsage de template
```suggestion
Il s'agit du style recommandé lorsque vous travaillez avec des templates à base de SFC ou de chaînes de caratères. Cependant, comme indiqué dans [les mises en garde concernant l'interprétation du template DOM](/guide/essentials/component-basics.html#dom-template-parsing-caveats), les balises déclarées en casse Pascal ne sont pas utilisables dans les templates DOM.
```

2022-11-03 12:38 UTC, edimitchel approved these changes

2022-11-15 09:00 UTC, merged