chore: translation of provide-inject.md
vuejs-translations/docs-fr pull request #150
Opened 2022-10-30 08:41 UTC by 8HoLoN

Actions à vérifier 

- [ ] Ancres anglaises ajoutées à chaque titre traduits
- [ ] Nom de la page mise en cohérence avec les ancres qui pointe sur la page traduite 
  
- [ ] Lien de menu mis à jour
  
- [ ] PR liée à une issue
      Closes #

2022-11-02 21:55 UTC, edimitchel requested changes
Beau travail!
Quelques erreurs d'inattentions mais ça viendra bien vite!

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +Habituellement, lorsque nous devons transmettre des données du parent à un composant enfant, nous utilisons des [props](/guide/components/props). Cependant, imaginez le cas où nous avons un arbre de
```suggestion
Habituellement, lorsque nous devons transmettre des données du parent à un composant enfant, nous utilisons des [props](/guide/components/props). Cependant, imaginez le cas où nous avons un arbre de composants important, et qu'un composant profondément imbriqué aurait besoin d'accéder à des informations d'un de ses composants parents. Avec seulement des props, nous devrions passer la même prop sur toute la chaîne composants parents :
```
As-tu installé l'extension VS Code pour éviter ce genre de faute d'orthographe?

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +Notez que bien que le composant `<Footer>` n'utilise pas du tout de ces props, il doit malgré tout les déclarer et les transmettre uniquement afin que `<DeepChild>` puisse y accéder. S'il y a une cha
```suggestion
Notez que bien que le composant `<Footer>` n'utilise pas du tout ces props, il doit malgré tout les déclarer et les transmettre uniquement afin que `<DeepChild>` puisse y accéder. S'il y a une chaîne de composants parents plus longue, encore plus de composants seront affectés par le problème. C'est ce qu'on appelle le "props drilling" et ce n'est certainement pas amusant à gérer.
```

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +La fonction `provide()` accepte deux arguments. Le premier argument est appelé la **clé d'injection**, qui peut être une chaîne de caractères ou un `Symbol`. La clé d'injection est utilisée par les c
```suggestion
La fonction `provide()` accepte deux arguments. Le premier argument est appelé la **clé d'injection**, qui peut être une chaîne de caractères ou un `Symbol`. La clé d'injection est utilisée par les composants descendants pour rechercher la valeur souhaitée à injecter. Un composant peut appeler `provide()` plusieurs fois avec différentes clés d'injection pour fournir différentes valeurs.
```
_A single component_ ne veut pas dire un seul composant, mais ça permet d'appuyer le fait qu'un composant puisse le faire plusieurs fois.

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +La fourniture de valeurs réactives permet aux composants descendants utilisant la valeur fournie d'établir une connexion réactive au composant fournisseur.
```suggestion
Fournir des valeurs réactives permet aux composants descendants qui les utilisent d'établir une connexion réactive au composant fournisseur.
```
Plus simple à lire

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +Pour chaque propriété de l'objet `provide`, la clé est utilisée par les composants enfants pour localiser la valeur correcte à injecter, tandis que la valeur est ce qui finit par être injecté.
```suggestion
Pour chaque propriété de l'objet `provide`, la clé est utilisée par les composants enfants pour localiser la valeur correcte à injecter, tandis que la valeur est ce qui finit par être injectée.
```
Non?

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +## App-level Provide {#app-level-provide}
Hum..
```suggestion
## Provide au niveau de l'application {#app-level-provide}
```
?

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +[Exemple complet provide + inject avec réactivité](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgcHJvdmlkZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBDaGlsZCBmcm9tICcuL0NoaWxkLnZ1Z
Traduire les commentaires dans le code?

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
>  export default {
injected value => valeur injectée

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +[Exemple complet provide + inject](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCBDaGlsZCBmcm9tICcuL0NoaWxkLnZ1ZSdcblxuZXhwb3J0IGRlZmF1bHQge1xuICBjb21wb25lbnRzOiB7IENoaWxkIH0sXG4gIHByb
Traduire le texte dans `GrandChild`

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +### Aliasing d'injection {#injection-aliasing}
```suggestion
### Alias d'injection {#injection-aliasing}
```
Pas sûr de moi mais me paraît plus commun que Aliasing, QDT*?

**Qu'en Dit-Tu?*

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +Lors de l'utilisation de la syntaxe utilisant un tableau pour `inject`, les propriétés injectées sont exposées sur l'instance de composant à l'aide de la même clé. Dans l'exemple ci-dessus, la propri
```suggestion
Si la syntaxe utilisée avec `inject` est sous la forme d'un tableau, les propriétés injectées sont exposées sur l'instance de composant à l'aide de la même clé. Dans l'exemple ci-dessus, la propriété a été fournie sous la clé `"message"` et injectée en tant que `this.message`. La clé locale est la même que la clé d'injection.
```

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +Si nous voulons injecter la propriété en utilisant une clé locale différente, nous devons utiliser la syntaxe utilisant un objet avec l'option `inject` :
```suggestion
Si nous voulons injecter la propriété en utilisant une clé locale différente, nous devrions utiliser la syntaxe sous la forme d'un objet avec l'option `inject` :
```

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
>  const value = inject('message', 'default value')
je me demande si les chaînes de caractères pourraient pas non plus être traduite.. ici `valeur par défaut` ferait du sens

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +## Travailler avec réactivité {#working-with-reactivity}
```suggestion
## Injections réactives {#working-with-reactivity}
```
ça illustre bien cette partie je pense

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +Lors de l'utilisation de valeurs de réactives avec provide / inject, **il est recommandé de conserver toutes les mutations des l'état réactif à l'intérieur du _fournisseur_ dans la mesure du possible
```suggestion
Lors de l'utilisation de valeurs de réactives avec provide / inject, **il est recommandé de conserver toutes les mutations d'un état réactif à l'intérieur du _fournisseur_ dans la mesure du possible**. Cela garantit que l'état fourni et ses éventuelles mutations sont localisés dans le même composant, ce qui facilite sa maintenabilité à l'avenir.
```
co-localisés me semble un peu répétitif avec dans le même composant.

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
Je trouve dommage de ne pas traduire les textes.. Pôle Nord ça le ferait plus nan?

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +La fonction `computed()` est généralement utilisée dans les composants utilisant l'API Composition, mais peut également être utilisée pour compléter certains cas d'usage avec l'API Options. Vous pouv
```suggestion
La fonction `computed()` est généralement utilisée dans les composants utilisant la Composition API, mais peut également être utilisée pour compléter certains cas d'usage avec l'Options API. Vous pouvez en savoir plus sur son utilisation en lisant [les principes de base de la réactivité](/guide/essentials/reactivity-fundamentals.html) et [les propriétés calculées](/guide/essentials/computed.html) avec la préférence d'API définie sur Composaition API.
```
Voir Glossaire

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +## Travailler avec les Symbols en tant que clés {#working-with-symbol-keys}
```suggestion
## Injection avec des Symbols en tant que clés {#working-with-symbol-keys}
```

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +Jusqu'à présent, nous avons utilisé des clés d'injection qui étaient des chaînes de caractères dans les exemples. Si vous travaillez dans une application de taille importante avec de nombreux fournis
```suggestion
Jusqu'à présent, nous avons utilisé dans les exemples des clés d'injection qui étaient des chaînes de caractères. Si vous travaillez dans une application de taille importante avec de nombreux fournisseurs de dépendances, ou si vous créez des composants qui seront utilisés par d'autres développeurs, il est préférable d'utiliser des clés d'injection utilisant des Symbols pour éviter les collisions potentielles.
```

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
_data to provide_ est à traduire

2022-11-02 21:55 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +// dans le composant injecteur
```suggestion
// dans le composant fournisseur
```

2022-11-03 09:04 UTC, 8HoLoN commented on src/guide/components/provide-inject.md
> +Habituellement, lorsque nous devons transmettre des données du parent à un composant enfant, nous utilisons des [props](/guide/components/props). Cependant, imaginez le cas où nous avons un arbre de
Non pour ce projet de traduction, je commit depuis github directement.

2022-11-03 09:07 UTC, 8HoLoN commented on src/guide/components/provide-inject.md
> +La fonction `provide()` accepte deux arguments. Le premier argument est appelé la **clé d'injection**, qui peut être une chaîne de caractères ou un `Symbol`. La clé d'injection est utilisée par les c
Je suis d'accord, typo here

2022-11-03 09:10 UTC, 8HoLoN commented on src/guide/components/provide-inject.md
> +La fourniture de valeurs réactives permet aux composants descendants utilisant la valeur fournie d'établir une connexion réactive au composant fournisseur.
en effet

2022-11-03 09:14 UTC, 8HoLoN commented on src/guide/components/provide-inject.md
> +Pour chaque propriété de l'objet `provide`, la clé est utilisée par les composants enfants pour localiser la valeur correcte à injecter, tandis que la valeur est ce qui finit par être injecté.
hmm, non ça s'accorde avec "ce", sinon ce devrait être "la valeur est celle qui finit par être injectée." mais on ne dit jamais ça. Argument supplémentaire ?

2022-11-03 09:25 UTC, 8HoLoN commented on src/guide/components/provide-inject.md
Done

2022-11-03 09:29 UTC, 8HoLoN commented on src/guide/components/provide-inject.md
> +// dans le composant injecteur
hmm, non le composant fournisseur est celui qui utilise `provide` ou alors je vois plutôt changer "composant injecteur" par "composant réalisant l'injection" ?

2022-11-03 09:41 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +// dans le composant injecteur
ha oui pardon.

2022-11-03 09:43 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +Pour chaque propriété de l'objet `provide`, la clé est utilisée par les composants enfants pour localiser la valeur correcte à injecter, tandis que la valeur est ce qui finit par être injecté.
Ben pour le coup je suis pour utiliser celle, car on parle bien de la valeur

2022-11-03 13:45 UTC, 8HoLoN commented on src/guide/components/provide-inject.md
hmm, je ne pense pas, si l'exemple manipule les chaines, le résultat peut être différent si on modifie le contenu. Donc pas fan de cette approche

2022-11-03 13:46 UTC, 8HoLoN commented on src/guide/components/provide-inject.md
> +[Exemple complet provide + inject avec réactivité](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgcHJvdmlkZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBDaGlsZCBmcm9tICcuL0NoaWxkLnZ1Z
? Je ne vois pas où ?

2022-11-03 13:49 UTC, 8HoLoN commented on src/guide/components/provide-inject.md
> +[Exemple complet provide + inject](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCBDaGlsZCBmcm9tICcuL0NoaWxkLnZ1ZSdcblxuZXhwb3J0IGRlZmF1bHQge1xuICBjb21wb25lbnRzOiB7IENoaWxkIH0sXG4gIHByb
On ne modifie pas les playgrounds ??

2022-11-03 13:51 UTC, 8HoLoN commented on src/guide/components/provide-inject.md
> +[Exemple complet provide + inject avec réactivité](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgcHJvdmlkZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBDaGlsZCBmcm9tICcuL0NoaWxkLnZ1Z
Modifer le playground ?? (je ne suis pas pour)

2022-11-03 13:54 UTC, 8HoLoN commented on src/guide/components/provide-inject.md
>  const value = inject('message', 'default value')
je suis pas pour modifier les exemples au-delà des commentaires. (cela  peut impacter la logique du code, selon comment la chaine est pas la suite manipulée)

2022-11-03 14:13 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +[Exemple complet provide + inject](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCBDaGlsZCBmcm9tICcuL0NoaWxkLnZ1ZSdcblxuZXhwb3J0IGRlZmF1bHQge1xuICBjb21wb25lbnRzOiB7IENoaWxkIH0sXG4gIHByb
Si, on modifie mais uniquement traduire les commentaires.

2022-11-03 14:25 UTC, edimitchel requested changes

2022-11-03 14:25 UTC, edimitchel commented on src/guide/components/provide-inject.md
➡️ https://github.com/vuejs-translations/docs-fr/discussions/160

2022-11-08 09:21 UTC, edimitchel approved these changes

2022-11-08 09:22 UTC, merged