a11y : premier charpitre
vuejs-translations/docs-fr pull request #152
Opened 2022-10-30 19:23 UTC by marc-bouvier

Actions à vérifier 

- [ ] Ancres anglaises ajoutées à chaque titre traduits
- [ ] Nom de la page mise en cohérence avec les ancres qui pointe sur la page traduite 
  
- [ ] Lien de menu mis à jour
  
- [ ] PR liée à une issue
      Closes #

2022-10-31 10:53 UTC, marc-bouvier commented
> Nom de la page mise en cohérence avec les ancres qui pointe sur la page traduite

@edimitchel , je ne suis pas sûr de comprendre celle-là.

2022-10-31 18:58 UTC, edimitchel commented
> > - [ ] Nom de la page mise en cohérence avec les ancres qui pointe sur la page traduite
> 
> @edimitchel , je ne suis pas sûr de comprendre celle-là.

Simplement regarder là où il y a une référence vers la page traduite et traduire le nom de la page quand elle est au format titre de page.

2022-11-01 20:07 UTC, edimitchel approved these changes
Pour l'instant, ce que tu as traduit me convient. J'attends la suite!

2022-11-25 14:52 UTC, tlagoda submitted a review, later dismissed

2022-12-11 21:54 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +:::tip Astuce:
Petit espace entre Astuce et :

2023-02-10 14:22 UTC, ElisePatrikainen commented
Des news 😁 ?

2023-02-14 22:23 UTC, marc-bouvier commented
J'ai pu trouver de la motivation pour faire une première passe complète en français. C'est pas parfait. Mais ca permet au moin de faire une revue plus exhaustive.
A vous! ;-)

2023-02-15 08:10 UTC, edimitchel commented
Peux-tu reset les changements sur le lock?

2023-02-16 22:38 UTC, edimitchel requested changes
Wordwrap à désactiver pour ce projet: object lignes ajoutées === lignes supprimées

2023-02-16 22:38 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +
```suggestion
```

2023-02-16 22:38 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +appelant focus sur la ref template du lien d'évitement (en supposant l'utilisation de `vue-router`):
```suggestion
Lorsque qu'un utilisateur change d'itinéraire, redonnez le focus sur le lien d'évitement. Cela peut être réalisé en appelant focus sur la ref template du lien d'évitement (en supposant l'utilisation de `vue-router`):
```
Attention, pas de saut de ligne supplémentaire, il faut garder autant de lignes ajoutées que de supprimées

2023-02-16 22:38 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +
```suggestion
```

2023-02-16 22:38 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +
```suggestion
```

2023-02-16 22:38 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +L'un des éléments les plus importants de l'accessibilité est de s'assurer que le design peut soutenir une mise en œuvre
Il semble que tu aies un word wrap d'activer, désactive le pour ce projet si possible :)

2023-02-16 22:38 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +| `<section>`     | role="region"        | Cpntenus pertinents vers lesquels les utilisateurs sont susceptibles de naviguer. Un libellé doit être fourni pour cet élément |
```suggestion
| `<section>`     | role="region"        | Contenus pertinents vers lesquels les utilisateurs sont susceptibles de naviguer. Un libellé doit être fourni pour cet élément |
```

2023-02-19 21:31 UTC, marc-bouvier commented on src/guide/best-practices/accessibility.md
> +L'un des éléments les plus importants de l'accessibilité est de s'assurer que le design peut soutenir une mise en œuvre
yep, bien vu, webstorm a des options de formattage activées par défaut.

2023-02-19 21:35 UTC, marc-bouvier commented on src/guide/best-practices/accessibility.md
> +:::tip Astuce:
Est-ce toujours d'actualité? ou le code ets bon maintenant?

2023-02-19 22:00 UTC, edimitchel requested changes

2023-02-19 22:00 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
>  - [Web Accessibility Perspectives: Explore the Impact and Benefits for Everyone](https://www.w3.org/WAI/perspective-videos/)
Si le titre d'un lien n'a pas un lien fort avec le contenu, il peut être traduit (par exemple un titre de livre on traduit pas, si c'est un contenu d'une doc, on peut traduire le titre)

2023-02-20 11:42 UTC, marc-bouvier commented on src/guide/best-practices/accessibility.md
>    - [NerdeFocus](https://chrome.google.com/webstore/detail/nerdefocus/lpfiljldhgjecfepfljnbjnbjfhennpd?hl=en-US…)
Ah, oui, bien vu

2023-02-20 12:18 UTC, marc-bouvier commented
TIL:
- En français, espace insécable avant `:`
- Si le titre d'un lien n'a pas un lien fort avec le contenu, il peut être traduit 
- Par défaut, mon éditeur de code wraps les lignes en markdown alors que je ne le veux pas
-

2023-02-20 12:43 UTC, edimitchel approved these changes

2023-02-21 08:37 UTC, edimitchel requested changes

2023-02-21 08:37 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +- [Perspectives sur l'accessibilité du Web: En explorer les imapacts et bénifices pour tous](https://www.w3.org/WAI/perspective-videos/)
```suggestion
- [Perspectives sur l'accessibilité du Web: En explorer les impacts et bénéfices pour tous](https://www.w3.org/WAI/perspective-videos/)
```

2023-02-21 08:38 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +    <label for="search" class="hidden-visually">Recherche: </label>
```suggestion
    <label for="search" class="hidden-visually">Recherche : </label>
```

2023-02-21 08:38 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +Regardons ce champ de recherche:
```suggestion
Regardons ce champ de recherche :
```

2023-02-21 08:38 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +  <label id="dob" for="dob">Date de naissance:</label>
```suggestion
  <label id="dob" for="dob">Date de naissance :</label>
```

2023-02-21 08:38 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +  <label id="date-label" for="date">Date courante:</label>
```suggestion
  <label id="date-label" for="date">Date courante :</label>
```

2023-02-21 08:39 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +    <label for="name">Nom complet:</label>
```suggestion
    <label for="name">Nom complet :</label>
```

2023-02-21 08:39 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +Utiliser [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) est similaire à `aria-label` à l'exception du fait que c'est utilisé si le lib
```suggestion
Utiliser [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) est similaire à `aria-label` à l'exception du fait que c'est utilisé si le libellé est visible à l'écran. Associez-le à d'autres éléments par leurs `id` et vous pourrez associer plusieurs `id`s :
```

2023-02-21 08:39 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +Lors de la création d'un formulaire, vous pouvez utiliser les éléments suivants: `<form>`, `<label>`, `<input>`, `<textarea>`, et `<button>`
```suggestion
Lors de la création d'un formulaire, vous pouvez utiliser les éléments suivants : `<form>`, `<label>`, `<input>`, `<textarea>`, et `<button>`
```

2023-02-21 08:39 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +Lorsque qu'un utilisateur change d'itinéraire, redonnez le focus sur le lien d'évitement. Cela peut être réalisé en appelant focus sur la ref template du lien d'évitement (en supposant l'utilisation
```suggestion
Lorsque qu'un utilisateur change d'itinéraire, redonnez le focus sur le lien d'évitement. Cela peut être réalisé en appelant focus sur la ref template du lien d'évitement (en supposant l'utilisation de `vue-router`) :
```

2023-02-21 12:34 UTC, tlagoda commented on src/guide/best-practices/accessibility.md
> +  <label id="date-label" for="date">Date courante:</label>
J'aurais plutôt vu `actuelle`
```suggestion
  <label id="date-label" for="date">Date actuelle :</label>
```

2023-02-21 12:34 UTC, tlagoda commented on src/guide/best-practices/accessibility.md
> +Utiliser [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) est similaire à `aria-label` à l'exception du fait que c'est utilisé si le lib
on enlève pas le s à id ?
```suggestion
Utiliser [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) est similaire à `aria-label` à l'exception du fait que c'est utilisé si le libellé est visible à l'écran. Associez-le à d'autres éléments par leurs `id` et vous pourrez associer plusieurs `id` :
```

2023-02-21 12:36 UTC, edimitchel commented on src/guide/best-practices/accessibility.md
> +Utiliser [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) est similaire à `aria-label` à l'exception du fait que c'est utilisé si le lib
effectivement

2023-02-21 22:55 UTC, marc-bouvier commented on src/guide/best-practices/accessibility.md
> +Utiliser [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) est similaire à `aria-label` à l'exception du fait que c'est utilisé si le lib
Effectivement on l'enlève ou effectivement on l'enlève pas?

2023-02-21 23:47 UTC, edimitchel requested changes
```diff
diff --git a/src/guide/best-practices/accessibility.md b/src/guide/best-practices/accessibility.md
index 68e0b4e0..1fd77552 100644
--- a/src/guide/best-practices/accessibility.md
+++ b/src/guide/best-practices/accessibility.md
@@ -118,10 +118,10 @@ Les utilisateurs peuvent naviguer dans une application à travers les titres. Le
 
 | HTML            | ARIA Role            | But du landmark                                                                                                                |
 |-----------------|----------------------|--------------------------------------------------------------------------------------------------------------------------------|
-| header          | role="banner"        | Entête principales: titre de la page\*                                                                                         |
+| header          | role="banner"        | Entête principales : titre de la page\*                                                                                         |
 | nav             | role="navigation"    | Collection de liens utilisables lors de la navigation dans le document ou vers des documents associés                          |
 | main            | role="main"          | Le contenu central ou principal du document.                                                                                   |
-| footer          | role="contentinfo"   | Information à propos du document parent: notes de pied de page/copyrights/liens vers la déclaration de confidentialité         |
+| footer          | role="contentinfo"   | Information à propos du document parent : notes de pied de page/copyrights/liens vers la déclaration de confidentialité         |
 | aside           | role="complementary" | Supporte le contenu principale, malgré tout est séparé et a du sens par lui-même                                               |
 | _Not available_ | role="search"        | Cette section contient la fonctionnalité de recherche pour l'application                                                       |
 | form            | role="form"          | Collection d'éléments associés à un formulaire                                                                                 |
@@ -209,7 +209,7 @@ N'hésitez pas à inspecter cet élément dans les outils de développeur de Chr
 
 #### `aria-labelledby` {#aria-labelledby}
 
-Utiliser [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) est similaire à `aria-label` à l'exception du fait que c'est utilisé si le libellé est visible à l'écran. Associez-le à d'autres éléments par leurs `id` et vous pourrez associer plusieurs `id`s:
+Utiliser [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) est similaire à `aria-label` à l'exception du fait que c'est utilisé si le libellé est visible à l'écran. Associez-le à d'autres éléments par leurs `id` et vous pourrez associer plusieurs `id` :
 
 ```vue-html
 <form
@@ -362,7 +362,7 @@ Regardons ce champ de recherche :
 
 ```vue-html
 <form role="search">
-  <label for="search" class="hidden-visually">Recherche: </label>
+  <label for="search" class="hidden-visually">Recherche : </label>
   <input type="text" name="search" id="search" v-model="search" />
   <button type="submit">Recherche</button>
 </form>
@@ -524,7 +524,7 @@ WAI-ARIA du W3C fournit des conseils sur comment construire du contenu dynamique
 
 L'Organisation Mondiale de la Santé estime que 15% de la population mondiale est atteinte d'une forme de handicap, 2-4% d'entre elle de handicaps sévères. Ceci est estimé à 1 milliard de personnes dans le monde ; faisant des personnes avec un handicap la plus grande minorité au monde.
 
-Il y a un large spectre de handicaps, qui peut être divisé grosso-modo en quatre catégories:
+Il y a un large spectre de handicaps, qui peut être divisé grosso-modo en quatre catégories :
 
 - _[Visuel](https://webaim.org/articles/visual/)_ - Ces utilisateurs peuvent bénéficier de l'utilisation de liseurs d'écran, d'outils d'agrandissement, du contrôle du contraste ou de plage braille.
 - _[Auditif](https://webaim.org/articles/auditory/)_ - Ces utilisateurs peuvent bénéficier de sous-titres, de transcriptions ou de vidéos en langages des signes.
@@ -533,5 +533,5 @@ Il y a un large spectre de handicaps, qui peut être divisé grosso-modo en quat
 
 Rendez-vous aux liens suivants de WebAim pour comprendre via des retours d'expérience d'utilisateurs :
 
-- [Perspectives sur l'accessibilité du Web: En explorer les impacts et bénéfices pour tous](https://www.w3.org/WAI/perspective-videos/)
+- [Perspectives sur l'accessibilité du Web : En explorer les impacts et bénéfices pour tous](https://www.w3.org/WAI/perspective-videos/)
 - [Histoires d'utilisateurs du Web](https://www.w3.org/WAI/people-use-web/user-stories/)
```
À appliquer avec `git patch`, je ne peux faire les modifs moi-même.

2023-02-24 10:07 UTC, marc-bouvier commented
Zut, j'ai foiré mon merge.
Je crois que je vais faire une nouvelle fork et une nouvelle MR. Sinon ca va juste être la grosse galère.

2023-02-24 10:18 UTC, marc-bouvier commented
Remplacé par https://github.com/vuejs-translations/docs-fr/pull/354 avec un historique git propre.
RIP.

2023-02-24 10:18 UTC, closed without merging