151 guide components events md
vuejs-translations/docs-fr pull request #155
Opened 2022-11-02 16:57 UTC by 8HoLoN

Actions à vérifier 

- [ ] Ancres anglaises ajoutées à chaque titre traduits
- [ ] Nom de la page mise en cohérence avec les ancres qui pointe sur la page traduite 
  
- [ ] Lien de menu mis à jour
  
- [ ] PR liée à une issue
      Closes #151

2022-11-02 22:21 UTC, edimitchel requested changes

2022-11-02 22:21 UTC, edimitchel commented on src/guide/components/events.md
>    <VueSchoolLink href="https://vueschool.io/lessons/defining-custom-events-emits" title="Free Vue.js Lesson on Defining Custom Events"/>
```suggestion
  <VueSchoolLink href="https://vueschool.io/lessons/defining-custom-events-emits" title="Free Vue.js Lesson on Defining Custom Events (EN)"/>
```

2022-11-02 22:21 UTC, edimitchel commented on src/guide/components/events.md
> +Un composant peut émettre des événements personnalisés directement à partir du template (par exemple, dans un gestionnaire d'évènement`v-on`) à l'aide de la méthode native `$emit` :
```suggestion
Un composant peut émettre des événements personnalisés directement à partir du template (par exemple, dans un gestionnaire d'événement `v-on`) à l'aide de la méthode native `$emit` :
```

2022-11-02 22:21 UTC, edimitchel commented on src/guide/components/events.md
> +## Arguments d'événement  {#event-arguments}
```suggestion
## Arguments d'événement {#event-arguments}
```

2022-11-02 22:21 UTC, edimitchel commented on src/guide/components/events.md
> +Il est parfois utile d'émettre une valeur spécifique avec un événement. Par exemple, nous pouvons vouloir que le composant `<BlogPost>` soit en charge de combien agrandir le texte. Dans ces cas, nous
```suggestion
Il est parfois utile d'émettre une valeur spécifique avec un événement. Par exemple, nous pouvons vouloir que le composant `<BlogPost>` soit en charge d'agrandir plus ou moins le texte. Dans ces cas, nous pouvons passer des arguments supplémentaires à `$emit` pour fournir cette valeur :
```

2022-11-02 22:21 UTC, edimitchel commented on src/guide/components/events.md
> +Semblable à la validation de type de prop, un événement émis peut être validé s'il est défini avec la syntaxe utilisant un objet au lieu de la syntaxe utilisant un tableau.
```suggestion
Semblable à la validation de type de prop, un événement émis peut être validé s'il est défini avec la syntaxe utilisant un objet au lieu d'un tableau.
```

2022-11-02 22:21 UTC, edimitchel commented on src/guide/components/events.md
> +En tirant parti de la possibilité de cibler un prop et un événement particuliers, comme nous l'avons appris précédemment avec [`v-model` arguments](#v-model-arguments), nous pouvons désormais créer p
```suggestion
En tirant parti de la possibilité de cibler un prop et un événement particuliers, comme nous l'avons appris précédemment avec [les arguments de `v-model`](#v-model-arguments), nous pouvons désormais créer plusieurs liaisons v-model sur une seule instance de composant.
```

2022-11-02 22:21 UTC, edimitchel commented on src/guide/components/events.md
> +Pour les liaisons `v-model` avec à la fois argument et modificateurs, le nom de la prop généré sera `arg + "Modifiers"`. Par exemple:
```suggestion
Pour les liaisons `v-model` avec à la fois argument et modificateurs, le nom de la prop généré sera `arg + "Modificateurs"`. Par exemple:
```

2022-11-03 10:23 UTC, 8HoLoN commented on src/guide/components/events.md
> +Un composant peut émettre des événements personnalisés directement à partir du template (par exemple, dans un gestionnaire d'évènement`v-on`) à l'aide de la méthode native `$emit` :
Non "évènement" est la forme correcte validée par l'Académie Française

2022-11-03 10:24 UTC, edimitchel commented on src/guide/components/events.md
> +Un composant peut émettre des événements personnalisés directement à partir du template (par exemple, dans un gestionnaire d'évènement`v-on`) à l'aide de la méthode native `$emit` :
Ok, alors il faut l'appliquer partout, mais surtout, y a un espace qui manque

2022-11-03 10:46 UTC, 8HoLoN commented on src/guide/components/events.md
> +Pour les liaisons `v-model` avec à la fois argument et modificateurs, le nom de la prop généré sera `arg + "Modifiers"`. Par exemple:
il s'agit là du nom de la clé, il ne faut pas la traduire

2022-11-03 11:06 UTC, edimitchel commented on src/guide/components/events.md
> +Pour les liaisons `v-model` avec à la fois argument et modificateurs, le nom de la prop généré sera `arg + "Modifiers"`. Par exemple:
oups, effectivement ;)

2022-11-03 12:37 UTC, edimitchel approved these changes

2022-11-08 09:20 UTC, edimitchel approved these changes

2022-11-08 09:20 UTC, merged