guide/components/slots
vuejs-translations/docs-fr pull request #194
Opened 2022-11-08 17:51 UTC by 8HoLoN

**Actions à effectuer :**

- [ ] Ajouter ancres anglaises à chaque titre traduits  
  
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres page  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes #174
      
Remarques:

2022-11-17 14:30 UTC, edimitchel requested changes

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
> +## Contenu de Slot Content and Outlet
```suggestion
## Les contenus de slot {#slot-content-and-outlet}
```

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
>    <slot></slot> <!-- slot outlet -->
```suggestion
  <slot></slot> <!-- emplacement du slot -->
```

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
> +L'élément `<slot>` est un **slot outlet** qui indique où le **contenu du slot** fourni par le parent doit être affiché.
```suggestion
L'élément `<slot>` est un **emplacement du slot** qui indique où le **contenu du slot** fourni par le parent doit être affiché.
```

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
>  ![slot diagram](./images/slots.png)
Le diagramme doit être mis à jour

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
>  <!-- https://www.figma.com/file/LjKTYVL97Ck6TEmBbstavX/slot -->
```suggestion
<!-- https://www.figma.com/file/uXgOHSQYUcc1elWGPTskfs/slot -->
```

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
>  ![slot diagram](./images/slots.png)
👇🏻

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
> +Le mécanisme de slot des composants Vue est inspiré de l'[élément natif Web Component `<slot>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot), mais avec des fonctionnalités suppléme
```suggestion
Le mécanisme de slot des composants Vue est inspiré de l'[élément natif Web Component `<slot>`](https://developer.mozilla.org/fr/docs/Web/HTML/Element/slot), mais avec des fonctionnalités supplémentaires que nous verrons plus tard.
```

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
> +Le contenu du slot a accès à la portée des données du composant parent, car il est défini dans le parent. Par exemple:
```suggestion
Le contenu du slot a accès à la portée des données du composant parent, car il est défini dans le parent. Par exemple :
```

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
> +Le contenu du slot **n'a pas** accès aux données du composant enfant. Les expressions dans les templates Vue ne peuvent accéder qu'à la portée de déclaration dans laquelle elles sont définies, confor
```suggestion
Le contenu du slot **n'a pas** accès aux données du composant enfant. Les expressions dans les templates Vue ne peuvent accéder qu'à la portée de déclaration dans laquelle elles sont définies, conformément à la portée lexicale de JavaScript. Autrement dit :
```

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
> +> Les expressions présentes dans template parent n'ont accès qu'à la portée parent ; les expressions dans le template enfant n'ont accès qu'à la portée composant enfant.
```suggestion
> Les expressions présentes dans le template du parent n'ont accès qu'à la portée du parent ; les expressions dans le template de l'enfant n'ont accès qu'à la portée du composant enfant.
```

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
> +Il y a des moments où il est utile d'avoir plusieurs "slot outlets" dans un seul composant. Par exemple, dans un composant `<BaseLayout>` avec le template suivant :
```suggestion
Il y a des moments où il est utile d'avoir plusieurs emplacements de slot dans un seul composant. Par exemple, dans un composant `<BaseLayout>` avec le template suivant :
```

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
> +Dans un composant parent utilisant `<BaseLayout>`, nous avons besoin d'un moyen de transmettre plusieurs fragments de contenu de slot, chacun ciblant un "slot outlet" différent. C'est là qu'intervien
```suggestion
Dans un composant parent utilisant `<BaseLayout>`, nous avons besoin d'un moyen de transmettre plusieurs fragments de contenu de slot, chacun ciblant un emplacement de slot différent. C'est là qu'interviennent les **slots nommés**.
```

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
>  <!-- https://www.figma.com/file/2BhP8gVZevttBu9oUmUUyz/named-slot -->
```suggestion
<!-- https://www.figma.com/file/0qMPF90unxH9VYhCTk1ohx/named-slot -->
```
Image à exporter.

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
> +// <BaseLayout> les affiche à différents endroits
```suggestion
// <BaseLayout> les affiche à différents emplacements
```

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
> +Cependant, il existe des cas où il peut être utile que le contenu d'un slot puisse utiliser des données provenant à la fois de la portée parent et de la portée enfant. Pour y parvenir, nous avons bes
```suggestion
Cependant, il existe des cas où il peut être utile que le contenu d'un slot puisse utiliser des données provenant à la fois de la portée du parent et de la portée de l'enfant. Pour y parvenir, nous avons besoin d'un moyen pour l'enfant de transmettre des données à un slot pour son affichage.
```

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
> +En fait, nous pouvons faire exactement cela - nous pouvons transmettre des attributs à un "slot outlet" comme on transmettrait des props à un composant :
```suggestion
En fait, nous pouvons faire exactement cela - nous pouvons transmettre des attributs à un emplacement de slot comme on transmettrait des props à un composant :
```

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
>  <MyComponent v-slot="slotProps">
Line 341, le diagramme à modifier

2022-11-17 14:30 UTC, edimitchel commented on src/guide/components/slots.md
>  <MyComponent v-slot="slotProps">
https://www.figma.com/file/F0hkenMuKr2aczzl2OIkLd/scoped-slot

2022-11-25 15:33 UTC, tlagoda submitted a review, later dismissed
Traduction ok, manque la mise à jour des diagrammes

2022-12-07 14:07 UTC, edimitchel commented on src/guide/components/slots.md
>  ![slot diagram](./images/slots.png)
Effectué
https://github.com/vuejs-translations/docs-fr/pull/194/files/6658ca6424e47ce1dee312c8ac8ac8e584185483..4efee081a97901298436065d4aeff7b26223b764

2022-12-07 14:08 UTC, edimitchel approved these changes

2022-12-07 14:09 UTC, merged