DRAFT: chore complete the rest of the tutorial
vuejs-translations/docs-fr pull request #221
Opened 2022-11-28 03:47 UTC by kissu

**Actions à effectuer :**

- [x] Ajouter ancres anglaises à chaque titre traduits  
  
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres page  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #149 
      
Remarques:
- me and my partner will give it a second read to be sure that it is not poorly written + no grammar issues. 👌🏻

2022-11-28 15:24 UTC, edimitchel requested changes
J'observe 241 lignes ajoutées mais 236 supprimés, à un endroit que j'ai identifié, je n'ai pas vu où il y a eu des ajouts sans suppressions..

Il faut que le nombre de lignes ajoutées égale le nombre de lignes supprimées

2022-11-28 15:24 UTC, edimitchel commented on src/tutorial/src/step-8/description.md
> +Voici de <a target="_blank" href="/guide/essentials/computed.html">`computed()`</a>. Nous pouvons créer une réf calculée qui calcule sa `.value` en fonction d'autres sources de données réactives :
```suggestion
Voici <a target="_blank" href="/guide/essentials/computed.html">`computed()`</a>. Nous pouvons créer une réf calculée qui calcule sa `.value` en fonction d'autres sources de données réactives :
```

2022-11-28 15:24 UTC, edimitchel commented on src/tutorial/src/step-10/description.md
> +`watch()` peut directement observer une ref, et le callback sera appelé dès que la valeur de `count` change. `watch()` peut aussi observer d'autres type de sources de données - davantage de détails s
```suggestion
`watch()` peut directement observer une ref, et le callback sera appelé dès que la valeur de `count` change. `watch()` peut aussi observer d'autres types de source de données - davantage de détails sont disponibles dans <a target="_blank" href="/guide/essentials/watchers.html">Guide - Observateurs</a>.
```

2022-11-28 15:24 UTC, edimitchel commented on src/tutorial/src/step-3/App/template.html
> +<h1>Passez moi au rouge</h1> <!-- ajoutez la liaison de la classe dynamique ici -->
```suggestion
<h1>Passez moi en rouge</h1> <!-- ajoutez la liaison de la classe dynamique ici -->
```

2022-11-28 18:11 UTC, kissu commented on src/tutorial/src/step-3/description.md
> +Dans Vue, la syntaxe des moustaches ne sert que pour l'intérpolation du texte. Pour lier un attribut à une valeur dynamique, nous utilisons la directive `v-bind` :
Done, remove ailleurs. ✅

2022-11-28 18:14 UTC, kissu commented on src/tutorial/src/step-11/App/template.html
> +<!-- render du composant enfant -->
Same ici pour le `render`, je pense pas qu'il faudrait traduire.

2022-11-28 18:17 UTC, kissu commented on src/tutorial/src/step-10/description.md
> +`watch()` peut directement observer une ref, et le callback sera appelé dès que la valeur de `count` change. `watch()` peut aussi observer d'autres type de sources de données - davantage de détails s
En fait, c'est même `types de sources`. 😂

2022-11-28 18:38 UTC, kissu commented
Je vais double-check la diff entre les lignes, je sais que j'ai un setting VScode qui m'en ajoute une à la fin de certaines. Vais double-check. 👌🏻

2022-11-29 03:03 UTC, kissu commented on src/tutorial/src/step-11/App/template.html
> +<!-- render du composant enfant -->
Got a discussion about that [on Discord](https://discord.com/channels/920681777411006536/941099693834920006/1046853950562906112), I guess we will indeed replace `render`.

2022-11-29 09:29 UTC, edimitchel commented on src/tutorial/src/step-11/App/template.html
> +<!-- render du composant enfant -->
Je pense qu'il est bon de faire la distinction entre:
- render => rendu dom/template
- display => affichage graphique
Pour moi `rendu` est plus correct ici

2022-11-29 10:11 UTC, kissu commented on src/tutorial/src/step-11/App/template.html
> +<!-- render du composant enfant -->
Après, la différence entre `rendu` et `affichage` est assez fine je pense.
Une personne pourrait se dire que c'est la même chose, d'où le fait que j'ai voulu utiliser `render`, pour bien faire la différence.

2022-11-29 10:17 UTC, kissu commented on src/tutorial/src/step-11/App/template.html
> +<!-- render du composant enfant -->
Ma chérie est clairement contre le fait de traduire `render` aussi.
Les boîtes fr où elle a bossé ont toujours utilisé ce terme là.
Possible de l'ajouter ici? https://github.com/SpookyUmi

2022-11-29 10:23 UTC, SpookyUmi commented on src/tutorial/src/step-11/App/template.html
> +<!-- render du composant enfant -->
Hello ! C'est moi, la chérie hehe
Selon moi il n'y a pas de débat pour le terme `render`. C'est un terme qui porte une connotation forte, c'est un terme technique et il n'y a simplement pas d'équivalent en FR. On ne traduirait pas `hooks` ou `switch` etc. Le but de la traduction en elle-même c'est de permettre aux francophones de comprendre et suivre la doc/les tutoriels, le but n'est pas de traduire chaque terme technique, ca n'a pas de sens, ca va juste desservir les gens qui vont lire. Car dans le mondre pro, même en FR, les termes techniques importants restent les mêmes qu'en anglais.

2023-01-08 22:09 UTC, edimitchel approved these changes

2023-01-08 22:10 UTC, merged

2023-01-09 03:45 UTC, kissu commented
Je referai une PR pour des micro-modifs via le feedback de ma chérie. 👌🏻