Component basics translation
vuejs-translations/docs-fr pull request #224
Opened 2022-12-01 08:51 UTC by tlagoda

**Actions à effectuer :**

- [x] Ajouter ancres anglaises à chaque titre traduits  
  
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres page  
  
- [ ] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #135  
      
Remarques:

2022-12-01 17:15 UTC, edimitchel requested changes
Attention aux ponctuations, en français, y a un espace avant les `:`.

[Tag => Balise](https://developer.mozilla.org/fr/docs/Glossary/Tag)
```diff
- tag 
+ balise
```

2022-12-01 17:15 UTC, edimitchel commented on src/guide/essentials/component-basics.md
> +`defineProps` est une macro de compilation qui est seulement accessible à l'intérieur de `<script setup>` et ne nécessite pas d'être explicitement importée. Les props déclarées sont automatiquement e
```suggestion
`defineProps` est une macro de compilation qui est seulement accessible à l'intérieur de `<script setup>` et ne nécessite pas d'être explicitement importée. Les props déclarées sont automatiquement exposées au template. `defineProps` retourne également un objet contenant toutes les propriétés passées au composant, de manière à ce que l'on puisse y accéder en JavaScript si nécessaire :
```

2022-12-01 17:15 UTC, edimitchel commented on src/guide/essentials/component-basics.md
> +Un composant peut avoir autant de props que vous voulez, et, par défaut, n'importe quelle valeur peut être passée à une prop.
```suggestion
Un composant peut avoir autant de props que vous voulez, et par défaut, n'importe quelle valeur peut être passée à une prop.
```

2022-12-01 17:15 UTC, edimitchel commented on src/guide/essentials/component-basics.md
> +Pour le moment le bouton ne fait rien - nous voulons que le clique communique au parent qu'il doit agrandir le texte de tous les articles. Pour résoudre ce problème, les composants fournissent un sys
```suggestion
Pour le moment le bouton ne fait rien - nous voulons que le clic communique au parent qu'il doit agrandir le texte de tous les articles. Pour résoudre ce problème, les composants fournissent un système personnalisé d'événements. Le parent peut choisir d'écouter n'importe quel événement de l'instance du composant enfant grâce à `v-on` ou `@`, comme nous le ferions avec un événement natif du DOM :
```

2022-12-01 17:15 UTC, edimitchel commented on src/guide/essentials/component-basics.md
> +Dans le cas où vous n'utilisez pas `<script setup>`, vous pouvez déclarer les événements émis en utilisant l'option `emits. Vous pouvez accéder à la fonction `emit` via une propriété du contexte du s
```suggestion
Dans le cas où vous n'utilisez pas `<script setup>`, vous pouvez déclarer les événements émis en utilisant l'option `emits`. Vous pouvez accéder à la fonction `emit` via une propriété du contexte du setup (passé à `setup()` en deuxième argument) :
```

2022-12-01 17:15 UTC, edimitchel commented on src/guide/essentials/component-basics.md
> +Comme vous le verrez, nous utilisons `<slot>` comme un espace réservé où nous voulons que le contenu aille – et c'est tout. Nous avons terminé!
```suggestion
Comme vous le verrez, nous utilisons `<slot>` comme un espace réservé où nous voulons que le contenu aille – et c'est tout. Nous avons terminé !
```

2022-12-01 17:15 UTC, edimitchel commented on src/guide/essentials/component-basics.md
> +Lorsqu'on alterne entre plusieurs composants avec `<component :is="...">`, le composant 'partant' sera démonté. On peut forcer les composants inactifs à rester "en vie" grâce au [composant intégré `<
`partant` me semble bon mais peut-être perfectible.
@8HoLoN @kissu ? Une idée?

2022-12-01 17:15 UTC, edimitchel commented on src/guide/essentials/component-basics.md
> +Il est important de rappeler que les limitations que nous venons d'aborder ne s'appliquent que lorsque vous écrivez vos templates directement dans le DOM. Elles ne s'appliquent PAS si vous utilisez d
```suggestion
Il est important de rappeler que les limitations que nous allons d'aborder ne s'appliquent que lorsque vous écrivez vos templates directement dans le DOM. Elles ne s'appliquent PAS si vous utilisez des templates en chaîne de caractères à partir des sources suivantes:
```

2022-12-01 17:15 UTC, edimitchel commented on src/guide/essentials/component-basics.md
> +Les tags HTML et les noms des attributs sont insensibles à la casse, donc les navigateurs interpréteront une lettre majuscule comme une lettre minuscule. Cela signifie que lorsque vous utilisez des t
```suggestion
Les balises HTML et les noms des attributs sont insensibles à la casse, donc les navigateurs interpréteront une lettre majuscule comme une lettre minuscule. Cela signifie que lorsque vous utilisez des templates dans le DOM, les noms des composants en casse Pascal et les noms des propriétés en casse Camel ou encore les noms des événements `v-on` doivent tous utiliser leurs équivalent en casse Kebab (séparation par un trait d'union):
```

2022-12-01 17:15 UTC, edimitchel commented on src/guide/essentials/component-basics.md
> +### Tags auto-fermants {#self-closing-tags}
```suggestion
### Balises auto-fermantes {#self-closing-tags}
```

2022-12-01 17:15 UTC, edimitchel commented on src/guide/essentials/component-basics.md
> +C'est tout ce que vous avez besoin de savoir à propos des mises en garde concernant l'analyse du template DOM pour le moment - et d'ailleurs, la fin des _Essentiels_ de Vue. Congratulations! Il y a e
```suggestion
C'est tout ce que vous avez besoin de savoir à propos des mises en garde concernant l'analyse du template DOM pour le moment - et d'ailleurs, la fin des _Essentiels_ de Vue. Félicitations ! Il y a encore à apprendre, mais d'abord, nous vous recommandons de prendre une pause afin d'expérimenter Vue par vous-même - construisez quelque chose d'amusant, ou découvrez certains des [Exemples](/examples/) si ça n'est pas déjà fait.
```

2022-12-01 17:24 UTC, kissu commented on src/guide/essentials/component-basics.md
> +Lorsqu'on alterne entre plusieurs composants avec `<component :is="...">`, le composant 'partant' sera démonté. On peut forcer les composants inactifs à rester "en vie" grâce au [composant intégré `<
- Le composant "sortant"
- Le composant qui est désactivé
- Le composant "inactif"
- > Lorsqu'on alterne entre plusieurs composants avec `<component :is="...">`, seul celui sélectionné par `:is` reste monté.

2022-12-01 17:34 UTC, tlagoda commented on src/guide/essentials/component-basics.md
> +Lorsqu'on alterne entre plusieurs composants avec `<component :is="...">`, le composant 'partant' sera démonté. On peut forcer les composants inactifs à rester "en vie" grâce au [composant intégré `<
@kissu ta proposition de totalement changer la phrase me semble plus adaptée.

2022-12-01 17:35 UTC, kissu commented on src/guide/essentials/component-basics.md
> +Lorsqu'on alterne entre plusieurs composants avec `<component :is="...">`, le composant 'partant' sera démonté. On peut forcer les composants inactifs à rester "en vie" grâce au [composant intégré `<
cc @SpookyUmi

2022-12-02 10:54 UTC, SpookyUmi commented on src/guide/essentials/component-basics.md
> +Lorsqu'on alterne entre plusieurs composants avec `<component :is="...">`, le composant 'partant' sera démonté. On peut forcer les composants inactifs à rester "en vie" grâce au [composant intégré `<
@kissu ton dernier bullet point me semble bien

2022-12-02 13:15 UTC, edimitchel commented on src/guide/essentials/component-basics.md
> +Lorsqu'on alterne entre plusieurs composants avec `<component :is="...">`, le composant 'partant' sera démonté. On peut forcer les composants inactifs à rester "en vie" grâce au [composant intégré `<
Go for it @tlagoda

2022-12-02 14:32 UTC, merged

2022-12-07 13:13 UTC, 8HoLoN commented on src/guide/essentials/component-basics.md
> +Lorsqu'on alterne entre plusieurs composants avec `<component :is="...">`, le composant 'partant' sera démonté. On peut forcer les composants inactifs à rester "en vie" grâce au [composant intégré `<
idem, la dernière proposition me semble mieux.