guide/essentials/list.md
vuejs-translations/docs-fr pull request #234
Opened 2023-01-23 21:22 UTC by tlagoda

**Actions à effectuer :**

- [x] Ajouter ancres anglaises à chaque titre traduits  
  
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres page  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #233 
      
Remarques:

2023-01-23 21:33 UTC, edimitchel requested changes

2023-01-23 21:33 UTC, edimitchel commented on src/guide/essentials/list.md
> +Lorsque Vue met à jour une liste d'éléments rendue avec `v-for`, il utilise par défaut une stratégie de "réparation en place". Si l'ordre des données a changé, au lieu de déplacer les éléments du DOM
Réparation en place me semble pas approprié.
Ajustement sur sur place

2023-01-23 21:33 UTC, edimitchel commented on src/guide/essentials/list.md
> +Regardez [this example of a simple todo list](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBUb2RvSXRlbSBmcm9tICcuL1RvZG9JdGVtLnZ1ZSdcbiAgXG
Manque la traduction du titre du lien

2023-01-23 22:14 UTC, edimitchel requested changes

2023-01-23 22:14 UTC, edimitchel commented on src/guide/essentials/list.md
> +Regardez [cet exemple d'une simple todo liste](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBUb2RvSXRlbSBmcm9tICcuL1RvZG9JdGVtLnZ1ZSdcbiAgX
une todo list ou une liste de todo

2023-01-23 22:19 UTC, tlagoda commented on src/guide/essentials/list.md
> +Regardez [cet exemple d'une simple todo liste](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBUb2RvSXRlbSBmcm9tICcuL1RvZG9JdGVtLnZ1ZSdcbiAgX
c'est vrai, c'est parfois difficile de choisir 😄

2023-01-24 08:33 UTC, edimitchel approved these changes

2023-01-24 08:33 UTC, merged