guide/essentials/reactivity-fundamentals.md
vuejs-translations/docs-fr pull request #262
Opened 2023-01-31 20:40 UTC by tlagoda

**Actions à effectuer :**

- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres page  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #261 
      
Remarques:
J'attends vos avis pour `proxy/proxies/proxifié`, `debounced`, `unwrapped/unwrapping`!

2023-02-01 14:59 UTC, edimitchel requested changes
J'ai un doute sur "Fondamentaux sur /ou/ de la réactivité"

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Vue utilise un préfixe `$` lorsqu'il expose ses propres API natives via l'instance du composant. Il réserve également le préfixe `_` pour les propriétés internes. Il faut éviter d'utiliser des noms q
```suggestion
Vue utilise un préfixe `$` lorsqu'il expose ses propres API natives via l'instance du composant. Il réserve également le préfixe `_` pour les propriétés internes. Il faut éviter d'utiliser des noms qui commencent par l'un de ces caractères pour les propriétés `data` à sa racine.
```

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Dans Vue 3, les données sont rendues dynamiques en tirant parti des [proxys JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy). Les utilisateurs venan
```suggestion
Avec Vue 3, les données sont rendues dynamiques en tirant parti des [proxys JavaScript](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Proxy). Les utilisateurs venant de Vue 2 doivent être conscients du cas limite suivant :
```

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Lorsque vous accédez à `this.someObject` après lui avoir assigné une valeur, la valeur est un proxy réactif du `newObject` original. **Contrairement à Vue 2, le `newObject` original reste intact et n
```suggestion
Lorsque vous accédez à `this.someObject` après lui avoir assigné une valeur, la valeur est un proxy réactif de l'objet d'origine `newObject`. **Contrairement à Vue 2, le `newObject` d'origine reste intact et ne sera pas rendu réactif : assurez-vous de toujours accéder à l'état réactif comme une propriété de `this`.**
```

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Les objets réactifs sont des [proxys JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) et se comportent comme des objets classiques. La différence es
```suggestion
Les objets réactifs sont des [proxys JavaScript](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Proxy) et se comportent comme des objets classiques. La différence est que Vue est capable de traquer l'accès aux propriétés et les mutations d'un objet réactif. Si vous êtes curieux de connaître les détails, nous expliquons comment fonctionne le système de réactivité de Vue dans [Reactivity in Depth](/guide/extras/reactivity-in-depth.html) - mais nous vous recommandons de le lire après avoir terminé le guide principal.
```

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Voir aussi : [Typing Reactive](/guide/typescript/composition-api.html#typing-reactive) <sup class="vt-badge ts" />
```suggestion
See also: [Typing Reactive](/guide/typescript/composition-api.html#typing-reactive) <sup class="vt-badge ts" />
```

Touche à rien pour éviter des conflits avec l'autre PR

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Exposer manuellement l'état et les méthodes via `setup()` peut être verbeux. Heureusement, cela n'est nécessaire que lorsqu'on n'utilise pas d'étape de construction. Lorsque l'on utilise des composan
```suggestion
Exposer manuellement l'état et les méthodes via `setup()` peut être verbeux. Heureusement, cela n'est nécessaire que lorsqu'on n'utilise pas d'outil de build. Lorsque l'on utilise des composants monofichiers, nous pouvons grandement simplifier l'utilisation avec `<script setup>` :
```

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Il est également possible de créer de manière explicite des [objets réactifs superficiels](/api/reactivity-advanced.html#shallowreactive) où la réactivité n'est traquée qu'au niveau de la racine, mai
```suggestion
Il est également possible de créer de manière explicite des [objets partiellement réactifs](/api/reactivity-advanced.html#shallowreactive) où la réactivité n'est traquée qu'au niveau de la racine, mais ces objets ne sont généralement nécessaires que dans des cas d'utilisation avancée.
```
Pas certain pour le coup..

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Il est important de noter que la valeur retournée par `reactive()` est un [proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) de l'objet original, qui n'es
```suggestion
Il est important de noter que la valeur retournée par `reactive()` est un [proxy](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Proxy) de l'objet original, qui n'est pas égal à l'objet original :
```

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +1. Elle ne fonctionne que pour les types d'objets (objets, tableaux et [objets de type collection](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects#keyed_collections)
```suggestion
1. Elle ne fonctionne que pour les types d'objets (objets, tableaux et [objets de type collections](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects#collections_indexées) tels que `Map` et `Set`). Elle ne peut pas contenir les [types primitifs](https://developer.mozilla.org/fr/docs/Glossary/Primitive) tels que `string`, `number` ou `boolean`.
```

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +2. Comme le suivi de la réactivité de Vue fonctionne sur l'accès aux propriétés, nous devons toujours conserver la même référence à l'objet réactif. Cela signifie que nous ne pouvons pas facilement "
```suggestion
2. Comme le suivi de la réactivité de Vue fonctionne sur l'accès aux propriétés, nous devons toujours conserver la même référence à l'objet réactif. Cela signifie que nous ne pouvons pas facilement "remplacer" un objet réactif car la connexion de réactivité à la première référence serait perdue :
```

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Pour pallier aux limites de `reactive()`, Vue fournit également une fonction [`ref()`](/api/reactivity-core.html#ref) qui nous permet de créer des **"refs "** réactives pouvant contenir n'importe que
```suggestion
Pour pallier aux limites de `reactive()`, Vue fournit également une fonction [`ref()`](/api/reactivity-core.html#ref) qui nous permet de créer des **"refs"** réactives pouvant contenir n'importe quel type de valeur :
```

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Voir aussi : [Typing Refs](/guide/typescript/composition-api.html#typing-ref) <sup class="vt-badge ts" />
```suggestion
See also: [Typing Refs](/guide/typescript/composition-api.html#typing-ref) <sup class="vt-badge ts" />
```

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +### Déballage d'une ref dans les templates \*\* {#ref-unwrapping-in-templates}
déballage me convient, @kissu ?

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Il s'agit simplement d'une fonctionnalité pratique de l'interpolation de texte et elle est équivalente à <code v-pre>{{ objet.foo.valeur }}</code>.
```suggestion
Il s'agit simplement d'une fonctionnalité pratique de l'interpolation de texte et elle est équivalente à <code v-pre>{{ objet.foo.value }}</code>.
```

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Le déballage des ref ne se produit que lorsqu'elles sont imbriquées dans un objet réactif profond. Il ne s'applique pas lorsqu'on y accède en tant que propriété d'un [objet réactif superficiel](/api/
```suggestion
Le déballage des refs ne se produit que lorsqu'elles sont imbriquées dans un objet réactif profond. Il ne s'applique pas lorsqu'on y accède en tant que propriété d'un [objet partiellement réactif](/api/reactivity-advanced.html#shallowreactive).
```

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Dans certains cas, nous pouvons avoir besoin de créer dynamiquement une méthode, par exemple en créant un gestionnaire d'événements débridé :
```suggestion
Dans certains cas, nous pouvons avoir besoin de créer dynamiquement une méthode, par exemple en créant un gestionnaire d'événements _debounced_ :
```
debounce ça reste assez technique et le traduire serait difficile à comprendre

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +    // Débridage avec Lodash
```suggestion
    // Debounce avec Lodash
```

2023-02-01 14:59 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +## Transformation de la réactivité <sup class="vt-badge experimental" /> \*\* {#reactivity-transform}
```suggestion
## Reactivity Transform <sup class="vt-badge experimental" /> \*\* {#reactivity-transform}
```
Il faut garder ça non traduit car très identifiant comme nom

2023-02-01 20:31 UTC, tlagoda commented on src/guide/essentials/reactivity-fundamentals.md
> +## Transformation de la réactivité <sup class="vt-badge experimental" /> \*\* {#reactivity-transform}
Ok 👍

2023-02-01 20:36 UTC, tlagoda commented on src/guide/essentials/reactivity-fundamentals.md
> +Il est également possible de créer de manière explicite des [objets réactifs superficiels](/api/reactivity-advanced.html#shallowreactive) où la réactivité n'est traquée qu'au niveau de la racine, mai
J'aime bien ta proposition 👍

2023-02-02 00:25 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +### Déballage d'une ref dans les templates \*\* {#ref-unwrapping-in-templates}
ai vu l'usage de déballe ailleurs, good je pense

2023-02-02 00:25 UTC, edimitchel approved these changes

2023-02-02 00:25 UTC, merged