guide/typescript/composition-api.md
vuejs-translations/docs-fr pull request #264
Opened 2023-02-01 06:28 UTC by tlagoda

**Actions à effectuer :**

- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres page  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #263

2023-02-01 13:48 UTC, edimitchel requested changes

2023-02-01 13:48 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +See also: [Typer les refs](/guide/typescript/composition-api.html#typing-ref) <sup class="vt-badge ts" />
same

2023-02-01 13:48 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +> Cette page part du principe que vous avez déjà lu l'aperçu sur [l'utilisation de Vue avec TypeScript](./overview).
```suggestion
> Cette page part du principe que vous avez déjà pris connaissance de comment [utiliser Vue avec TypeScript](./overview).
```
à voir pour aligner l'autre page que tu avais traduit, je préfère cette tournure

2023-02-01 13:48 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +Ceci est appelé "déclaration d'exécution", parce que l'argument passé à `defineProps()` sera utilisé comme l'option `props` lord de l'exécution.
```suggestion
Ceci est appelé "déclaration l'exécution" parce que l'argument passé à `defineProps()` sera utilisé comme l'option `props` lors de l'exécution.
```

2023-02-01 13:48 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +Vous pouvez utiliser la déclaration basée sur les types OU la déclaration d'exécution, mais vous ne pouvez pas utiliser les deux en même temps.
```suggestion
Vous pouvez utiliser la déclaration basée sur les types OU la déclaration à l'exécution, mais vous ne pouvez pas utiliser les deux en même temps.
```

2023-02-01 13:48 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +Actuellement ce comportement nécessite [explicit opt-in](/guide/extras/reactivity-transform.html#explicit-opt-in).
```suggestion
Actuellement ce comportement nécessite [une activation explicite](/guide/extras/reactivity-transform.html#explicit-opt-in).
```

2023-02-01 13:48 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +Pour la déclaration au moment de l'exécution, nous pouvons utiliser le type utilitaire `PropType` :
```suggestion
Pour la déclaration à l'exécution, nous pouvons utiliser le type utilitaire `PropType` :
```

2023-02-01 13:48 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +L'option `props` est plus couramment utilisée avec l'Options API, vous trouverez donc des exemples plus détaillés dans le guide de [TypeScript avec l'Options API](/guide/typescript/options-api.html#t
```suggestion
L'option `props` est plus couramment utilisée avec l'Options API, vous trouverez donc des exemples plus détaillés dans le guide de [TypeScript avec l'Options API](/guide/typescript/options-api.html#typing-component-props). Les techniques présentées dans ces exemples s'appliquent également aux déclarations à l'exécution utilisant `defineProps()`.
```

2023-02-01 13:48 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +## Typer les emits d'un composant {#typing-component-emits}
```suggestion
## Typer les événements d'un composant {#typing-component-emits}
```

2023-02-01 13:48 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +Dans `<script setup>`, la fonction `emit` peut également être typée en utilisant la déclaration d'exécution OU la déclaration de type :
```suggestion
Dans `<script setup>`, la fonction `emit` peut également être typée en utilisant la déclaration à l'exécution OU la déclaration de type :
```

2023-02-01 13:48 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +// exécution
```suggestion
// à l'exécution
```

2023-02-01 13:48 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +  // terreur de type si un nombre n'est pas retourné
```suggestion
  // erreur de type si un nombre n'est pas retourné
```
Il a eu peur le type lol

2023-02-01 13:48 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +Provide et inject sont généralement utilisés dans des composants séparés. Pour typer correctement les valeurs injectées, Vue fournit une interface `InjectionKey`, qui est un type générique qui étend
```suggestion
Provide et Inject sont généralement utilisés dans des composants séparés. Pour typer correctement les valeurs injectées, Vue fournit une interface `InjectionKey`, qui est un type générique qui étend `Symbol`. Elle peut être utilisée pour synchroniser le type de la valeur injectée entre le fournisseur et le consommateur :
```

2023-02-01 13:48 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +## Typer les refs du template {#typing-template-refs}
```suggestion
## Typer les refs de template {#typing-template-refs}
```

2023-02-01 21:28 UTC, tlagoda commented on src/guide/typescript/composition-api.md
> +Ceci est appelé "déclaration d'exécution", parce que l'argument passé à `defineProps()` sera utilisé comme l'option `props` lord de l'exécution.
typo dans ta proposition ? `déclaration l'exécution` ?

2023-02-01 21:29 UTC, tlagoda commented on src/guide/typescript/composition-api.md
> +Ceci est appelé "déclaration d'exécution", parce que l'argument passé à `defineProps()` sera utilisé comme l'option `props` lord de l'exécution.
à l'exécution j'imagine

2023-02-01 21:31 UTC, tlagoda commented on src/guide/typescript/composition-api.md
> +  // terreur de type si un nombre n'est pas retourné
Terrifiant 🤣

2023-02-01 22:44 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +Ceci est appelé "déclaration d'exécution", parce que l'argument passé à `defineProps()` sera utilisé comme l'option `props` lord de l'exécution.
j'ai mit à jour et ai changé un peu la tournure

2023-02-01 22:45 UTC, edimitchel requested changes

2023-02-01 22:45 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +Ceci est appelé "déclaration d'exécution", parce que l'argument passé à `defineProps()` sera utilisé comme l'option `props` lord de l'exécution.
```suggestion
Ceci est appelé "déclaration d'exécution" du fait que l'argument passé à `defineProps()` sera utilisé comme l'option `props` lord de l'exécution.
```

2023-02-02 01:47 UTC, edimitchel requested changes

2023-02-02 01:47 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +C'est ce qu'on appelle la "déclaration basée sur le type". Le compilateur fera de son mieux pour déduire les options d'exécution équivalentes en fonction de l'argument de type. Dans ce cas, notre deu
```suggestion
C'est ce qu'on appelle la "déclaration basée sur le type". Le compilateur fera de son mieux pour déduire les options à l'exécution équivalentes en fonction de l'argument de type. Dans ce cas, notre deuxième exemple compile avec exactement les mêmes options à l'exécution que le premier exemple.
```

2023-02-02 01:47 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +Afin de générer le code d'exécution correct, l'argument générique pour `defineProps()` doit être l'un des suivants :
```suggestion
Afin de générer le code exécuté correct, l'argument générique pour `defineProps()` doit être l'un des suivants :
```

2023-02-02 01:47 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +Ceci sera compilé en options `default` équivalentes aux props d'exécution. De plus, `withDefaults` fournit des vérifications de type pour les valeurs par défaut, et assure que le type `props` retourn
```suggestion
Ceci sera compilé en options à l'exécution `default` équivalentes aux props. De plus, `withDefaults` fournit des vérifications de type pour les valeurs par défaut, et assure que le type `props` retourné n'a pas les options facultatives pour les propriétés qui ont des valeurs déclarées par défaut.
```

2023-02-02 01:47 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +// la valeur par défaut est compilée en option équivalente d'exécution
```suggestion
// la valeur par défaut est compilée en option à l'exécution équivalente
```

2023-02-02 17:43 UTC, tlagoda commented on src/guide/typescript/composition-api.md
> +Ceci est appelé "déclaration d'exécution", parce que l'argument passé à `defineProps()` sera utilisé comme l'option `props` lord de l'exécution.
good

2023-02-02 18:24 UTC, edimitchel approved these changes

2023-02-02 21:46 UTC, merged