guide/extras/ways-of-using-vue.md
vuejs-translations/docs-fr pull request #287
Opened 2023-02-04 21:48 UTC by Kamsou

**Actions à effectuer :**

- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres page  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #285
      
Remarques:

2023-02-04 22:45 UTC, tlagoda reviewed
Quelques points à corriger mais beau boulot!

2023-02-04 22:45 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +Nous pensons qu'il n'existe pas de solution unique pour le web. C'est pourquoi Vue est conçu pour être flexible et facilement adoptable. Selon votre cas d'utilisation, Vue peut être utilisé de différ
```suggestion
Nous pensons qu'il n'existe pas de solution unique pour le web. C'est pourquoi Vue est conçu pour être flexible et facilement adoptable. Selon votre cas d'utilisation, Vue peut être utilisé de différentes manières pour trouver l'équilibre optimal entre la complexité de la pile technique, l'expérience de développement et les performances finales.
```

2023-02-04 22:45 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +Vue peut être utilisé comme un fichier de script autonome, sans étape de construction requise! Si vous avez déjà un framework backend qui rend la plupart de l'HTML ou si votre logique frontend n'est
```suggestion
Vue peut être utilisé comme un fichier de script autonome, sans étape de build requise! Si vous avez déjà un framework backend qui rend la plupart de l'HTML ou si votre logique frontend n'est pas assez complexe pour justifier une étape de build, c'est la manière la plus facile d'intégrer Vue à votre pile technique. Vous pouvez considérer Vue comme un remplacement plus déclaratif de jQuery dans de tels cas.
```

2023-02-04 22:45 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +Vue fournit également une distribution alternative appelée [petite-vue](https://github.com/vuejs/petite-vue) qui est spécifiquement optimisée pour améliorer progressivement les HTML existants. Il a u
```suggestion
Vue fournit également une distribution alternative appelée [petite-vue](https://github.com/vuejs/petite-vue) qui est spécifiquement optimisée pour améliorer progressivement l'HTML existant. Elle a un jeu de fonctionnalités plus restreint, mais est extrêmement légère et utilise une implémentation plus efficace dans les scénarios sans étape de build.
```

2023-02-04 22:45 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +Vous pouvez utiliser Vue pour [construire des composants web standard](/guide/extras/web-components) qui peuvent être intégrés dans n'importe quelle page HTML, quelle que soit la manière dont ils son
```suggestion
Vous pouvez utiliser Vue pour [construire des composants web standards](/guide/extras/web-components) qui peuvent être intégrés dans n'importe quelle page HTML, quelle que soit la manière dont ils sont rendus. Cette option vous permet de tirer parti de Vue de manière complètement agnostique pour le consommateur: les composants web résultants peuvent être intégrés dans des applications legacy, dans du HTML statique, ou même dans des applications construites avec d'autres frameworks.
```

2023-02-04 22:45 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +## Application à une seule page (SPA) {#single-page-application-spa}
```suggestion
## Application monopage (SPA) {#single-page-application-spa}
```

On a traduit les SPA par `application monopage`. N'hésite pas à te référer au glossaire pour les termes techniques 😃 
[Glossaire](https://github.com/vuejs-translations/docs-fr/wiki/Glossaire)

2023-02-04 22:45 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +Certaines applications nécessitent une interactivité riche, une profondeur de session importante et une logique étatique non triviale sur le frontend. La meilleure manière de construire de telles app
```suggestion
Certaines applications nécessitent une interactivité riche, une profondeur de session importante et une logique d'état non triviale sur le frontend. La meilleure manière de construire de telles applications consiste à utiliser une architecture où Vue contrôle non seulement toutes les pages, mais gère également les mises à jour de données et la navigation sans avoir à recharger la page. Ce type d'application est généralement appelé une application monopage (SPA).
```

2023-02-04 22:45 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +Les SPAs côté client pur posent problème lorsque l'application est sensible au SEO et au temps d'accès au contenu. Cela est dû au fait que le navigateur recevra une page HTML largement vide et devra
```suggestion
Les SPAs côté client pures posent problème lorsque l'application est sensible au SEO et au temps d'accès au contenu. Cela est dû au fait que le navigateur recevra une page HTML largement vide et devra attendre que le JavaScript soit téléchargé avant de rendre quoi que ce soit.
```

2023-02-04 22:45 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +Vue fournit des API de première classe pour "rendre" une application Vue en chaînes HTML sur le serveur. Cela permet au serveur de renvoyer des HTML déjà rendus, permettant aux utilisateurs finaux de
```suggestion
Vue fournit des API de première classe pour "rendre" une application Vue en chaînes HTML sur le serveur. Cela permet au serveur de renvoyer du HTML déjà rendu, permettant aux utilisateurs finaux de voir immédiatement le contenu tandis que le JavaScript est en cours de téléchargement. Vue hydratera alors l'application côté client pour la rendre interactive. Cela s'appelle [Server-Side Rendering (SSR)](/guide/scaling-up/ssr) et améliore considérablement les métriques Core Web Vital telles que [Largest Contentful Paint (LCP)](https://web.dev/lcp/).
```

2023-02-04 22:45 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +Il existe deux types de SSG : une seule page et multi-page. Les deux types pré-rendent le site en HTML statique, la différence étant que :
```suggestion
Il existe deux types de SSG : monopage et multi-page. Les deux types pré-rendent le site en HTML statique, la différence étant que :
```

2023-02-04 22:45 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +- Après le chargement initial de la page, une SSG à une seule page "hydrate" la page en une SPA. Cela nécessite un payload JS plus important et un coût d'hydratation plus élevé, mais les navigations
```suggestion
- Après le chargement initial de la page, une SSG monopage "hydrate" la page en une SPA. Cela nécessite une payload JS plus importante et un coût d'hydratation plus élevé, mais les navigations ultérieures seront plus rapides, car elle n'aura qu'à mettre à jour partiellement le contenu de la page au lieu de la recharger entièrement.
```

2023-02-04 22:45 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +- Une SSG à plusieurs pages charge une nouvelle page à chaque navigation. L'avantage est qu'elle peut livrer un JS minimal - ou pas du tout s'il n'y a pas besoin d'interaction ! Certains frameworks S
```suggestion
- Une SSG à plusieurs pages charge une nouvelle page à chaque navigation. L'avantage est qu'elle peut livrer un JS minimal - ou pas du tout s'il n'y a pas besoin d'interaction ! Certains frameworks SSG à plusieurs pages, tels que [Astro](https://astro.build/) prennent également en charge une "hydratation partielle" - ce qui vous permet d'utiliser des composants Vue pour créer des "îlots" interactifs à l'intérieur de l'HTML statique.
```

2023-02-04 22:45 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +Les SSG à une seule page conviennent mieux si vous attendez une interactivité non négligeable, des sessions profondes ou des éléments / états persistants à travers les navigations. Dans le cas contra
```suggestion
Les SSG monopages conviennent mieux si vous attendez une interactivité non négligeable, des sessions profondes ou des éléments / états persistants à travers les navigations. Dans le cas contraire, une SSG à plusieurs pages serait un choix plus judicieux.
```

2023-02-04 22:45 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +L'équipe Vue maintient également un générateur de site statique appelé  [VitePress](https://vitepress.vuejs.org/), qui alimente le site web que vous êtes en train de lire en ce moment même! VitePress
```suggestion
L'équipe Vue maintient également un générateur de site statique appelé [VitePress](https://vitepress.vuejs.org/), qui alimente le site web que vous êtes en train de lire en ce moment même! VitePress prend en charge les deux types de SSG. [Nuxt](https://nuxt.com/) prend également en charge le SSG. Vous pouvez même mélanger SSR et SSG pour différentes routes dans la même application Nuxt.
```

2023-02-04 23:04 UTC, edimitchel requested changes
Très bon boulot, quelques commentaires, on peut en discuter

2023-02-05 10:32 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +Nous pensons qu'il n'existe pas de solution unique pour le web. C'est pourquoi Vue est conçu pour être flexible et facilement adoptable. Selon votre cas d'utilisation, Vue peut être utilisé de différ
@edimitchel `pile technique` ?

2023-02-05 10:33 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +## Application à une seule page (SPA) {#single-page-application-spa}
@edimitchel j'avais proposé `application monopage` étant donné que c'est précisé dans le glossaire ?

2023-02-05 11:23 UTC, Kamsou commented on src/guide/extras/ways-of-using-vue.md
> +- Après le chargement initial de la page, une SSG à une seule page "hydrate" la page en une SPA. Cela nécessite un payload JS plus important et un coût d'hydratation plus élevé, mais les navigations
@tlagoda payload c'est masculin il me semble : https://fr.wiktionary.org/wiki/payload

2023-02-05 11:24 UTC, Kamsou commented on src/guide/extras/ways-of-using-vue.md
> +Les SPAs côté client pur posent problème lorsque l'application est sensible au SEO et au temps d'accès au contenu. Cela est dû au fait que le navigateur recevra une page HTML largement vide et devra
c'est le client qui est pur ici nope ?

2023-02-05 11:35 UTC, Kamsou commented on src/guide/extras/ways-of-using-vue.md
> +Nous pensons qu'il n'existe pas de solution unique pour le web. C'est pourquoi Vue est conçu pour être flexible et facilement adoptable. Selon votre cas d'utilisation, Vue peut être utilisé de différ
Oui je suis plutôt d'accord de dire `stack`, même en français. Jamais entendu "pile" ou "pile technique" dans mes discussions techs. On part sur ça ?

2023-02-05 11:42 UTC, Kamsou commented on src/guide/extras/ways-of-using-vue.md
> +Vue fournit des API de première classe pour "rendre" une application Vue en chaînes HTML sur le serveur. Cela permet au serveur de renvoyer des HTML déjà rendus, permettant aux utilisateurs finaux de
@edimitchel Faudrait faire un choix, entre garder Server-Side Rendering ou utiliser Rendu côté serveur, non ?

2023-02-05 11:48 UTC, Kamsou commented on src/guide/extras/ways-of-using-vue.md
> +Il existe des frameworks basés sur Vue de niveau supérieur construits sur ce paradigme, tels que [Nuxt](https://nuxt.com/), qui vous permettent de développer une application fullstack à l'aide de Vue
@edimitchel Ouais t'as raison, j'ai simplifié l'ensemble déjà : 
Il y a des frameworks de haut niveau basés sur Vue, par exemple [Nuxt](https://nuxt.com/), qui permettent de développer une application avec Vue et JavaScript.

Pour `"frameworks de haut niveau"` je suis pas sûr du terme haut niveau. On peut dire simplement frameworks basés sur Vue ? ou nécessaire de dire que c'est de "haut niveau" ?

2023-02-05 11:52 UTC, Kamsou commented on .vitepress/config.ts
> +          text: "Méthodes d'utilisation de Vue",
Y'a aussi `"Façons d'utiliser Vue"`, oui c'est plus juste, c'est du language plus courant. 
"Méthodes d'utilisation" est plus technique. Je saurais pas trancher. @tlagoda une idée ?

2023-02-05 11:56 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +- Après le chargement initial de la page, une SSG à une seule page "hydrate" la page en une SPA. Cela nécessite un payload JS plus important et un coût d'hydratation plus élevé, mais les navigations
my bad ✅

2023-02-05 11:57 UTC, tlagoda commented on .vitepress/config.ts
> +          text: "Méthodes d'utilisation de Vue",
Je préfère `façons/manières` à `méthodes d'utilisation` pour ma part, ça traduit mieux le sens anglais

2023-02-05 11:57 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +Nous pensons qu'il n'existe pas de solution unique pour le web. C'est pourquoi Vue est conçu pour être flexible et facilement adoptable. Selon votre cas d'utilisation, Vue peut être utilisé de différ
allez!

2023-02-05 12:01 UTC, Kamsou commented on .vitepress/config.ts
> +          text: "Méthodes d'utilisation de Vue",
ok parfait ! Go ta propal @edimitchel !

2023-02-05 12:05 UTC, Kamsou commented on src/guide/extras/ways-of-using-vue.md
> +## Composants web intégrés {#embedded-web-components}
@edimitchel `Intégration Web Components` ?

2023-02-05 12:09 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +Vue fournit des API de première classe pour "rendre" une application Vue en chaînes HTML sur le serveur. Cela permet au serveur de renvoyer des HTML déjà rendus, permettant aux utilisateurs finaux de
Oui c'est juste bien de mettre les deux une fois je pense pour qu'on sache à quoi correspond l'acronyme SSR. Comme ça quand c'est réutilisé plus loin on sait de quoi ça parle :)

2023-02-05 12:10 UTC, tlagoda commented on src/guide/extras/ways-of-using-vue.md
> +Il existe des frameworks basés sur Vue de niveau supérieur construits sur ce paradigme, tels que [Nuxt](https://nuxt.com/), qui vous permettent de développer une application fullstack à l'aide de Vue
J'ai l'impression que quand on dit `basé sur Vue` ça traduit déjà l'idée du `higher-level`

2023-02-05 12:15 UTC, Kamsou commented on src/guide/extras/ways-of-using-vue.md
> +Vue fournit des API de première classe pour "rendre" une application Vue en chaînes HTML sur le serveur. Cela permet au serveur de renvoyer des HTML déjà rendus, permettant aux utilisateurs finaux de
ok je capte, gardons-le ici uniquement alors !

2023-02-06 04:03 UTC, edimitchel commented on src/guide/extras/ways-of-using-vue.md
> +## Composants web intégrés {#embedded-web-components}
```suggestion
## Intégration des Web Components {#embedded-web-components}
```

2023-02-06 04:05 UTC, edimitchel commented on src/guide/extras/ways-of-using-vue.md
> +Il existe des frameworks basés sur Vue de niveau supérieur construits sur ce paradigme, tels que [Nuxt](https://nuxt.com/), qui vous permettent de développer une application fullstack à l'aide de Vue
ok pour basé sur Vue

2023-02-06 04:06 UTC, edimitchel submitted a review, later dismissed
Merci !

2023-02-06 04:07 UTC, edimitchel commented on src/guide/extras/ways-of-using-vue.md
> +Il y a des frameworks de haut niveau basés sur Vue, par exemple [Nuxt](https://nuxt.com/), qui permettent de développer une application avec Vue et JavaScript.
```suggestion
Il y a des frameworks basés sur Vue, par exemple [Nuxt](https://nuxt.com/), qui permettent de développer une application avec Vue et JavaScript.
```

2023-02-06 04:08 UTC, edimitchel approved these changes

2023-02-06 04:08 UTC, merged