guide/scaling-up/ssr.md
vuejs-translations/docs-fr pull request #291
Opened 2023-02-05 13:53 UTC by Kamsou

**Actions à effectuer :**

- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres page  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #289 
      
Remarques:

2023-02-05 17:24 UTC, tlagoda reviewed
T'as pas choisi la page la plus facile 😨 
Mais beau boulot !!!

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +3. Prend en charge l'utilisation comme `import * from 'vue'` dans le navigateur en ajoutant [Import Map](https://github.com/WICG/import-maps) à la coque HTML.
```suggestion
3. Prendre en charge les cas d'usage tels que `import * from 'vue'` dans le navigateur en ajoutant [Import Map](https://github.com/WICG/import-maps) à la coque HTML.
```
Pas sûr pour coque HTML ?

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +[Essayez l'exemple complété sur StackBlitz](https://stackblitz.com/fork/vue-ssr-example?file=index.js).  Le bouton est maintenant interactif !
```suggestion
[Essayez l'exemple complété sur StackBlitz](https://stackblitz.com/fork/vue-ssr-example?file=index.js). Le bouton est maintenant interactif !
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +- Prise en charge des SFC Vue et d'autres exigences de la phase de construction. En fait, nous aurons besoin de coordonner deux builds pour la même application: un pour le client et un pour le serveu
```suggestion
- Prendre en charge les SFC Vue et d'autres exigences de l'étape de build. En fait, nous aurons besoin de coordonner deux builds pour la même application : un pour le client et un pour le serveur.
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +  Les composants Vue sont compilés différemment lorsqu'ils sont utilisés en SSR - les modèles sont compilés en concaténations de chaînes au lieu de fonctions de rendu de DOM virtuel pour un rendu plu
```suggestion
  Les composants Vue sont compilés différemment lorsqu'ils sont utilisés en SSR - les templates sont compilés en concaténations de chaînes au lieu de fonctions de rendu de DOM virtuel pour un rendu plus efficace en performance.
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +- Gestion du routage, de la récupération de données et des magasins de gestion d'état de manière universelle.
```suggestion
- Gestion du routage, de la récupération de données et des stores de gestion d'état de manière universelle.
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +[Quasar](https://quasar.dev) est une solution complète basée sur Vue qui vous permet de cibler du SPA, du SSR, de la PWA, de l'application mobile, de l'application de bureau et de l'extension de navi
```suggestion
[Quasar](https://quasar.dev) est une solution complète basée sur Vue qui vous permet de cibler du SPA, du SSR, de la PWA, de l'application mobile, de l'application de bureau et de l'extension de navigateur en utilisant une seule base de code. Elle gère non seulement la mise en place du build, mais fournit également une collection complète de composants d'interface utilisateur conformes à Material Design.
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +Vite fournit [un support intégré pour le rendu côté serveur de Vue](https://vitejs.dev/guide/ssr.html), mais il est intentionnellement de niveau bas. Si vous souhaitez aller directement avec Vite, co
```suggestion
Vite fournit [un support intégré pour le rendu côté serveur de Vue](https://vitejs.dev/guide/ssr.html), mais il est intentionnellement de bas niveau. Si vous souhaitez utiliser directement Vite, consultez [vite-plugin-ssr](https://vite-plugin-ssr.com/), un plugin communautaire qui fait abstraction de nombreux détails complexes pour vous.
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +Vous pouvez également trouver un exemple de projet Vue + Vite SSR en utilisant une configuration manuelle ici, qui peut servir de base pour la construction. Notez que ceci n'est recommandé que si vou
```suggestion
Vous pouvez également trouver un exemple de projet Vue + Vite SSR en utilisant une configuration manuelle ici, qui peut servir de base pour le build. Notez que ceci n'est recommandé que si vous avez de l'expérience avec SSR / outils de build et que vous souhaitez avoir un contrôle complet sur l'architecture de haut niveau.
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +Indépendamment de votre configuration de construction ou de votre choix de framework de haut niveau, il existe des principes qui s'appliquent à toutes les applications Vue SSR.
```suggestion
Indépendamment de votre configuration de build ou de votre choix de framework de haut niveau, il existe des principes qui s'appliquent à toutes les applications Vue SSR.
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +Pendant le SSR, chaque URL de demande correspond à un état souhaité de notre application. Il n'y a pas d'interaction utilisateur et aucune mise à jour DOM, donc la réactivité n'est pas nécessaire sur
```suggestion
Pendant le SSR, chaque URL requêtée correspond à un état souhaité de notre application. Il n'y a pas d'interaction utilisateur et aucune mise à jour du DOM, donc la réactivité n'est pas nécessaire sur le serveur. Par défaut, la réactivité est désactivée pendant le SSR pour une meilleure performance.
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +Depuis qu'il n'y a plus de mises à jour dynamiques, les hooks de cycle de vie tels que <span class="options-api">`mounted`</span><span class="composition-api">`onMounted`</span> ou <span class="optio
```suggestion
Depuis qu'il n'y a plus de mises à jour dynamiques, les hooks de cycle de vie tels que <span class="options-api">`mounted`</span><span class="composition-api">`onMounted`</span> ou <span class="options-api">`updated`</span><span class="composition-api">`onUpdated`</span> ne seront **PAS** appelés pendant le SSR et ne seront exécutés que côté client.<span class="options-api"> Les seuls hooks qui sont appelés pendant le SSR sont `beforeCreate` et `created`</span>
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +Vous devriez éviter le code qui produit des effets secondaires qui nécessitent un nettoyage dans <span class="options-api">`beforeCreate` et `created`</span><span class="composition-api">`setup()` ou
```suggestion
Vous devriez éviter le code qui produit des effets secondaires qui nécessitent un nettoyage dans <span class="options-api">`beforeCreate` et `created`</span><span class="composition-api">`setup()` ou dans la portée de `<script setup>`</span>. Un exemple d'effets secondaires est la configuration de minuteries avec `setInterval`. Dans le code exécuté côté client, nous pouvons configurer une minuterie et la démonter dans <span class="options-api">`beforeUnmount`</span><span class="composition-api">`onBeforeUnmount`</span> ou <span class="options-api">`unmounted`</span><span class="composition-api">`onUnmounted`</span>. Cependant, étant donné que les hooks de démontage ne seront jamais appelés pendant le SSR, les minuteries resteront à jamais. Pour éviter cela, déplacez votre code d'effets secondaires dans <span class="options-api">`mounted`</span><span class="composition-api">`onMounted`</span>.
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +###  Accès aux API spécifiques à la plateforme {#access-to-platform-specific-apis}
```suggestion
### Accès aux API spécifiques à la plateforme {#access-to-platform-specific-apis}
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
>  Universal code cannot assume access to platform-specific APIs, so if your code directly uses browser-only globals like `window` or `document`, they will throw errors when executed in Node.js, and vic
Tu as laissé les blocs non traduits ici

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +Pour les tâches partagées entre le serveur et le client mais avec des API de plateforme différentes, il est recommandé de wraper les implémentations spécifiques à la plateforme dans une API universel
```suggestion
Pour les tâches partagées entre le serveur et le client mais avec des API de plateforme différentes, il est recommandé d'envelopper les implémentations spécifiques à la plateforme dans une API universelle ou d'utiliser des bibliothèques qui le font pour vous. Par exemple, vous pouvez utiliser [`node-fetch`](https://github.com/node-fetch/node-fetch) pour utiliser la même API fetch sur le serveur et le client.
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +Notez que si une bibliothèque tiers n'est pas écrite en vue d'une utilisation universelle, il peut être difficile de l'intégrer dans une application rendue côté serveur. Vous _pourriez_ être en mesur
```suggestion
Notez que si une bibliothèque tiers n'est pas écrite en vue d'une utilisation universelle, il peut être difficile de l'intégrer dans une application rendue côté serveur. Vous _pourriez_ être en mesure de la faire fonctionner en simulant certaines des globales, mais ce serait un bricolage et pourrait interférer avec le code de détection de l'environnement d'autres bibliothèques.
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +### Pollution d'État à demande croisée {#cross-request-state-pollution}
```suggestion
### Pollution d'état par demandes croisées {#cross-request-state-pollution}
```

@edimitchel une idée ? 🤣

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +Le modèle déclare un état partagé dans le scope d'un module JavaScript. Cela les rend **singletons** - c'est-à-dire qu'il n'y a qu'une seule instance de l'objet réactif tout au long de la vie de notr
```suggestion
Le modèle déclare un état partagé dans la portée d'un module JavaScript. Cela les rend **singletons** - c'est-à-dire qu'il n'y a qu'une seule instance de l'objet réactif tout au long de la vie de notre application. Cela fonctionne comme prévu dans une application Vue côté client, car les modules de notre application sont initialisés à nouveau pour chaque visite de page navigateur.
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +Cependant, dans un contexte SSR, les modules d'application sont généralement initialisés une seule fois sur le serveur, lorsque le serveur démarre. Les mêmes instances de modules seront réutilisées à
```suggestion
Cependant, dans un contexte SSR, les modules d'application sont généralement initialisés une seule fois sur le serveur, lorsque le serveur démarre. Les mêmes instances de modules seront réutilisées à travers plusieurs demandes de serveur, et donc nos objets d'état singletons. Si nous modifions l'état partagé singleton avec des données spécifiques à un utilisateur, cela peut être accidentellement fuir vers une demande provenant d'un autre utilisateur. Nous appelons cela une **pollution d'état cross-request.**
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +La solution recommandée est de créer une nouvelle instance de l'application entière - y compris le routeur et les stores globaux - à chaque demande. Ensuite, au lieu de l'importer directement dans no
Pas sûr pour la trad du titre du lien, est-ce qu'on traduit `provide` ?

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +  // créer une nouvelle instance de store par requête
```suggestion
  // crée une nouvelle instance de store par requête
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +  // fournir un store au niveau de l'application
```suggestion
  // fournit un store au niveau de l'application
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +1. Le modèle contient une structure de nesting HTML non valide, et le HTML rendu a été "corrigé" par le comportement de parsing HTML natif du navigateur. Par exemple, une erreur courante est que [`<d
```suggestion
1. Le modèle contient une structure HTML imbriqué non valide, et le HTML rendu a été "corrigé" par le comportement d'analyse syntaxique du HTML natif du navigateur. Par exemple, une erreur courante est que [`<div>` ne peut pas être placée à l'intérieur de `<p>`](https://stackoverflow.com/questions/8397852/why-cant-the-p-tag-contain-a-div-tag-inside-it):
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +   Si nous produisons ceci dans notre HTML rendu par le serveur, le navigateur terminera le premier `<p>` lorsque `<div>` sera rencontré et le parser en la structure de DOM suivante :
```suggestion
   Si nous produisons ceci dans notre HTML rendu par le serveur, le navigateur terminera le premier `<p>` lorsque `<div>` sera rencontré et l'analysera en la structure de DOM suivante :
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +   Utilisez une bibliothèque de générateur de nombres aléatoires qui prend en charge la génération avec des seeds, et garantissez que l'exécution du serveur et l'exécution du client utilisent la même
```suggestion
   Utilisez une bibliothèque de générateur de nombres aléatoires qui prend en charge la génération avec des seeds, et assurez-vous que l'exécution du serveur et l'exécution du client utilisent la même seed (par exemple en incluant la seed dans l'état sérialisé et en la récupérant sur le client).
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +3. Le serveur et le client se trouvent dans des fuseaux horaires différents. Parfois, nous pouvons vouloir convertir un horodatage en temps local de l'utilisateur. Cependant, le fuseau horaire lors d
```suggestion
3. Le serveur et le client se trouvent dans des fuseaux horaires différents. Parfois, nous pouvons vouloir convertir un timestamp en temps local de l'utilisateur. Cependant, le fuseau horaire lors de l'exécution du serveur et le fuseau horaire lors de l'exécution du client ne sont pas toujours les mêmes, et nous ne pouvons pas toujours connaître de manière fiable le fuseau horaire de l'utilisateur lors de l'exécution du serveur. Dans de tels cas, la conversion de l'heure locale doit également être effectuée en tant qu'opération uniquement côté client.
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +Vous devez injecter le markup de téléportation dans l'emplacement correct dans votre HTML de page finale, similaire à comment vous devez injecter le markup principal de l'application.
```suggestion
Vous devez injecter le markup de téléportation dans l'emplacement correct dans votre HTML de page finale, tout comme vous devez injecter le markup principal de l'application.
```

2023-02-05 17:24 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +Évitez de cibler `body` lorsque vous utilisez Teleports et SSR ensemble - généralement, `<body>` contiendra d'autres contenus rendus sur le serveur ce qui rend impossible pour Teleports de déterminer
```suggestion
Évitez de cibler `body` lorsque vous utilisez Teleports et le SSR ensemble - généralement, `<body>` contiendra d'autres contenus rendus sur le serveur ce qui rend impossible pour Teleports de déterminer le bon emplacement de départ pour l'hydratation.
```

2023-02-05 18:18 UTC, Kamsou commented on src/guide/scaling-up/ssr.md
> +- **Meilleur référencement** : les crawlers de moteur de recherche verront directement la page entièrement rendue.
Je me suis posé la question aussi o.o @edimitchel un avis ?

2023-02-05 18:27 UTC, Kamsou commented on src/guide/scaling-up/ssr.md
> +Pour rendre l'application côté client interactive, Vue doit effectuer l'étape de **hydratation**. Pendant l'hydratation, elle crée la même application Vue qui a été exécutée sur le serveur, associe c
@tlagoda j'ai mis au féminin car on parle de "l'application Vue" non?

2023-02-05 18:31 UTC, Kamsou commented on src/guide/scaling-up/ssr.md
> +3. Prend en charge l'utilisation comme `import * from 'vue'` dans le navigateur en ajoutant [Import Map](https://github.com/WICG/import-maps) à la coque HTML.
@tlagoda Oui bizarre qu'il l'ait nommé comme ça. Jamais vu. J'aurais dis au fichier ou à l'interface HTML ?

2023-02-05 18:37 UTC, Kamsou commented on src/guide/scaling-up/ssr.md
> +Vous devriez éviter le code qui produit des effets secondaires qui nécessitent un nettoyage dans <span class="options-api">`beforeCreate` et `created`</span><span class="composition-api">`setup()` ou
@tlagoda Dans le glossaire, j'ai cru voir qu'on gardait scope ?

2023-02-05 18:39 UTC, Kamsou commented on src/guide/scaling-up/ssr.md
> +Le modèle déclare un état partagé dans le scope d'un module JavaScript. Cela les rend **singletons** - c'est-à-dire qu'il n'y a qu'une seule instance de l'objet réactif tout au long de la vie de notr
@tlagoda Dans le glossaire, j'ai cru voir qu'on gardait scope ?

2023-02-05 18:45 UTC, Kamsou commented on src/guide/scaling-up/ssr.md
> +La solution recommandée est de créer une nouvelle instance de l'application entière - y compris le routeur et les stores globaux - à chaque demande. Ensuite, au lieu de l'importer directement dans no
@tlagoda Je viens de voir sur la page Provide / Inject, c'est traduit : Provide au niveau de l'application ! j'avais pas vu, je fixe

2023-02-05 20:02 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +Pour rendre l'application côté client interactive, Vue doit effectuer l'étape de **hydratation**. Pendant l'hydratation, elle crée la même application Vue qui a été exécutée sur le serveur, associe c
Pour moi le sujet c'est Vue nop ?

2023-02-05 20:03 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +Vous devriez éviter le code qui produit des effets secondaires qui nécessitent un nettoyage dans <span class="options-api">`beforeCreate` et `created`</span><span class="composition-api">`setup()` ou
Bizarrerie 🤣 c'est bien scope dans le glossaire mais c'est traduit portée un peu partout!

2023-02-05 20:04 UTC, tlagoda commented on src/guide/scaling-up/ssr.md
> +3. Prend en charge l'utilisation comme `import * from 'vue'` dans le navigateur en ajoutant [Import Map](https://github.com/WICG/import-maps) à la coque HTML.
fichier me paraît pas mal, voir html tout court

2023-02-06 04:45 UTC, edimitchel commented on src/guide/scaling-up/ssr.md
> +- **Meilleur référencement** : les crawlers de moteur de recherche verront directement la page entièrement rendue.
plutôt pour la traduction vu la traduction que tu proposes @tlagoda !

2023-02-06 04:46 UTC, edimitchel commented on src/guide/scaling-up/ssr.md
> +Pour rendre l'application côté client interactive, Vue doit effectuer l'étape de **hydratation**. Pendant l'hydratation, elle crée la même application Vue qui a été exécutée sur le serveur, associe c
Je suis de l'avis de @tlagoda :)

2023-02-06 04:48 UTC, edimitchel commented on src/guide/scaling-up/ssr.md
> +Le modèle déclare un état partagé dans le scope d'un module JavaScript. Cela les rend **singletons** - c'est-à-dire qu'il n'y a qu'une seule instance de l'objet réactif tout au long de la vie de notr
Effectivement, mais en vrai, la question de se pose, portée me semble assez limpide comme traduction de scope.
On peut peut-être remettre en question ce choix.

2023-02-06 04:50 UTC, edimitchel commented
@Kamsou avant que ne fasse la review, merci de regarder où tu fait des erreurs sur le nombre de lignes ajoutées/supprimées, il doit y avoir des sauts de lignes superflues ou en moins..
Rajoute moi aux reviewers quand tu auras les lignes ajoutées/supprimées équilibrées

2023-02-06 21:49 UTC, Kamsou commented on src/guide/scaling-up/ssr.md
> +Le modèle déclare un état partagé dans le scope d'un module JavaScript. Cela les rend **singletons** - c'est-à-dire qu'il n'y a qu'une seule instance de l'objet réactif tout au long de la vie de notr
Je la trouve bien cette traduction, allons y sur ça

2023-02-06 22:23 UTC, edimitchel requested changes

2023-02-06 22:23 UTC, edimitchel commented on src/guide/scaling-up/ssr.md
> +Pour rendre l'application côté client interactive, Vue doit effectuer l'étape de **hydratation**. Pendant l'hydratation, elle crée la même application Vue qui a été exécutée sur le serveur, associe c
```suggestion
Pour rendre l'application côté client interactive, Vue doit effectuer l'étape de **hydratation**. Pendant l'hydratation, il crée la même application Vue qui a été exécutée sur le serveur, associe chaque composant aux nœuds DOM qu'il doit contrôler et attache les écouteurs d'événements du DOM.
```

2023-02-06 22:23 UTC, edimitchel commented on src/guide/scaling-up/ssr.md
> +Cela devrait imprimer ce qui suit sur la ligne de commande :
```suggestion
Cela devrait retourner :
```

2023-02-06 22:23 UTC, edimitchel commented on src/guide/scaling-up/ssr.md
> +// hydratation au lieu de monter de nouveaux noeuds du DOM.
```suggestion
// hydratation au lieu de monter de nouveaux nœuds du DOM.
```

2023-02-06 22:23 UTC, edimitchel commented on src/guide/scaling-up/ssr.md
> +- Dans le gestionnaire de requête du serveur, afficher le HTML avec les liens de ressources client corrects et les astuces de ressources optimales. Il peut également être nécessaire de basculer entre
```suggestion
- Dans le gestionnaire de requête du serveur, afficher le HTML avec les liens corrects des ressources clientes et autres ressources optimisées. Il peut également être nécessaire de basculer entre le mode SSR et SSG, ou même de mélanger les deux dans la même application.
```

2023-02-06 22:23 UTC, edimitchel commented on src/guide/scaling-up/ssr.md
> +Vite fournit [un support intégré pour le rendu côté serveur de Vue](https://vitejs.dev/guide/ssr.html), mais il est intentionnellement de bas niveau. Si vous souhaitez utiliser directement avec Vite,
```suggestion
Vite fournit [un support natif pour le rendu côté serveur de Vue](https://vitejs.dev/guide/ssr.html), mais il est intentionnellement de bas niveau. Si vous souhaitez utiliser directement avec Vite, consultez [vite-plugin-ssr](https://vite-plugin-ssr.com/), un plugin communautaire qui fait abstraction de nombreux détails complexes pour vous.
```

2023-02-06 22:23 UTC, edimitchel commented on src/guide/scaling-up/ssr.md
> +Depuis qu'il n'y a plus de mises à jour dynamiques, les hooks de cycle de vie tels que <span class="options-api">`mounted`</span><span class="composition-api">`onMounted`</span> ou <span class="optio
```suggestion
Vu qu'il n'y a pas de mises à jour dynamiques, les hooks de cycle de vie tels que <span class="options-api">`mounted`</span><span class="composition-api">`onMounted`</span> ou <span class="options-api">`updated`</span><span class="composition-api">`onUpdated`</span> ne seront **PAS** appelés pendant le SSR et ne seront exécutés que côté client.<span class="options-api"> Les seuls hooks qui sont appelés pendant le SSR sont `beforeCreate` et `created`</span>
```

2023-02-06 22:23 UTC, edimitchel commented on src/guide/scaling-up/ssr.md
> +### Pollution d'État à demande croisée {#cross-request-state-pollution}
ta proposition me convient @tlagoda !

2023-02-06 22:23 UTC, edimitchel commented on src/guide/scaling-up/ssr.md
> +Cependant, dans un contexte SSR, les modules d'application sont généralement initialisés une seule fois sur le serveur, lorsque le serveur démarre. Les mêmes instances de modules seront réutilisées à
```suggestion
Cependant, dans un contexte SSR, les modules d'application sont généralement initialisés une seule fois sur le serveur, lorsque le serveur démarre. Les mêmes instances de modules seront réutilisées à travers plusieurs demandes de serveur, et donc nos objets d'état singletons. Si nous modifions l'état partagé singleton avec des données spécifiques à un utilisateur, cela peut être accidentellement fuir vers une demande provenant d'un autre utilisateur. Nous appelons cela une **pollution d'état par demandes croisées.**
```

2023-02-06 22:23 UTC, edimitchel commented on src/guide/scaling-up/ssr.md
> +  // fournis un store au niveau de l'application
```suggestion
  // fournit un store au niveau de l'application
```

2023-02-06 22:23 UTC, edimitchel commented on src/guide/scaling-up/ssr.md
> +// appelé sur chaque demande
```suggestion
// appelée sur chaque demande
```

2023-02-07 20:32 UTC, edimitchel requested changes

2023-02-07 20:32 UTC, edimitchel commented on src/guide/scaling-up/ssr.md
> +[Nuxt](https://nuxt.com/) Nuxt est une plateforme Vue simplifiée pour développer des applications universelles et peut être utilisée comme générateur de site statique. Nous vous recommandons fortemen
```suggestion
[Nuxt](https://nuxt.com/) est une plateforme Vue simplifiée pour développer des applications universelles et peut être utilisée comme générateur de site statique. Nous vous recommandons fortement de l'essayer.
```

2023-02-07 20:32 UTC, edimitchel commented on src/guide/scaling-up/ssr.md
> +## Écrire un code convivial pour du SSR {#writing-ssr-friendly-code}
```suggestion
## Écrire du code SSR propre {#writing-ssr-friendly-code}
```
Convivial me semble pas correct ici

2023-02-07 22:10 UTC, edimitchel approved these changes

2023-02-07 22:11 UTC, merged