api/built-in-special-elements.md
vuejs-translations/docs-fr pull request #299
Opened 2023-02-06 21:50 UTC by tlagoda

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #298

2023-02-06 22:34 UTC, edimitchel requested changes

2023-02-06 22:34 UTC, edimitchel commented on src/api/built-in-special-attributes.md
>  - **See also:**
```suggestion
- **Voir aussi :**
```

2023-02-06 22:34 UTC, edimitchel commented on src/api/built-in-special-elements.md
> +`<component>`, `<slot>` et `<template>` sont des fonctionnalités semblables aux composants et font partie de la syntaxe des templates. Ce ne sont pas de véritables composants et ils sont supprimés lo
```suggestion
`<component>`, `<slot>` et `<template>` sont des fonctionnalités semblables aux composants et font partie de la syntaxe des templates. Ce ne sont pas de véritables composants et ils sont supprimés lors de la compilation des templates. En tant que tels, ils sont conventionnellement écrits en minuscules dans les templates.
```

2023-02-06 22:34 UTC, edimitchel commented on src/api/built-in-special-elements.md
> +- **Voir aussi :** [Composants Dynamiques](/guide/essentials/component-basics.html#dynamic-components)
```suggestion
- **Voir aussi :** [Composants dynamiques](/guide/essentials/component-basics.html#dynamic-components)
```

2023-02-06 22:34 UTC, edimitchel commented on src/api/built-in-special-elements.md
> +Indique la place content le contenu d'un slot dans les templates.
```suggestion
Indique l'emplacement du contenu d'un slot dans les templates.
```

2023-02-06 22:34 UTC, edimitchel commented on src/api/built-in-special-elements.md
> +  Un `<template>` avec un `v-for` peut aussi avoir un attribut [`key`] (/api/built-in-special-attributes.html#key). Tous les autres attributs et directives seront rejetés, car ils n'ont pas de sens s
```suggestion
  Un `<template>` avec un `v-for` peut aussi avoir un attribut [`key`](/api/built-in-special-attributes.html#key). Tous les autres attributs et directives seront rejetés, car ils n'ont pas de sens sans l'élément correspondant.
```

2023-02-07 21:49 UTC, tlagoda commented on src/api/built-in-special-attributes.md
>  - **See also:**
@edimitchel j'ai traduit dans ma PR du fichier concerné, pas besoin de traduire ici ?

2023-02-07 22:02 UTC, edimitchel commented on src/api/built-in-special-attributes.md
>  - **See also:**
effectivement :)

2023-02-07 22:03 UTC, edimitchel approved these changes

2023-02-07 22:03 UTC, merged