api/sfc-spec.md
vuejs-translations/docs-fr pull request #305
Opened 2023-02-09 19:52 UTC by tlagoda

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #304

2023-02-10 11:42 UTC, edimitchel requested changes

2023-02-10 11:42 UTC, edimitchel commented on src/api/sfc-spec.md
> +- formatage des avertissements de développement
```suggestion
- Formatage des avertissements de développement
```

2023-02-10 11:42 UTC, edimitchel commented on src/api/sfc-spec.md
> +`lang` peut être appliqué à n'importe quel bloc - par exemple, nous pouvons utiliser `<style>` avec [Sass] (https://sass-lang.com/) et `<template>` avec [Pug] (https://pugjs.org/api/getting-started.h
```suggestion
`lang` peut être appliqué à n'importe quel bloc - par exemple, nous pouvons utiliser `<style>` avec [Sass](https://sass-lang.com/) et `<template>` avec [Pug](https://pugjs.org/api/getting-started.html) :
```

2023-02-10 17:21 UTC, tlagoda commented on src/api/sfc-spec.md
> +- formatage des avertissements de développement
oups!

2023-02-12 21:45 UTC, edimitchel approved these changes

2023-02-12 21:45 UTC, merged