guide/best-practices/security.md
vuejs-translations/docs-fr pull request #307
Opened 2023-02-09 21:18 UTC by tlagoda

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #306 
      
Remarques: On traduit le nom des attaques ou pas ?

2023-02-10 11:27 UTC, edimitchel requested changes

2023-02-10 11:27 UTC, edimitchel commented on src/guide/best-practices/security.md
> +Outre les recommandations formulées ci-dessus concernant les [dangers potentiels] (#potential-dangers), nous vous recommandons également de vous familiariser avec ces ressources :
```suggestion
Outre les recommandations formulées ci-dessus concernant les [dangers potentiels](#potential-dangers), nous vous recommandons également de vous familiariser avec ces ressources :
```
Attention, je vois souvent cette erreur

2023-02-10 17:24 UTC, tlagoda commented on src/guide/best-practices/security.md
> +Outre les recommandations formulées ci-dessus concernant les [dangers potentiels] (#potential-dangers), nous vous recommandons également de vous familiariser avec ces ressources :
sorry!

2023-02-12 21:44 UTC, edimitchel approved these changes

2023-02-12 21:44 UTC, merged