guide/best-practices/performance.md
vuejs-translations/docs-fr pull request #309
Opened 2023-02-10 23:03 UTC by tlagoda

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #308 
      
Remarques: pas mal de termes techniques anglais que j'ai pas traduit, j'attends vos retours!

2023-02-12 22:24 UTC, edimitchel requested changes

2023-02-12 22:24 UTC, edimitchel commented on src/guide/best-practices/performance.md
> +Il existe de nombreux aspects indépendants du framework pour optimiser les performances de chargement des pages - consultez [ce guide web.dev](https://web.dev/fast/) pour un tour d'horizon complet. I
```suggestion
Il existe de nombreux aspects indépendants du framework pour optimiser les performances de chargement des pages - consultez [le guide web.dev](https://web.dev/fast/) pour un tour d'horizon complet. Ici, nous nous concentrerons principalement sur les techniques spécifiques à Vue.
```

2023-02-12 22:24 UTC, edimitchel commented on src/guide/best-practices/performance.md
> +Si votre application est sensible aux performances de chargement des pages, évitez de la rendre en tant que SPA entièrement côté client. Vous voulez que votre serveur envoie directement le HTML conte
```suggestion
Si votre application est sensible aux performances de chargement des pages, évitez de la rendre en tant que SPA entièrement côté client. Vous voulez que votre serveur envoie directement le HTML contenant le contenu que les utilisateurs veulent voir. Le rendu côté purement client souffre d'un temps d'accès au contenu plus lent. Ceci peut être atténué avec [le rendu côté serveur (SSR)](/guide/extras/ways-of-using-vue.html#fullstack-ssr) ou [la génération de site statique (SSG)](/guide/extras/ways-of-using-vue.html#jamstack-ssg). Consultez le [Guide SSR](/guide/scaling-up/ssr.html) pour en savoir plus sur l'exécution SSR avec Vue. Si votre application n'a pas besoin d'une grande interactivité, vous pouvez également utiliser un serveur backend traditionnel pour rendre le HTML et le rendre interactif avec Vue côté client.
```

2023-02-12 22:24 UTC, edimitchel commented on src/guide/best-practices/performance.md
> +### Taille des paquets et suppression des arbres {#bundle-size-and-tree-shaking}
```suggestion
### Taille des paquets et _Tree-shaking_ {#bundle-size-and-tree-shaking}
```
On va se prendre les écolos si on laisse ça xD

2023-02-12 22:24 UTC, edimitchel commented on src/guide/best-practices/performance.md
> +  - De nombreuses API de Vue peuvent être ["retirées de l'arbre"](https://developer.mozilla.org/fr/docs/Glossary/Tree_shaking) si elles sont groupées via un outil de construction moderne. Par exemple
```suggestion
  - De nombreuses API de Vue peuvent être ["retirées de l'arbre"](https://developer.mozilla.org/fr/docs/Glossary/Tree_shaking) si elles sont groupées via un outil de construction moderne. Par exemple, si vous n'utilisez pas le composant natif `<Transition>`, il ne sera pas inclus dans le paquet de production final. Le _tree-shaking_ peut également supprimer d'autres modules inutilisés dans votre code source.
```

2023-02-12 22:24 UTC, edimitchel commented on src/guide/best-practices/performance.md
> +  - Si vous utilisez un outil de build, préférez les dépendances qui offrent des formats de modules ES et qui sont compatibles avec la suppression des arbres. Par exemple, préférez `lodash-es` à `lod
```suggestion
  - Si vous utilisez un outil de build, préférez les dépendances qui offrent des formats de modules ES et qui sont compatibles au _tree-shaking._ Par exemple, préférez `lodash-es` à `lodash`.
```

2023-02-12 22:24 UTC, edimitchel commented on src/guide/best-practices/performance.md
> +- Si vous utilisez Vue principalement pour l'amélioration progressive et préférez éviter un outil de build, envisagez d'utiliser [petite-vue](https://github.com/vuejs/petite-vue) (seulement **6kb**)
```suggestion
- Si vous utilisez Vue principalement pour une intégration progressive et préférez éviter un outil de build, envisagez plutôt d'utiliser [petite-vue](https://github.com/vuejs/petite-vue) (seulement **6kb**).
```

2023-02-12 22:24 UTC, edimitchel commented on src/guide/best-practices/performance.md
> +Le fractionnement du code consiste pour un outil de build à diviser le paquet d'applications en plusieurs petits morceaux, qui peuvent ensuite être chargés à la demande ou en parallèle. Avec un fract
```suggestion
Le fractionnement du code consiste pour un outil de build à diviser le paquet d'applications en plusieurs petits morceaux, qui peuvent ensuite être chargés à la demande ou en parallèle. Avec un fractionnement de code approprié, les fonctionnalités requises au chargement de la page peuvent être téléchargées immédiatement, les morceaux supplémentaires n'étant chargés à la volée qu'en cas de besoin, ce qui améliore les performances.
```
Lazy se traduit à la volée d'après le glossaire.. je sais qu'il y a plusieurs cas où paresseux a été utilisé.. faudrait les remplacer (tu peux faire une PR à part?)

2023-02-12 22:24 UTC, edimitchel commented on src/guide/best-practices/performance.md
> +Le chargement paresseux est optimal pour les fonctionnalités qui ne sont pas immédiatement nécessaires après le chargement initial de la page. Dans les applications Vue, il peut être utilisé en combi
```suggestion
Le chargement à la volée est optimal pour les fonctionnalités qui ne sont pas immédiatement nécessaires après le chargement initial de la page. Dans les applications Vue, il peut être utilisé en combinaison avec la fonctionnalité [composants asynchrones](/guide/components/async.html) de Vue pour créer des morceaux fractionnés pour les arbres de composants :
```

2023-02-12 22:24 UTC, edimitchel commented on src/guide/best-practices/performance.md
> +Pour les applications utilisant Vue Router, il est fortement recommandé d'utiliser le chargement paresseux pour les composants de route. Vue Router a un support explicite pour le chargement paresseux
```suggestion
Pour les applications utilisant Vue Router, il est fortement recommandé d'utiliser le chargement à la volée pour les composants de route. Vue Router a un support explicite pour le chargement à la volée, séparé de `defineAsyncComponent`. Voir [le chargement à la volée des routes](https://router.vuejs.org/guide/advanced/lazy-loading.html) pour plus de détails.
```

2023-02-12 22:24 UTC, edimitchel commented on src/guide/best-practices/performance.md
> +Dans le composant `<ListItem>`, il utilise ses props `id` et `activeId` pour déterminer s'il s'agit de l'élément actif. Bien que cela fonctionne, le problème est que chaque fois que `activeId` change
```suggestion
Dans le composant `<ListItem>`, les props `id` et `activeId` sont utilisées pour déterminer s'il s'agit de l'élément actif. Bien que cela fonctionne, le problème est que chaque fois que `activeId` change, **l'entièreté** des `<ListItem>` inclus dans la liste doit être mis à jour !
```

2023-02-12 22:24 UTC, edimitchel commented on src/guide/best-practices/performance.md
> +Le système de réactivité de Vue est profond par défaut. Bien que cela rende la gestion de l'état intuitive, cela crée un certain niveau de surcharge lorsque la taille des données est importante, car
```suggestion
Le système de réactivité de Vue est profond par défaut. Bien que cela rende la gestion de l'état intuitive, cela crée un certain niveau de surcharge lorsque la taille des données est importante, car chaque accès à une propriété déclenche un mécanisme des proxys qui effectuent un suivi des dépendances. Ce problème est généralement perceptible lorsque l'on traite de grands tableaux d'objets profondément imbriqués, où un seul rendu doit accéder à plus de 100 000 propriétés, et ne devrait donc affecter que des cas d'utilisation très spécifiques.
```

2023-02-13 18:33 UTC, tlagoda commented on src/guide/best-practices/performance.md
> +### Taille des paquets et suppression des arbres {#bundle-size-and-tree-shaking}
J'avoue j'y ai pas pensé 😆

2023-02-13 18:35 UTC, tlagoda commented on src/guide/best-practices/performance.md
> +Le fractionnement du code consiste pour un outil de build à diviser le paquet d'applications en plusieurs petits morceaux, qui peuvent ensuite être chargés à la demande ou en parallèle. Avec un fract
yes!

2023-02-14 09:44 UTC, edimitchel approved these changes

2023-02-14 09:44 UTC, merged