api/sfc-script-setup.md
vuejs-translations/docs-fr pull request #311
Opened 2023-02-11 19:57 UTC by tlagoda

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #310

2023-02-12 22:45 UTC, edimitchel requested changes

2023-02-12 22:45 UTC, edimitchel commented on src/api/sfc-script-setup.md
> +`<script setup>` est un sucre syntaxique de compilation pour l'utilisation de la Composition API dans les composants monopages (SFC). C'est la syntaxe recommandée si vous utilisez à la fois les SFC e
```suggestion
`<script setup>` est un sucre syntaxique de compilation pour l'utilisation de la Composition API dans les composants monofichiers (SFC). C'est la syntaxe recommandée si vous utilisez à la fois les SFC et la Composition API. Elle offre un certain nombre d'avantages par rapport à la syntaxe classique `<script>` :
```

2023-02-12 22:45 UTC, edimitchel commented on src/api/sfc-script-setup.md
> +Lorsque vous utilisez `<script setup>`, toutes les liaisons de haut niveau (y compris les variables, les déclarations de fonctions et les imports) déclarées dans `<script setup>` sont directement uti
```suggestion
Lorsque vous utilisez `<script setup>`, toutes liaisons de haut niveau (y compris les variables, les déclarations de fonctions et les imports) déclarées dans `<script setup>` sont directement utilisables dans le template :
```

2023-02-12 22:45 UTC, edimitchel commented on src/api/sfc-script-setup.md
> +### Composants d'un espace de nom {#namespaced-components}
```suggestion
### Composants sous espace de nom {#namespaced-components}
```

2023-02-12 22:45 UTC, edimitchel commented on src/api/sfc-script-setup.md
> +Les composants utilisant `<script setup>` sont **fermés par défaut** - c'est à dire que l'instance publique du composant, qui est récupérée via les refs du template ou les chaînes de caractères `$par
```suggestion
Les composants utilisant `<script setup>` sont **fermés par défaut** - c'est à dire que l'instance publique du composant, qui est récupérée via les refs du template ou via `$parent`, n'exposera **aucune** des liaisons déclarées dans `<script setup>`.
```

2023-02-12 22:45 UTC, edimitchel commented on src/api/sfc-script-setup.md
> +Lorsqu'un parent accède à une instance de ce composant via des refs de template, l'instance récupérée sera de la forme `{ a : nombre, b : nombre }` (les refs sont automatiquement déballés comme pour
```suggestion
Lorsqu'un parent accède à une instance de ce composant via des refs de template, l'instance récupérée sera de la forme `{ a: number, b: number }` (les refs sont automatiquement déballés comme pour les instances normales).
```

2023-02-12 22:45 UTC, edimitchel commented on src/api/sfc-script-setup.md
> +  - En mode développement, le compilateur essaiera de déduire la validation d'exécution correspondante à partir des types. Par exemple, ici, `foo : String` est déduit du type `foo : string`. Si le ty
```suggestion
  - En mode développement, le compilateur essaiera de déduire la validation d'exécution correspondante à partir des types. Par exemple, ici, `foo: String` est déduit du type `foo: string`. Si le type est une référence à un type importé, le résultat déduit sera `foo: null` (égal au type `any`) puisque le compilateur n'a pas d'information sur les fichiers externes.
```

2023-02-12 22:45 UTC, edimitchel commented on src/api/sfc-script-setup.md
>  One drawback of the type-only `defineProps` declaration is that it doesn't have a way to provide default values for the props. To resolve this problem, a `withDefaults` compiler macro is also provide
oubli

2023-02-13 19:23 UTC, tlagoda commented on src/api/sfc-script-setup.md
> +Lorsque vous utilisez `<script setup>`, toutes les liaisons de haut niveau (y compris les variables, les déclarations de fonctions et les imports) déclarées dans `<script setup>` sont directement uti
```suggestion
Lorsque vous utilisez `<script setup>`, toutes liaisons de haut niveau (y compris les variables, les déclarations de fonctions et les imports) déclarées dans `<script setup>` est directement utilisable dans le template :
```

Je pars plutôt sur ça!

2023-02-13 19:27 UTC, tlagoda commented on src/api/sfc-script-setup.md
>  One drawback of the type-only `defineProps` declaration is that it doesn't have a way to provide default values for the props. To resolve this problem, a `withDefaults` compiler macro is also provide
oups!

2023-02-14 09:48 UTC, edimitchel requested changes

2023-02-14 09:48 UTC, edimitchel commented on src/api/sfc-script-setup.md
> +Ceci sera compilé en options `default` pour les props d'exécution. De plus, l'utilitaire `withDefaults` fournit des vérifications de type pour les valeurs par défaut, et assure que le type de `props`
```suggestion
Ceci sera compilé en props avec la valeur `default`. De plus, l'utilitaire `withDefaults` fournit des vérifications de type pour les valeurs par défaut, et assure que le type de `props` retourné n'a pas les flags optionnels pour les propriétés qui ont des valeurs par défaut de déclarées.
```

2023-02-15 08:47 UTC, edimitchel approved these changes

2023-02-15 08:51 UTC, edimitchel approved these changes

2023-02-15 08:51 UTC, merged