api/composition-api-dependency-injection.md
vuejs-translations/docs-fr pull request #316
Opened 2023-02-12 09:39 UTC by tlagoda

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #315 
      
Remarques: traduction de `factory` ? on met `usine` ?

2023-02-12 21:56 UTC, edimitchel requested changes

2023-02-12 21:56 UTC, edimitchel commented on src/api/composition-api-dependency-injection.md
> +  Le second argument est optionnel et représente la valeur par défaut à utiliser si aucune valeur correspondante n'a été trouvée. Il peut aussi être une fonction d'usine pour retourner des valeurs qu
```suggestion
  Le second argument est optionnel et représente la valeur par défaut à utiliser si aucune valeur correspondante n'a été trouvée. Il peut aussi être une fonction _factory_ pour retourner des valeurs qui sont coûteuses à créer. Si la valeur par défaut est une fonction, alors `false` doit être passé comme troisième argument pour indiquer que la fonction doit être utilisée comme valeur au lieu de celle produite par la _factory_.
```

2023-02-13 17:27 UTC, tlagoda commented on src/api/composition-api-dependency-injection.md
> +  Le second argument est optionnel et représente la valeur par défaut à utiliser si aucune valeur correspondante n'a été trouvée. Il peut aussi être une fonction d'usine pour retourner des valeurs qu
Une suggestion pour les lignes 57 et 96?

2023-02-14 09:43 UTC, edimitchel requested changes

2023-02-14 09:43 UTC, edimitchel commented on src/api/composition-api-dependency-injection.md
> +  // en utilisant une usine
```suggestion
  // en utilisant une fonction factory
```

2023-02-14 09:43 UTC, edimitchel commented on src/api/composition-api-dependency-injection.md
> +  // injection avec une valeur par défaut usine
```suggestion
  // injection avec une valeur par défaut via une fonction factory
```

2023-02-15 08:50 UTC, edimitchel approved these changes

2023-02-15 08:50 UTC, merged