api/options-composition.md
vuejs-translations/docs-fr pull request #318
Opened 2023-02-12 20:37 UTC by tlagoda

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #317

2023-02-12 21:43 UTC, edimitchel requested changes

2023-02-12 21:43 UTC, edimitchel commented on src/api/options-composition.md
> +- **Détails:**
```suggestion
- **Détails :**
```

2023-02-12 21:43 UTC, edimitchel commented on src/api/options-composition.md
> +- **Détails**
```suggestion
- **Détails :**
```

2023-02-12 21:43 UTC, edimitchel commented on src/api/options-composition.md
> +      - La propriété `default` est utilisée comme valeur de secours. Comme pour les valeurs par défaut des props, une fonction d'usine est nécessaire pour les types objets afin d'éviter le partage de
```suggestion
      - La propriété `default` est utilisée comme valeur de secours. Comme pour les valeurs par défaut des props, une fonction de fabrique est nécessaire pour les types objets afin d'éviter le partage de valeurs entre plusieurs instances de composants.
```

2023-02-12 21:43 UTC, edimitchel commented on src/api/options-composition.md
> +  Comme pour les valeurs par défaut des props, vous devez utiliser une fonction d'usine pour les valeurs non primitives :
```suggestion
  Comme pour les valeurs par défaut des props, vous devez utiliser une fonction de fabrication pour les valeurs non primitives :
```

En vrai, j'aime pas trop la traduction de fabrication, ça devrait rester factory qui fait référence au design pattern

2023-02-12 21:43 UTC, edimitchel commented on src/api/options-composition.md
> +- **Détails:**
```suggestion
- **Détails :**
```

2023-02-12 21:43 UTC, edimitchel commented on src/api/options-composition.md
> +  :::warning Plus recommandé
```suggestion
  :::warning N'est plus recommandé
```

2023-02-12 21:43 UTC, edimitchel commented on src/api/options-composition.md
> +  Dans Vue 2, les mixins étaient le principal mécanisme pour créer des morceaux réutilisables de la logique des composants. Bien que les mixins continuent d'être pris en charge dans Vue 3, la [Compos
```suggestion
  Dans Vue 2, les mixins étaient le principal mécanisme pour créer des morceaux réutilisables des logique de composants. Bien que les mixins continuent d'être pris en charge dans Vue 3, la [Composition API](/guide/reusability/composables.html) est désormais l'approche privilégiée pour la réutilisation du code entre les composants.
```

2023-02-12 21:43 UTC, edimitchel commented on src/api/options-composition.md
> +- **Exemple:**
```suggestion
- **Exemple :**
```

2023-02-12 21:43 UTC, edimitchel commented on src/api/options-composition.md
> +- **Détails:**
```suggestion
- **Détails :**
```

2023-02-12 21:43 UTC, edimitchel commented on src/api/options-composition.md
>  - **Example:**
```suggestion
- **Exemple :**
```

2023-02-13 19:32 UTC, tlagoda commented on src/api/options-composition.md
> +  Comme pour les valeurs par défaut des props, vous devez utiliser une fonction d'usine pour les valeurs non primitives :
ça me va parfaitement, j'ai traduit par principe mais c'est pas très parlant en français. Je laisse factory dans ce fichier, je ferais une PR pour corriger ailleurs

2023-02-14 09:22 UTC, edimitchel approved these changes

2023-02-14 09:22 UTC, merged