api/options-lifecycle.md
vuejs-translations/docs-fr pull request #325
Opened 2023-02-13 21:28 UTC by tlagoda

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #324 
      
Remarques: je ne sais pas si je dois traduire le dernier lien du fichier ? ça avait déjà été fait il me semble ?

2023-02-14 10:29 UTC, edimitchel requested changes

2023-02-14 10:29 UTC, edimitchel commented on src/api/options-lifecycle.md
> +Appelé juste avant que le composant ne soit sur le point de mettre à jour son arbre du DOM  après un changement d'état réactif.
```suggestion
Appelé juste avant que le composant ne soit sur le point de mettre à jour son arbre du DOM après un changement d'état réactif.
```

2023-02-14 10:29 UTC, edimitchel commented on src/api/options-lifecycle.md
> +  - Fonction `setup()`.
```suggestion
  - Fonction `setup()`
```

2023-02-14 10:29 UTC, edimitchel commented on src/api/options-lifecycle.md
> +  - Si plusieurs hooks `errorCaptured` existent sur la chaîne descendante ou la chaîne ascendante d'un composant, ils seront tous invoqués sur la même erreur, suivant un ordre allant de bas en haut.
```suggestion
  - Si plusieurs hooks `errorCaptured` existent sur la chaîne descendante ou la chaîne ascendante d'un composant, ils seront tous invoqués sur la même erreur, suivant un ordre allant de bas en haut. Cela est comparable au mécanisme de _bubbling_ des événements natifs du DOM.
```

2023-02-14 10:29 UTC, edimitchel commented on src/api/options-lifecycle.md
> +      // les données sont pré-récupérées sur le serveur car cela est plus que via le client.
```suggestion
      // les données sont pré-récupérées sur le serveur car cela est plus rapide que via le client.
```

2023-02-14 10:29 UTC, edimitchel commented on src/api/options-lifecycle.md
> +        // récupération côté client à la place.
```suggestion
        // est rendu dynamiquement sur le client.
        // Effectue la récupération côté client.
```

2023-02-14 10:29 UTC, edimitchel commented on src/api/options-lifecycle.md
> +- **Voir aussi :** [Rendu côté client](/guide/scaling-up/ssr.html)
```suggestion
- **Voir aussi :** [Rendu côté serveur](/guide/scaling-up/ssr.html)
```

2023-02-14 19:04 UTC, tlagoda commented on src/api/options-lifecycle.md
> +Appelé juste avant que le composant ne soit sur le point de mettre à jour son arbre du DOM  après un changement d'état réactif.
??

2023-02-15 08:50 UTC, edimitchel approved these changes

2023-02-15 08:50 UTC, merged