guide/extras/render-function.md
vuejs-translations/docs-fr pull request #335
Opened 2023-02-15 21:19 UTC by tlagoda

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #332 
      
Remarques: Une suggestion pour la ligne 652 ?

2023-02-15 22:56 UTC, edimitchel requested changes
par rapport à Vnodes, je suis partagé... entre garder vnodes car terme technique, introduire sous noeuds dom virtuel et continuer en utilisant vnodes...

2023-02-15 22:56 UTC, edimitchel commented on src/guide/extras/render-function.md
> +Les composants fonctionnels sont une autre forme de composants qui n'ont pas d'état propre. Ils agissent comme de pures fonctions : props in, vnodes out. Ils sont rendus sans créer d'instance de comp
```suggestion
Les composants fonctionnels sont une autre forme de composants qui n'ont pas d'état propre. Ils agissent comme de pures fonctions : props en entrée, nœuds DOM virtuels en sortie. Ils sont rendus sans créer d'instance de composant (c'est-à-dire sans `this`), et sans les hooks habituels du cycle de vie des composants.
```

2023-02-15 22:56 UTC, edimitchel commented on src/api/render-function.md
> +- **See also:** [Guide - Fonctions de rendu - Créer des Vnodes](/guide/extras/render-function.html#creating-vnodes)
```suggestion
- **See also:** [Guide - Fonctions de rendu - Créer des nœuds virtuel](/guide/extras/render-function.html#creating-vnodes)
```

2023-02-15 22:56 UTC, edimitchel commented on src/guide/extras/render-function.md
> +// qu'ils ont dans les modèles
```suggestion
// qu'ils ont dans les templates
```

2023-02-15 22:56 UTC, edimitchel commented on src/guide/extras/render-function.md
> +// les écouteurs d'événements doivent être passés suivant le modèle onXxx
```suggestion
// les écouteurs d'événements doivent être passés suivant le format onXxx
```

2023-02-15 22:56 UTC, edimitchel commented on src/guide/extras/render-function.md
> +La définition de type de Vue fournit également une inférence de type pour l'utilisation de TSX. Lorsque vous utilisez TSX, assurez-vous de spécifier `"jsx" : "preserve"` dans `tsconfig.json` afin que
```suggestion
La définition de type de Vue fournit également une inférence de type pour l'utilisation de TSX. Lorsque vous utilisez TSX, assurez-vous de spécifier `"jsx": "preserve"` dans `tsconfig.json` afin que TypeScript laisse la syntaxe du JSX intacte pour le bon fonctionnement de la transformation du JSX par Vue.
```

2023-02-15 22:56 UTC, edimitchel commented on src/guide/extras/render-function.md
> +## Modèles de fonctions de rendu {#render-function-recipes}
```suggestion
## Recettes de fonctions de rendu {#render-function-recipes}
```
ou
```suggestion
## Exemples de fonctions de rendu {#render-function-recipes}
```
à changer dans le paragraphe ci-dessous si l'un des deux te convient mieux

2023-02-15 22:56 UTC, edimitchel commented on src/guide/extras/render-function.md
> +Les composants fonctionnels sont une autre forme de composants qui n'ont pas d'état propre. Ils agissent comme de pures fonctions : props in, vnodes out. Ils sont rendus sans créer d'instance de comp
garder la formulation mais choisir le terme vnodes ou noeuds selon le choix effectué.

2023-02-16 20:41 UTC, tlagoda commented on src/guide/extras/render-function.md
> +Les composants fonctionnels sont une autre forme de composants qui n'ont pas d'état propre. Ils agissent comme de pures fonctions : props in, vnodes out. Ils sont rendus sans créer d'instance de comp
perso `vnode` me choque pas, et puis c'est un terme assez régulièrement utilisé. Je vais l'introduire au début de la page, puis je reste sur `vnode` si ça te va 👍

2023-02-16 20:44 UTC, tlagoda commented on src/guide/extras/render-function.md
> +## Modèles de fonctions de rendu {#render-function-recipes}
je pars sur `exemple` 👍

2023-02-16 22:40 UTC, edimitchel approved these changes

2023-02-16 22:40 UTC, merged

2023-02-16 22:40 UTC, edimitchel commented on src/guide/extras/render-function.md
> +Les composants fonctionnels sont une autre forme de composants qui n'ont pas d'état propre. Ils agissent comme de pures fonctions : props in, vnodes out. Ils sont rendus sans créer d'instance de comp
Très bonne idée!