api/ssr.md
vuejs-translations/docs-fr pull request #337
Opened 2023-02-16 21:42 UTC by tlagoda

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #336 
      
Remarques: j'ai eu pas mal de difficultés dans ce fichier, j'attends vos retours!

2023-02-16 23:17 UTC, edimitchel reviewed
discutons en si tu en as besoin

2023-02-16 23:17 UTC, edimitchel commented on src/api/ssr.md
> +  // dans un environnement prenant en charge ReadableStream
```suggestion
  // dans un environnement prenant en charge _ReadableStream_
```

2023-02-16 23:17 UTC, edimitchel commented on src/api/ssr.md
> +Effectue le rendu de l'entrée sous forme de [stream web lisible](https://developer.mozilla.org/fr/docs/Web/API/Streams_API).
```suggestion
Effectue le rendu de l'entrée sous forme d'un [_Readable Stream_ web](https://developer.mozilla.org/fr/docs/Web/API/Streams_API).
```

2023-02-16 23:17 UTC, edimitchel commented on src/api/ssr.md
> +Effectue le rendu et la transmission à une instance existante d'un [stream modifiable web](https://developer.mozilla.org/fr/docs/Web/API/WritableStream).
```suggestion
Effectue le rendu et le transfert à une instance existante d'un [_Writable Stream_ web](https://developer.mozilla.org/en-US/docs/Web/API/WritableStream).
```

La doc en français n'existe pas

2023-02-16 23:17 UTC, edimitchel commented on src/api/ssr.md
> +          // fait
```suggestion
          // terminé
```

2023-02-16 23:17 UTC, edimitchel commented on src/api/ssr.md
> +    // ...joint des propriétés au contexte
```suggestion
    // ...attache des propriétés au contexte
```

2023-02-16 23:17 UTC, edimitchel requested changes
discutons en si tu en as besoin

2023-02-17 20:37 UTC, tlagoda commented on src/api/ssr.md
> +Effectue le rendu et la transmission à une instance existante d'un [stream modifiable web](https://developer.mozilla.org/fr/docs/Web/API/WritableStream).
oups

2023-02-17 22:05 UTC, edimitchel approved these changes

2023-02-17 22:06 UTC, merged