api/reactivity-core.md
vuejs-translations/docs-fr pull request #344
Opened 2023-02-18 22:30 UTC by tlagoda

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #343 
      
Remarques: j'ai utilisé `fonction de rappel` parfois, et `rappel` d'autres fois. Pour moi c'est cohérent. Je sais pas ce que vous en dites ?

2023-02-19 21:54 UTC, edimitchel requested changes

2023-02-19 21:54 UTC, edimitchel commented on src/api/reactivity-core.md
> +  TL'objet ref est mutable - c'est-à-dire que vous pouvez attribuer de nouvelles valeurs à `.value`. Il est également réactif - c'est-à-dire que toute lecture de `.value` est traquée, et que les opér
```suggestion
  L'objet ref est mutable - c'est-à-dire que vous pouvez attribuer de nouvelles valeurs à `.value`. Il est également réactif - c'est-à-dire que toute lecture de `.value` est traquée, et que les opérations d'écriture déclenchent les effets associés.
```

2023-02-19 21:54 UTC, edimitchel commented on src/api/reactivity-core.md
>    - [Guide - Computed Debugging](/guide/extras/reactivity-in-depth.html#computed-debugging)
à traduire, c'est un oubli

2023-02-19 21:54 UTC, edimitchel commented on src/api/reactivity-core.md
>    type StopHandle = () => void
4 lignes plus haut, manque la traduction de `default`

2023-02-19 21:54 UTC, edimitchel commented on src/api/reactivity-core.md
> +  Le premier argument est la fonction à exécuter. La fonction reçoit elle-même une fonction qui peut être utilisée pour enregistrer un rappel de nettoyage. Le rappel de nettoyage sera appelé juste av
```suggestion
  Le premier argument est la fonction à exécuter qui reçoit elle-même en argument une fonction qui peut être utilisée pour enregistrer une fonction de nettoyage. La fonction de nettoyage sera appelé juste avant la prochaine exécution de l'effet, et peut être utilisé pour nettoyer les effets secondaires invalidés, par exemple une requête asynchrone en attente (voir l'exemple ci-dessous).
```

2023-02-19 21:54 UTC, edimitchel commented on src/api/reactivity-core.md
> +  Par défaut, les observateurs seront exécutés juste avant le rendu du composant. Définir `flush : 'post'` reportera l'exécution du watcher après le rendu du composant. Voir le paragraphe sur [le tim
```suggestion
  Par défaut, les observateurs seront exécutés juste avant le rendu du composant. Définir `flush: 'post'` reportera l'exécution du watcher après le rendu du composant. Voir le paragraphe sur [le timing du nettoyage des fonction de rappel](/guide/essentials/watchers.html#callback-flush-timing) pour plus d'informations. Dans de rares cas, il peut être nécessaire de déclencher un observateur immédiatement lorsqu'une dépendance réactive change, par exemple pour invalider un cache. Ceci peut être réalisé en utilisant `flush: 'sync'`. Cependant, ce paramètre doit être utilisé avec prudence, car il peut entraîner des problèmes de performance et de cohérence des données si plusieurs propriétés sont mises à jour en même temps.
```

2023-02-19 21:54 UTC, edimitchel commented on src/api/reactivity-core.md
> +  Par défaut, les observateurs seront exécutés juste avant le rendu du composant. Définir `flush : 'post'` reportera l'exécution du watcher après le rendu du composant. Voir le paragraphe sur [le tim
Pour les `:` utilisés dans du code ne sont pas être espacer.

2023-02-19 21:54 UTC, edimitchel commented on src/api/reactivity-core.md
> +  La valeur de retour est une fonction gestionnaire qui peut être appelée pour empêcher l'effet de s'exécuter à nouveau.
```suggestion
  La valeur de retour est une fonction de gestion qui peut être appelée pour empêcher l'effet de s'exécuter à nouveau.
```

2023-02-19 21:54 UTC, edimitchel commented on src/api/reactivity-core.md
>    - [Guide - Watcher Debugging](/guide/extras/reactivity-in-depth.html#watcher-debugging)
à traduire

2023-02-19 21:54 UTC, edimitchel commented on src/api/reactivity-core.md
> +  Le second argument est la fonction de rappel qui sera appelée lorsque la source sera modifiée. Celle-ci reçoit trois arguments : la nouvelle valeur, l'ancienne, et une fonction pour enregistrer un
```suggestion
  Le second argument est la fonction de rappel qui sera appelée lorsque la source sera modifiée. Celle-ci reçoit trois arguments : la nouvelle valeur, l'ancienne, et une fonction pour enregistrer une fonction de nettoyage des effets secondaires. La fonction de nettoyage serae appelé juste avant la prochaine exécution de l'effet, et peut être utilisée pour nettoyer les effets secondaires invalidés, par exemple une requête asynchrone en attente.
```

2023-02-19 21:54 UTC, edimitchel commented on src/api/reactivity-core.md
> +  Par rapport à [`watchEffect()`](#watcheffect), `watch()` nous permet de :
```suggestion
  Comparée à [`watchEffect()`](#watcheffect), `watch()` nous permet de :
```

2023-02-19 21:54 UTC, edimitchel commented on src/api/reactivity-core.md
> +  Lorsque vous utilisez une source accesseur, l'observateur ne se déclenche que si la valeur de retour de l'accesseur a changé. Si vous voulez que la fonction de rappel se déclenche même lors de muta
```suggestion
  Lorsque vous utilisez une source accesseur, l'observateur ne se déclenche que si la valeur de retour de l'accesseur a changé. Si vous voulez que la fonction de rappel se déclenche même lors de mutations profondes, vous devez explicitement forcer l'observateur à fonctionner en mode profond avec `{ deep: true }`. Notez qu'en mode profond, la nouvelle valeur et l'ancienne seront le même objet si la fonction de rappel a été déclenchée par une mutation profonde :
```

2023-02-19 21:54 UTC, edimitchel commented on src/api/reactivity-core.md
> +`watch()` a les mêmes options de minuteur et de débogage que [`watchEffect()`](#watcheffect) :
```suggestion
`watch()` a les mêmes options de timing et de débogage que [`watchEffect()`](#watcheffect) :
```

2023-02-19 21:54 UTC, edimitchel commented on src/api/reactivity-core.md
> +  // lorsqu'on a plus besoin de l'observateur :
```suggestion
  // lorsque'on n'a plus besoin de l'observateur :
```

2023-02-19 21:54 UTC, edimitchel commented on src/api/reactivity-core.md
>    - [Guide - Watcher Debugging](/guide/extras/reactivity-in-depth.html#watcher-debugging)
à traduire

2023-02-19 21:54 UTC, edimitchel commented on src/guide/extras/composition-api-faq.md
> +- [API de réactivité](/api/reactivity-core.html), e.g. `ref()` and `reactive()`, that allows us to directly create reactive state, computed state, and watchers.
```suggestion
- [API de la réactivité](/api/reactivity-core.html), e.g. `ref()` and `reactive()`, that allows us to directly create reactive state, computed state, and watchers.
```

2023-02-19 21:54 UTC, edimitchel commented on src/api/reactivity-core.md
> +# API de réactivité : Essentiel {#reactivity-api-core}
```suggestion
# API de la réactivité : Essentiel {#reactivity-api-core}
```

2023-02-19 22:17 UTC, tlagoda commented on src/api/reactivity-core.md
>    - [Guide - Watcher Debugging](/guide/extras/reactivity-in-depth.html#watcher-debugging)
je m'occupe des modifs demain mais reactivity-in-depth n'a pas encore été traduit si je ne dis pas de bétises, c'est pour ça que je n'ai pas traduit ce lien, ni celui un peu plus haut

2023-02-19 22:23 UTC, tlagoda commented on src/api/reactivity-core.md
> +  Le premier argument est la fonction à exécuter. La fonction reçoit elle-même une fonction qui peut être utilisée pour enregistrer un rappel de nettoyage. Le rappel de nettoyage sera appelé juste av
```suggestion
  Le premier argument est la fonction à exécuter qui reçoit elle-même en argument une fonction qui peut être utilisée pour enregistrer une fonction de nettoyage. La fonction de nettoyage sera appelée juste avant la prochaine exécution de l'effet, et peut être utilisé pour nettoyer les effets secondaires invalidés, par exemple une requête asynchrone en attente (voir l'exemple ci-dessous).
```

mémo

2023-02-19 22:46 UTC, edimitchel commented on src/api/reactivity-core.md
>    - [Guide - Watcher Debugging](/guide/extras/reactivity-in-depth.html#watcher-debugging)
ha effectivement je me suis trompé!

2023-02-20 08:41 UTC, edimitchel commented on src/api/reactivity-core.md
> +  Par défaut, les observateurs seront exécutés juste avant le rendu du composant. Définir `flush: 'post'` reportera l'exécution du watcher après le rendu du composant. Voir le paragraphe sur [le timi
```suggestion
  Par défaut, les observateurs seront exécutés juste avant le rendu du composant. Définir `flush: 'post'` reportera l'exécution du watcher après le rendu du composant. Voir le paragraphe sur [le timing du nettoyage des fonctions de rappel](/guide/essentials/watchers.html#callback-flush-timing) pour plus d'informations. Dans de rares cas, il peut être nécessaire de déclencher un observateur immédiatement lorsqu'une dépendance réactive change, par exemple pour invalider un cache. Ceci peut être réalisé en utilisant `flush: 'sync'`. Cependant, ce paramètre doit être utilisé avec prudence, car il peut entraîner des problèmes de performance et de cohérence des données si plusieurs propriétés sont mises à jour en même temps.
```

2023-02-20 08:42 UTC, edimitchel approved these changes

2023-02-20 08:48 UTC, merged