guide/extras/rendering-mechanism.md
vuejs-translations/docs-fr pull request #346
Opened 2023-02-20 06:36 UTC by tlagoda

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #345 
      
Remarques: Pas trop sûr concernant : 
_ `diff` / `diffing`
_ `static hoisting`
_ `tree flattening`

2023-02-20 08:48 UTC, edimitchel reviewed
Tu peux traduire toute l'image je pense

2023-02-20 23:45 UTC, tlagoda commented
> Tu peux traduire toute l'image je pense

done 👍

2023-02-21 08:30 UTC, edimitchel approved these changes

2023-02-21 08:31 UTC, edimitchel requested changes

2023-02-21 08:31 UTC, edimitchel commented on src/guide/extras/rendering-mechanism.md
> +2. **Montage** : Le moteur d'exécution invoque les fonctions de rendu, parcourt l'arbre du DOM virtuel retourné et crée des nœuds DOM réels en fonction. Cette étape est réalisée comme un [effet réact
```suggestion
2. **Montage** : Le moteur d'exécution invoque les fonctions de rendu, parcourt l'arbre du DOM virtuel retourné et crée des nœuds DOM réels en fonction. Cette étape est réalisée comme un [effet réactif](./reactivity-in-depth), et garde donc la trace de toutes les dépendances réactives qui ont été utilisées.
```

2023-02-21 09:09 UTC, edimitchel requested changes

2023-02-21 09:09 UTC, edimitchel commented on src/guide/extras/rendering-mechanism.md
> +Les options de correction et la réduction des arbres améliorent également considérablement les performances de Vue en matière d'[hydratation SSR](/guide/scaling-up/ssr.html#client-hydration) :
```suggestion
Les drapeaux de correction et la réduction des arbres améliorent également considérablement les performances de Vue en matière d'[hydratation SSR](/guide/scaling-up/ssr.html#client-hydration) :
```

2023-02-21 19:43 UTC, tlagoda commented on src/guide/extras/rendering-mechanism.md
>  <!-- https://www.figma.com/file/elViLsnxGJ9lsQVsuhwqxM/Rendering-Mechanism -->
yes!

2023-02-21 19:44 UTC, tlagoda commented on src/guide/extras/rendering-mechanism.md
> +}, null, 2 /* classe */)
my bad!

2023-02-21 19:45 UTC, tlagoda commented on src/guide/extras/rendering-mechanism.md
> +### Réduction d'un arbre {#tree-flattening}
Oui, ou sinon `élagage` mais encore une fois on va se faire taper dessus par les écolos 🤣

2023-02-21 19:46 UTC, tlagoda commented on src/guide/extras/rendering-mechanism.md
> +Les options de correction et la réduction des arbres améliorent également considérablement les performances de Vue en matière d'[hydratation SSR](/guide/scaling-up/ssr.html#client-hydration) :
J'ai mis options partout.. Tu tiens vraiment à mettre drapeaux ? Perso en FR ça me parle pas

2023-02-21 21:31 UTC, edimitchel commented on src/guide/extras/rendering-mechanism.md
> +Les options de correction et la réduction des arbres améliorent également considérablement les performances de Vue en matière d'[hydratation SSR](/guide/scaling-up/ssr.html#client-hydration) :
en fait, pour moi, les informations flags sont comme des marques pour bien identifier les caractéristiques.. du coup, drapeaux en français je l'utilise souvent pour dire une variable booléenne..

soit, je pense avoir trouver une autre manière de dire flags:
```suggestion
Les marques de correction et la réduction des arbres améliorent également considérablement les performances de Vue en matière d'[hydratation SSR](/guide/scaling-up/ssr.html#client-hydration) :
```

2023-02-22 08:30 UTC, merged