guide/extras/reactivity-in-depth.md
vuejs-translations/docs-fr pull request #348
Opened 2023-02-21 22:30 UTC by tlagoda

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #347

2023-02-22 08:59 UTC, edimitchel requested changes
Globalement je serai plutôt d'avis d'utiliser _en détail_ plutôt que _en profondeur_ qui pourrait être mal interpréter pouvant faire allusion à la réactivité profond (deep)

2023-02-22 08:59 UTC, edimitchel commented on src/guide/extras/reactivity-in-depth.md
>  One of Vue’s most distinctive features is the unobtrusive reactivity system. Component state consists of reactive JavaScript objects. When you modify them, the view updates. It makes state management
Ben alors?

et les paragraphes d'après

Certainement c'est venu avec le rebase, j'ai vu passer des changements sur ce fichier

2023-02-22 08:59 UTC, edimitchel commented on src/guide/extras/reactivity-in-depth.md
> +Nous ne pouvons pas tout à fait suivre la lecture et l'écriture des variables locales comme dans l'exemple. Il n'y a tout simplement pas de mécanisme pour le faire dans le JavaScript classique. Ce qu
```suggestion
Nous ne pouvons pas tout à fait suivre la lecture et l'écriture des variables locales comme dans l'exemple. Il n'y a tout simplement pas de mécanisme pour le faire avec du JavaScript classique. Ce que nous **pouvons** faire cependant, c'est intercepter la lecture et l'écriture des **propriétés d'un objet**.
```

2023-02-22 08:59 UTC, edimitchel commented on src/guide/extras/reactivity-in-depth.md
> +Cela explique certaines [limitations des objets réactifs](/guide/essentials/reactivity-fundamentals.html#limitations-of-reactive) que nous avons abordées dans la section sur les principes fondamentau
```suggestion
Cela explique certaines [limitations des objets réactifs](/guide/essentials/reactivity-fundamentals.html#limitations-of-reactive) que nous avons abordées dans la section sur les principes fondamentaux :
```

2023-02-22 08:59 UTC, edimitchel commented on src/guide/extras/reactivity-in-depth.md
> +- Lorsque vous assignez ou déstructurez la propriété d'un objet réactif à une variable locale, la réactivité est "déconnectée" car l'accès à la variable locale ne déclenche plus les pièges d'accès /
```suggestion
- Lorsque vous assignez ou déstructurez la propriété d'un objet réactif à une variable locale, la réactivité est "déconnectée" car l'accès à la variable locale ne déclenche plus les mécanismes d'accès / de mutation du proxy.
```

2023-02-22 08:59 UTC, edimitchel commented on src/guide/extras/reactivity-in-depth.md
> +# La réactivité en profondeur {#reactivity-in-depth}
```suggestion
# La réactivité en détails {#reactivity-in-depth}
```

2023-02-22 08:59 UTC, edimitchel commented on src/guide/extras/reactivity-in-depth.md
> +Les API `ref()`, `computed()` et `watchEffect()` font toutes partie de la Composition API. Si vous n'avez utilisé que l'Options API avec Vue jusqu'à présent, vous remarquerez que la Composition API e
```suggestion
Les API `ref()`, `computed()` et `watchEffect()` font toutes partie de la Composition API. Si vous n'avez utilisé que l'Options API avec Vue jusqu'à présent, vous remarquerez que la Composition API est plus proche de la façon dont le système de réactivité de Vue fonctionne sous le capot. En fait, dans Vue 3, l'Options API est mise en œuvre par dessus la Composition API. Tous les accès aux propriétés de l'instance du composant (`this`) déclenchent des accesseurs / mutateurs pour le suivi de la réactivité, et les options comme `watch` et `computed` invoquent leurs équivalents de la Composition API en interne.
```

2023-02-22 08:59 UTC, edimitchel commented on src/guide/extras/reactivity-in-depth.md
> +L'idée générale derrière l'intégration du système de réactivité de Vue avec une solution externe de gestion d'état est de conserver l'état externe dans un [`shallowRef`](/api/reactivity-advanced.html
```suggestion
L'idée générale derrière l'intégration du système de réactivité de Vue avec une solution externe de gestion d'état est de conserver l'état externe dans un [`shallowRef`](/api/reactivity-advanced.html#shallowref). Une ref peu profonde n'est réactive que lorsqu'on accède à sa propriété `.value` - la valeur interne reste intacte. Lorsque l'état externe change, remplacer la valeur de la ref pour déclencher les mises à jour.
```

2023-02-22 10:49 UTC, tlagoda commented on src/guide/extras/reactivity-in-depth.md
>  One of Vue’s most distinctive features is the unobtrusive reactivity system. Component state consists of reactive JavaScript objects. When you modify them, the view updates. It makes state management
Oui j'avais tout trad :(

2023-02-22 20:00 UTC, edimitchel commented
J'ai update main depuis upstream, y a du nouveau texte à traduire

2023-02-22 21:03 UTC, tlagoda commented on src/guide/extras/reactivity-in-depth.md
> +L'idée générale derrière l'intégration du système de réactivité de Vue avec une solution externe de gestion d'état est de conserver l'état externe dans un [`shallowRef`](/api/reactivity-advanced.html
Non c'est de l'impératif

2023-02-22 22:36 UTC, edimitchel requested changes

2023-02-22 22:36 UTC, edimitchel commented on src/guide/extras/reactivity-in-depth.md
>  console.log(A2) // Still 3
```suggestion
 console.log(A2) // Toujours 3
```

2023-02-22 22:36 UTC, edimitchel commented on src/guide/extras/reactivity-in-depth.md
> +Ce dont nous avons besoin, c'est d'une fonction magique qui puisse invoquer `update()` (l' **effet**) chaque fois que `A0` ou `A1` (les **dépendances**) changent :
```suggestion
Ce dont nous avons besoin, c'est d'une fonction magique qui puisse invoquer `update()` (l'**effet**) chaque fois que `A0` ou `A1` (les **dépendances**) changent :
```

2023-02-22 22:36 UTC, edimitchel commented on src/guide/extras/reactivity-in-depth.md
> +- [Signaux de Qwik](https://qwik.builder.io/docs/components/state/#usesignal)
Je garderai les termes non traduits

2023-02-22 22:36 UTC, edimitchel commented on src/guide/extras/reactivity-in-depth.md
> +- [Signaux de Qwik](https://qwik.builder.io/docs/components/state/#usesignal)
Ou alors Signals de Xxx

2023-02-22 22:36 UTC, edimitchel commented on src/guide/extras/reactivity-in-depth.md
> +Fondamentalement, les signaux sont le même genre de primitive de réactivité que les refs de Vue. Il s'agit d'un conteneur de valeurs qui permet la traque des dépendances lors de l'accès et le déclenc
```suggestion
Fondamentalement, les signaux sont le même genre de primitive de réactivité que les refs de Vue. Il s'agit d'un conteneur de valeurs qui permet la traque des dépendances lors de l'accès et le déclenchement d'effets lors de la mutation. Dans certains contextes, les signaux sont également liés au modèle de rendu, les mises à jour sont alors effectuées par le biais d'abonnements finement ajustés, bien que cela ne soit pas nécessaire pour en faire un signal.
```

2023-02-22 22:36 UTC, edimitchel commented on src/guide/extras/reactivity-in-depth.md
>  setCount(1) // update the value
Traduction et au dessus aussi

2023-02-22 22:36 UTC, edimitchel commented on src/guide/extras/reactivity-in-depth.md
> +Fondamentalement, les signaux sont le même genre de primitive de réactivité que les refs de Vue. Il s'agit d'un conteneur de valeurs qui permet la traque des dépendances lors de l'accès et le déclenc
Gardez signals pas traduire en signaux

2023-02-23 08:39 UTC, edimitchel commented
Gardons le terme dirty checking à mettre en italique

2023-02-23 20:13 UTC, tlagoda commented on src/guide/extras/reactivity-in-depth.md
> +- [Signaux de Qwik](https://qwik.builder.io/docs/components/state/#usesignal)
Ok pour Signals de XXX 👍

2023-02-23 20:16 UTC, tlagoda commented on src/guide/extras/reactivity-in-depth.md
> +Fondamentalement, les signaux sont le même genre de primitive de réactivité que les refs de Vue. Il s'agit d'un conteneur de valeurs qui permet la traque des dépendances lors de l'accès et le déclenc
Ok 🇫🇷

2023-02-23 20:31 UTC, edimitchel approved these changes

2023-02-23 20:31 UTC, merged