about/faq.md
vuejs-translations/docs-fr pull request #370
Opened 2023-03-03 21:06 UTC by tlagoda

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #366

2023-03-03 21:26 UTC, edimitchel requested changes

2023-03-03 21:26 UTC, edimitchel commented on src/about/faq.md
> +# Questions fréquemment posées {#frequently-asked-questions}
```suggestion
# Questions fréquemment posées (FAQ) {#frequently-asked-questions}
```

2023-03-03 21:26 UTC, edimitchel commented on src/about/faq.md
> +Malgré les différences, la majorité des API de Vue sont partagées entre les deux versions majeures, donc la plupart de vos connaissances de Vue 2 continueront à fonctionner dans Vue 3. Notamment, l'A
```suggestion
Malgré les différences, la majorité des API de Vue sont partagées entre les deux versions majeures, donc la plupart de vos connaissances de Vue 2 continueront à fonctionner dans Vue 3. Notamment, la Composition API était à l'origine une fonctionnalité réservée à Vue 3, mais elle a été intégrée à Vue 2 de façon rétroactive et est disponible avec [Vue 2.7](https://github.com/vuejs/vue/blob/main/CHANGELOG.md#270-2022-07-01).
```

2023-03-03 21:26 UTC, edimitchel commented on src/about/faq.md
> +Dans les scénarios de test de stress, Vue surpasse React et Angular avec une marge décente dans le [js-framework-benchmark](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-resu
```suggestion
Dans les scénarios de test de stress, Vue surpasse React et Angular avec une marge décente dans le [js-framework-benchmark](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html). Il est également au coude à coude avec certains des frameworks sans DOM virtuel les plus rapides du benchmark.
```
je ne vois pas traduction claire à production-level, je pense que c'est pas utile de traduire

2023-03-03 21:26 UTC, edimitchel commented on src/about/faq.md
> +Lorsque vous utilisez une étape de build, de nombreuses API de Vue peuvent être ["retirées de l'arbre"](https://developer.mozilla.org/fr/docs/Glossary/Tree_shaking). Par exemple, si vous n'utilisez p
```suggestion
Lorsque vous utilisez un outil de build, de nombreuses API de Vue peuvent être ["retirées de l'arbre"](https://developer.mozilla.org/fr/docs/Glossary/Tree_shaking). Par exemple, si vous n'utilisez pas le composant natif `<Transition>`, il ne sera pas inclus dans le paquet de production final.
```

2023-03-03 21:26 UTC, edimitchel commented on src/about/faq.md
> +Lorsque Vue est utilisé sans outil de build, non seulement nous perdons la possibilité d'alléger l'arbre, mais nous devons également envoyer le compilateur de templates au navigateur. Cela fait gonfl
```suggestion
Lorsque Vue est utilisé sans outil de build, non seulement nous perdons la possibilité d'alléger l'arbre, mais nous devons également envoyer le compilateur de templates au navigateur. Cela fait gonfler la taille à environ **41 Ko**. Par conséquent, si vous utilisez Vue principalement pour l'amélioration progressive sans outil de build, envisagez d'utiliser [petite-vue](https://github.com/vuejs/petite-vue) (seulement **6 Ko**) à la place.
```

2023-03-03 23:23 UTC, tlagoda commented on src/about/faq.md
> +Dans les scénarios de test de stress, Vue surpasse React et Angular avec une marge décente dans le [js-framework-benchmark](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-resu
exact!

2023-03-04 08:21 UTC, edimitchel approved these changes

2023-03-04 08:21 UTC, merged