api/component-instance.md
vuejs-translations/docs-fr pull request #394
Opened 2023-03-05 18:29 UTC by ElisePatrikainen

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-03-06 13:20 UTC, edimitchel requested changes
Merci pour ce travail encore en progression.
Quelques oublis, mais dans en l'état c'est déjà pas mal pour une première :)

2023-03-06 13:20 UTC, edimitchel commented on src/api/component-instance.md
>  - **Type**
On a pris l'habitude de mettre un double point pour ce genre de titre

```suggestion
- **Type :**
```

Applicable aux autres :) (n'hésite pas à faire un rechercher/remplacer)

2023-03-06 13:20 UTC, edimitchel commented on src/api/component-instance.md
> +  - Pour les composants avec des nœuds racines multiples, `$el` sera un nœud du DOM fictif que Vue utilise pour suivre la position du composant dans le DOM (un nœud `Text`, ou un nœud `Comment` en mo
```suggestion
  - Pour les composants avec des nœuds racines multiples, `$el` sera un nœud du DOM fictif que Vue utilise pour suivre la position du composant dans le DOM (un nœud texte, ou un nœud `commentaire` en mode hydratation avec rendu côté serveur).
```
?

2023-03-06 13:20 UTC, edimitchel commented on src/api/component-instance.md
> +// TODO : voir comment traduire `resolved`, j'ai utilisé `résolu`
ça me va

2023-03-06 13:20 UTC, edimitchel commented on src/api/component-instance.md
> +  L'objet `$options` expose les options résolues pour l'instance courante du composant et est le résultat du merge de trois sources possibles :
```suggestion
  L'objet `$options` expose les options résolues pour l'instance courante du composant et est le résultat de la fusion de trois sources possibles :
```

2023-03-06 13:20 UTC, edimitchel commented on src/api/component-instance.md
manque la traduction de `default` au ci-dessus

2023-03-06 13:20 UTC, edimitchel commented on src/api/component-instance.md
> +  - **`immediate`**: déclenche la fonction de rappel immédiatement à la création de l'observateur. L'ancienne valeur vaudra `undefined` lors du premier appel.
```suggestion
  - **`immediate`** : déclenche la fonction de rappel immédiatement à la création de l'observateur. L'ancienne valeur vaudra `undefined` lors du premier appel.
```
espace insécable avant les `:`

2023-03-06 13:20 UTC, edimitchel commented on src/api/component-instance.md
>  - **Example**
```suggestion
- **Exemple :**
```

2023-03-06 13:20 UTC, edimitchel commented on src/api/component-instance.md
>    this.$watch(
commentaires à traduire ci-dessous

2023-03-06 13:20 UTC, edimitchel commented on src/api/component-instance.md
>    unwatch()
pareil ci-dessus

2023-03-06 13:20 UTC, edimitchel commented on src/api/component-instance.md
traduire les texte en commentaire ainsi que Example

2023-03-07 21:24 UTC, tlagoda commented
Hello, beau boulot pour le moment! 💪 
Attention toutefois à ce que les ajouts et les délétions soient égaux, actuellement ça n'est pas le cas, sûrement des sauts de ligne en trop/en moins :) Bon courage!

2023-03-07 21:46 UTC, edimitchel commented
> Hello, beau boulot pour le moment! 💪 Attention toutefois à ce que les ajouts et les délétions soient égaux, actuellement ça n'est pas le cas, sûrement des sauts de ligne en trop/en moins :) Bon courage!

C'est du aux TODO qu'elle a laissé rien de grave pour le moment. Et puis c'est encore en draft donc pas de soucis

2023-03-07 21:47 UTC, tlagoda commented
> > Hello, beau boulot pour le moment! 💪 Attention toutefois à ce que les ajouts et les délétions soient égaux, actuellement ça n'est pas le cas, sûrement des sauts de ligne en trop/en moins :) Bon courage!
> 
> C'est du aux TODO qu'elle a laissé rien de grave pour le moment. Et puis c'est encore en draft donc pas de soucis

Parfait alors!

2023-03-15 08:52 UTC, edimitchel commented on src/api/component-instance.md
> +  - **`immediate`**: déclenche la fonction de rappel immédiatement à la création de l'observateur. L'ancienne valeur vaudra `undefined` lors du premier appel.
ainsi que pour les lignes suivantes

2023-03-15 08:52 UTC, edimitchel requested changes

2023-03-15 08:52 UTC, edimitchel commented on src/api/component-instance.md
> +- **Example :**
```suggestion
- **Exemple :**
```

2023-03-15 08:52 UTC, edimitchel commented on src/api/component-instance.md
> +- **Example :**
```suggestion
- **Exemple :**
```

2023-03-16 07:59 UTC, ElisePatrikainen commented on src/api/component-instance.md
> +  - Pour les composants avec des nœuds racines multiples, `$el` sera un nœud du DOM fictif que Vue utilise pour suivre la position du composant dans le DOM (un nœud `Text`, ou un nœud `Comment` en mo
Pour les nœuds, je trouvais plus clair de laisser le nom des interfaces du DOM, qu'en penses-tu ? 

Et parfait pour le SSR, j'ai modifié, merci.

2023-03-16 10:35 UTC, edimitchel commented on src/api/component-instance.md
> +    flush?: 'pre' | 'post' | 'sync' // défaut: 'pre'
```suggestion
    immediate?: boolean // par défaut: false
    deep?: boolean // par défaut: false
    flush?: 'pre' | 'post' | 'sync' // par défaut: 'pre'
```

2023-03-16 10:35 UTC, edimitchel approved these changes

2023-03-16 10:38 UTC, edimitchel requested changes

2023-03-16 10:38 UTC, edimitchel commented on src/api/component-instance.md
> +Emmet un événement personnalisé depuis l'instance courante. Tout argument additionnel sera passé à la fonction de rappel.
```suggestion
Emet un événement personnalisé depuis l'instance courante. Tout argument additionnel sera passé à la fonction de rappel.
```

2023-03-17 22:54 UTC, tlagoda reviewed
Hey, bon boulot!

2023-03-17 22:54 UTC, tlagoda commented on src/api/component-instance.md
> +- **Details :**
```suggestion
- **Détails :**
```

2023-03-17 22:54 UTC, tlagoda commented on src/api/component-instance.md
> +- **Details :**
A corriger à plusieurs reprises dans le doc 👍

2023-03-17 22:54 UTC, tlagoda commented on src/api/component-instance.md
> +  Cette option est typiquement utilisée quand on créé manuellement des [render functions](/guide/extras/render-function), mais elle peut aussi être utilisée pour détecter si un slot est présent.
Tu peux traduire render function 😄

2023-03-17 22:54 UTC, tlagoda commented on src/api/component-instance.md
> +  Si un slot est un [scoped slot](/guide/components/slots#scoped-slots), les arguments passés à la fonction de slot sont rendus disponibles au slot en tant que props du slot.
scoped slot à traduire

2023-03-17 22:54 UTC, tlagoda commented on src/api/component-instance.md
> +Un objet constitué d'éléments du DOM et d'instances de composants, enregistré via les [template refs](/guide/essentials/template-refs).
tu peux traduire template refs

2023-03-17 22:54 UTC, tlagoda commented on src/api/component-instance.md
> +Un objet qui contient les attributs implicitement déclarés (fallthrough attributes) du composant.
```suggestion
Un objet qui contient les attributs implicitement déclarés (_fallthrough attributes_) du composant.
```

2023-03-17 22:54 UTC, tlagoda commented on src/api/component-instance.md
> +  [Attributs implicitement déclarés](/guide/components/attrs) sont des attributs ou écouteurs d'événements `v-on` passés par le composant parent mais non déclarés comme prop ou émission par le compos
```suggestion
  Les [attributs implicitement déclarés](/guide/components/attrs) sont des attributs ou écouteurs d'événements `v-on` passés par le composant parent mais non déclarés comme prop ou émission par le composant enfant.
```

2023-03-17 22:54 UTC, tlagoda commented on src/api/component-instance.md
> +API impérative pour créer des observateurs (watchers).
```suggestion
API impérative pour créer des observateurs.
```

2023-03-17 22:54 UTC, tlagoda commented on src/api/component-instance.md
> +  Le premier argument est la source observée. Cela peut être une string correspondant au nom d'une propriété du composant, ou une fonction accesseur.
```suggestion
  Le premier argument est la source observée. Cela peut être une chaîne de caractères correspondant au nom d'une propriété du composant, ou une fonction accesseur.
```

2023-03-17 22:54 UTC, tlagoda commented on src/api/component-instance.md
> +  - **`onTrack / onTrigger`** : débogue les dépendances de l'observateur. Voir [Débogage des observateur](/guide/extras/reactivity-in-depth#watcher-debugging).
```suggestion
  - **`onTrack / onTrigger`** : débogue les dépendances de l'observateur. Voir [débogage des observateur](/guide/extras/reactivity-in-depth#watcher-debugging).
```

2023-03-17 22:54 UTC, tlagoda commented on src/api/component-instance.md
> +  Observer via un path (délimité par des points) :
```suggestion
  Observer via un chemin (délimité par des points) :
```

2023-03-17 22:54 UTC, tlagoda commented on src/api/component-instance.md
> +Emet un événement personnalisé depuis l'instance courante. Tout argument additionnel sera passé à la fonction de rappel.
```suggestion
Émet un événement personnalisé depuis l'instance courante. Tout argument additionnel sera passé à la fonction de rappel.
```

2023-03-17 22:54 UTC, tlagoda commented on src/api/component-instance.md
> +  Ceci devrait être rarement nécessaire grâce au système de réactivité entièrement automatique de Vue. Le seul cas où vous devriez en avoir besoin est celui où vous auriez créé un composant à l'état
```suggestion
  Ceci devrait être rarement nécessaire grâce au système de réactivité entièrement automatique de Vue. Le seul cas où vous devriez en avoir besoin est celui où vous auriez créé un composant à l'état explicitement non-réactif en utilisant des API de réactivité avancées.
```

2023-03-19 17:11 UTC, ElisePatrikainen commented on src/api/component-instance.md
> +  Si un slot est un [scoped slot](/guide/components/slots#scoped-slots), les arguments passés à la fonction de slot sont rendus disponibles au slot en tant que props du slot.
Ah, ils n'ont pas été traduits dans la page sur les slots (https://github.com/vuejs-translations/docs-fr/blob/main/src/guide/components/slots.md?plain=1#L318), est-ce que je les traduis quand-même ?

2023-03-19 17:27 UTC, ElisePatrikainen commented
@tlagoda, merci pour tes commentaires ! Pour information j'ai pushé les retours demandés.

2023-03-19 17:43 UTC, edimitchel commented on src/api/component-instance.md
> +  Par cohérence, il est recommandé d'utiliser [les refs du template](/guide/essentials/template-refs) pour accéder directement aux éléments du DOM plutôt que `$el`.
```suggestion
  Par cohérence, il est recommandé d'utiliser [les refs de template](/guide/essentials/template-refs) pour accéder directement aux éléments du DOM plutôt que `$el`.
```

2023-03-19 17:44 UTC, edimitchel submitted a review, later dismissed

2023-03-19 17:46 UTC, edimitchel commented
As-tu pensé à mettre à jour les différentes références vers cette page?

Merci de rectifier et/ou cocher la case pour nous aider à pouvoir merger cette dernière page.

2023-03-19 17:50 UTC, ElisePatrikainen commented
> As-tu pensé à mettre à jour les différentes références vers cette page?
> 
> Merci de rectifier et/ou cocher la case pour nous aider à pouvoir merger cette dernière page.

Je viens justement de le faire :)

2023-03-19 18:47 UTC, edimitchel approved these changes

2023-03-19 18:49 UTC, merged