examples/circle-drawer
vuejs-translations/docs-fr pull request #438
Opened 2023-03-16 23:02 UTC by tlagoda

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #437

2023-03-17 08:24 UTC, edimitchel requested changes

2023-03-17 08:24 UTC, edimitchel commented on src/examples/src/circle-drawer/App/template.html
> +  <p>Ajusté le rayon du cercle situé en ({{ selected.cx }}, {{ selected.cy }})</p>
Ajusté ? Ajuster plutôt non?

2023-03-17 21:03 UTC, tlagoda commented on src/examples/src/circle-drawer/App/template.html
> +  <p>Ajusté le rayon du cercle situé en ({{ selected.cx }}, {{ selected.cy }})</p>
my bad! :o

2023-03-18 12:16 UTC, edimitchel approved these changes

2023-03-18 12:16 UTC, merged