Update reactivity-fundamentals.md
vuejs-translations/docs-fr pull request #472
Opened 2023-06-13 06:21 UTC by nobodyiam95

Translate the French string

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-06-13 08:06 UTC, edimitchel requested changes
Merci ! Est-ce que tu serais ok pour traduire toute les parties en anglais ? ça serait vraiment appréciable ;)

2023-06-13 08:06 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> + `ref()` prend l'argument et le renvoie enveloppé dans un objet ref avec une propriété `.value` :
```suggestion
`ref()` prend l'argument et le renvoie enveloppé dans un objet ref avec une propriété `.value` :
```

2023-06-13 09:46 UTC, nobodyiam95 commented on src/guide/essentials/reactivity-fundamentals.md
> + `ref()` prend l'argument et le renvoie enveloppé dans un objet ref avec une propriété `.value` :
Bien sûr je parcours la doc française actuellement s'il y'a des points qui sont pas traduits je ferai la traduction.

Existe t'il des pages anglaises non présentes dans la doc en français ?

2023-06-13 09:49 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> + `ref()` prend l'argument et le renvoie enveloppé dans un objet ref avec une propriété `.value` :
Oui, il y a toutes les pages qui demandent du travail de traduction : https://github.com/vuejs-translations/docs-fr/issues/461

Penses à prendre connaissance du guide de contributions pour avoir tous les bons réflexes, aussi, tu peux rejoindre notre discord :)

2023-06-23 18:12 UTC, tlagoda commented
On valide la mR et tu en refais une ?
@edimitchel

2023-06-23 18:33 UTC, edimitchel commented
Non manque la résolution de mon commentaire

2023-06-24 08:20 UTC, nobodyiam95 commented
Oui j’en veux bien une autre. MerciLe 23 juin 2023 à 20:12, tlagoda ***@***.***> a écrit :﻿
On valide la mR et tu en refais une ?
@edimitchel

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-06-24 08:37 UTC, edimitchel commented
Merci de rectifier ta PR @nobodyiam95 stp

2023-06-24 09:29 UTC, nobodyiam95 commented
@edimitchel quelle rectification je dois faire ?
Merci

2023-06-24 09:44 UTC, edimitchel commented
> @edimitchel quelle rectification je dois faire ?
> Merci

Ceci: https://github.com/vuejs-translations/docs-fr/pull/472#discussion_r1227704809

2023-06-24 10:19 UTC, nobodyiam95 commented
Merci @edimitchel j'en tiendrai compte les prochaines fois.

2023-06-24 11:14 UTC, edimitchel approved these changes

2023-06-24 11:14 UTC, merged