api/utility-types.md
vuejs-translations/docs-fr pull request #483
Opened 2023-06-14 07:07 UTC by tlagoda

Closes #479

2023-06-14 07:57 UTC, edimitchel requested changes
J'ai du mal avec ce runtime props options, il faudrait trouver une meilleure traduction..

2023-06-14 07:57 UTC, edimitchel commented on src/api/utility-types.md
> +Extrait les types de props à partir d'un objet d'options de props au moment de l'exécution. Les types extraits sont destinés à un usage public, c'est-à-dire les props que le parent est autorisé à tra
```suggestion
Extrait les types de props à partir d'un objet d'options de props. Les types extraits sont destinés à un usage public, c'est-à-dire les props que le parent est autorisé à transmettre.
```

2023-06-14 10:22 UTC, tlagoda commented
> J'ai du mal avec ce runtime props options, il faudrait trouver une meilleure traduction..

également, mais honnêtement je vois pas mieux?

2023-06-15 00:19 UTC, edimitchel approved these changes

2023-06-15 00:19 UTC, merged