Translation of reactivity-fundamentals page
vuejs-translations/docs-fr pull request #505
Opened 2023-07-07 14:15 UTC by tisma95

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-07-07 14:50 UTC, edimitchel requested changes
Je remarque un problème qui n'est pas de ton fait, si tu peux t'aligner par rapport à https://github.com/vuejs/docs/blob/main/src/guide/essentials/reactivity-fundamentals.md?plain=1#L13 (l'étoile qui manque) ?

2023-07-07 14:50 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Lorsque vous utilisez une ref dans le modèle et que vous modifiez la valeur de la ref ultérieurement, Vue détecte automatiquement le changement et met à jour le DOM en conséquence. Ceci est possible
```suggestion
Lorsque vous utilisez une ref dans le template et que vous modifiez la valeur de la ref ultérieurement, Vue détecte automatiquement le changement et met à jour le DOM en conséquence. Ceci est possible grâce à un système de réactivité basé sur le suivi des dépendances. Lorsqu'un composant est rendu pour la première fois, Vue **trace** toutes les refs utilisées pendant le rendu. Plus tard, lorsqu'une ref est modifiée, elle **déclenche** un nouveau rendu pour les composants qui la suivent.
```

2023-07-07 14:50 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Les refs peuvent contenir n'importe quel type de valeur, y compris des objets profondément imbriqués, des tableaux ou des structures de données JavaScript intégrées comme `Map`.
```suggestion
Les refs peuvent contenir n'importe quel type de valeur, y compris des objets profondément imbriqués, des tableaux ou des structures de données JavaScript natives comme `Map`.
```

2023-07-07 14:50 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Il existe une autre façon de déclarer un état réactif, avec l'API `reactive()`. Contrairement à une ref qui enveloppe la valeur interne dans un objet spécial, `reactive()` rend un objet lui-même réac
```suggestion
Il existe une autre façon de déclarer un état réactif, avec l'API `reactive()`. Contrairement à une ref qui enveloppe la valeur interne dans un objet spécial, `reactive()` rend un objet lui-même réactif :
```

2023-07-07 14:50 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +> Voir aussi: [Typer reactive()](/guide/typescript/composition-api#typing-reactive) <sup class="vt-badge ts" />
```suggestion
> Voir aussi : [Typer reactive()](/guide/typescript/composition-api#typing-reactive) <sup class="vt-badge ts" />
```

2023-07-07 14:50 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Utilisation dans template:
```suggestion
Utilisation dans le template :
```

2023-07-07 14:50 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Une ref est automatiquement déballée lorsqu'elle est accédée ou mutée en tant que propriété d'un objet réactif. En d'autres termes, elle se comporte comme une propriété normale:
```suggestion
Une ref est automatiquement déballée lorsqu'elle est accédée ou mutée en tant que propriété d'un objet réactif. En d'autres termes, elle se comporte comme une propriété normale :
```

2023-07-07 14:50 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Si une nouvelle ref est attribuée à une propriété liée à une ref existante, elle remplacera l'ancienne ref:
```suggestion
Si une nouvelle ref est attribuée à une propriété liée à une ref existante, elle remplacera l'ancienne ref :
```

2023-07-07 14:50 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Contrairement aux objets réactifs, il n'y a **pas** de déballage effectué lorsque la ref est accédée en tant qu'élément d'un tableau réactif ou d'un type de collection natif comme `Map`:
```suggestion
Contrairement aux objets réactifs, il n'y a **pas** de déballage effectué lorsque la ref est accédée en tant qu'élément d'un tableau réactif ou d'un type de collection natif comme `Map` :
```

2023-07-07 14:50 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Dans l'exemple ci-dessous, `count` et `object` sont des propriétés de premier niveau, mais `object.id` ne l'est pas:
```suggestion
Dans l'exemple ci-dessous, `count` et `object` sont des propriétés de premier niveau, mais `object.id` ne l'est pas :
```

2023-07-07 14:50 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Cette expression fonctionne donc comme prévu:
```suggestion
Cette expression fonctionne donc comme prévu :
```

2023-07-07 14:50 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +...alors que celui-ci ne le fait **PAS**:
```suggestion
...alors que celui-ci ne le fait **PAS** :
```

2023-07-07 14:50 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Le résultat rendu sera `[object Object]1` car `object.id` n'est pas décompressé lors de l'évaluation de l'expression et reste un objet ref. Pour résoudre ce problème, nous pouvons déstructurer `id` e
```suggestion
Le résultat rendu sera `[object Object]1` car `object.id` n'est pas déballé lors de l'évaluation de l'expression et reste un objet ref. Pour résoudre ce problème, nous pouvons déstructurer `id` en une propriété de premier niveau :
```

2023-07-07 14:50 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Une autre chose à noter est qu'une ref est déballée s'il s'agit de la valeur finale évaluée d'une interpolation de texte (c'est-à-dire une balise <code v-pre>{{ }}</code>), donc ce qui suit rendra `1
```suggestion
Une autre chose à noter est qu'une ref est déballée s'il s'agit de la valeur finale évaluée d'une interpolation de texte (c'est-à-dire une balise <code v-pre>{{ }}</code>), donc ce qui suit rendra `1` :
```

2023-07-07 14:50 UTC, edimitchel commented on src/guide/essentials/reactivity-fundamentals.md
> +Une ref rendra sa valeur profondément réactive. Cela signifie que vous pouvez vous attendre à ce que les changements soient détectés même lorsque vous mutez des objets imbriqués ou des tableaux:
```suggestion
Une ref rendra sa valeur profondément réactive. Cela signifie que vous pouvez vous attendre à ce que les changements soient détectés même lorsque vous mutez des objets imbriqués ou des tableaux :
```

2023-07-07 14:59 UTC, edimitchel requested changes

2023-07-07 14:59 UTC, edimitchel commented on src/guide/typescript/composition-api.md
> +L'argument du type peut être l'un des suivants:
```suggestion
L'argument du type peut être l'un des suivants :
```

2023-07-07 15:43 UTC, tisma95 commented
> Je remarque un problème qui n'est pas de ton fait, si tu peux t'aligner par rapport à https://github.com/vuejs/docs/blob/main/src/guide/essentials/reactivity-fundamentals.md?plain=1#L13 (l'étoile qui manque) ?

C'est bon @edimitchel  c'est fait.

2023-07-09 21:39 UTC, edimitchel commented
Il y a encore quelques commentaires non pris en compte

2023-07-11 14:18 UTC, edimitchel approved these changes

2023-07-11 21:43 UTC, tlagoda reviewed
Je t'ai indiqué les espaces manquants devant les ":".
Sinon très bon boulot, merci pour ton contribution! 👍

2023-07-11 21:43 UTC, tlagoda commented on src/guide/essentials/reactivity-fundamentals.md
> +`reactive()` convertit l'objet en profondeur: les objets imbriqués sont également enveloppés par `reactive()` lorsqu'on y accède. Il est également appelé par `ref()` en interne lorsque la valeur de r
```suggestion
`reactive()` convertit l'objet en profondeur : les objets imbriqués sont également enveloppés par `reactive()` lorsqu'on y accède. Il est également appelé par `ref()` en interne lorsque la valeur de ref est un objet. Comme pour les refs peu profondes, il existe aussi l'API [`shallowReactive()`](/api/reactivity-advanced#shallowreactive) pour choisir de ne pas utiliser la réactivité profonde.
```

2023-07-11 21:43 UTC, tlagoda commented on src/guide/typescript/composition-api.md
> +// 3.3+: syntaxe alternative, plus succincte
```suggestion
// 3.3+ : syntaxe alternative, plus succincte
```

2023-07-13 14:44 UTC, edimitchel approved these changes

2023-07-13 14:53 UTC, merged