Update README.md
vuejs-translations/docs-fr pull request #507
Opened 2023-07-07 15:17 UTC by tisma95

translate the requirement node version note

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-07-09 21:38 UTC, edimitchel requested changes

2023-07-09 21:38 UTC, edimitchel commented on README.md
> +Ce projet nécessite que Node.js `v14.0.0` ou plus récent, car nous utilisons de nouvelles fonctionnalités JavaScript dans notre code, telles que le chaînage optionnel..
```suggestion
Ce projet nécessite Node.js la version `v14.0.0` ou plus récent, car nous utilisons de nouvelles fonctionnalités JavaScript dans notre code, telles que le chaînage optionnel..
```

2023-07-10 20:43 UTC, edimitchel requested changes

2023-07-10 20:43 UTC, edimitchel commented on README.md
> +Ce projet nécessite Node.js la version `v14.0.0` ou plus récent, car nous utilisons de nouvelles fonctionnalités JavaScript dans notre code, telles que le chaînage optionnel..
```suggestion
Ce projet nécessite la version `v14.0.0` ou plus récent de Node.js, car nous utilisons de nouvelles fonctionnalités JavaScript dans notre code, telles que le chaînage optionnel..
```
J'etais pas juste dans ma suggestion mais la tienne ne va pas non plus.

2023-07-10 21:15 UTC, tlagoda commented on README.md
> +Ce projet nécessite Node.js la version `v14.0.0` ou plus récent, car nous utilisons de nouvelles fonctionnalités JavaScript dans notre code, telles que le chaînage optionnel..
```suggestion
Ce projet nécessite la version `v14.0.0` ou une version plus récente de Node.js, car nous utilisons de nouvelles fonctionnalités JavaScript dans notre code, telles que le chaînage optionnel..
```

2023-07-11 13:50 UTC, edimitchel approved these changes

2023-07-11 13:51 UTC, merged