docs(faq): remove outdated information about considering to use vue 2
vuejs-translations/docs-fr pull request #517
Opened 2023-07-18 19:56 UTC by tisma95

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-07-18 21:30 UTC, edimitchel requested changes

2023-07-18 21:30 UTC, edimitchel commented on src/guide/components/props.md
> +  //  (les valeurs`null` et `undefined` autoriseront tous les types)
```suggestion
  //  (les valeurs `null` et `undefined` autoriseront tous les types)
```

2023-07-18 21:34 UTC, edimitchel commented
Pour info, tu peux désormais créer les branches directement sur le projet au lieu de le faire depuis ton fork ;)

2023-07-24 09:54 UTC, tlagoda submitted a review, later dismissed
👏

2023-07-24 09:54 UTC, tlagoda commented on src/glossary/index.md
> +Vue Router dispose d'une fonctionnalité similaire pour la fonction [chargement paresseux du composant route](https://router.vuejs.org/guide/advanced/lazy-loading.html), bien que cela n'utilise pas la
```suggestion
Vue Router dispose d'une fonctionnalité similaire pour le [chargement paresseux du composant route](https://router.vuejs.org/guide/advanced/lazy-loading.html), bien que cela n'utilise pas la fonctionnalité de composants asynchrones de Vue.
```

2023-07-26 07:20 UTC, edimitchel commented on src/guide/components/props.md
> +  //  (les valeurs`null` et `undefined` autoriseront tous les types)
@tisma95 merci de prendre en compte ce commentaire :)

2023-07-26 20:31 UTC, edimitchel approved these changes

2023-07-26 20:31 UTC, merged