docs(glossary): translate composition API
vuejs-translations/docs-fr pull request #530
Opened 2023-07-21 15:59 UTC by tisma95

Issues:https://github.com/vuejs-translations/docs-fr/issues/529 English Version: https://vuejs.org/glossary/#composition-api
<img width="875" alt="Capture d’écran 2023-07-21 à 17 55 14" src="https://github.com/vuejs-translations/docs-fr/assets/55036198/e39b62f8-a434-47fa-95e8-f62aa6a733ad">

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-07-24 07:53 UTC, edimitchel requested changes

2023-07-24 07:53 UTC, edimitchel commented on src/glossary/index.md
> +L'*API de Composition* est une collection de fonctions utilisées pour écrire des composants et des composables dans Vue.
```suggestion
La '*Composition API* est une collection de fonctions utilisées pour écrire des composants et des composables dans Vue.
```

2023-07-24 07:53 UTC, edimitchel commented on src/glossary/index.md
> +Le terme est également utilisé pour décrire l'un des deux styles principaux utilisés pour écrire des composants, l'autre étant l'[API Options](#options-api). Les composants écrits à l'aide de l'API C
```suggestion
Le terme est également utilisé pour décrire l'un des deux styles principaux utilisés pour écrire des composants, l'autre étant l'[Options API](#options-api). Les composants écrits à l'aide de la Composition API utilisent soit `<script setup>`, soit une fonction explicite `setup()`.
```

2023-07-24 07:53 UTC, edimitchel commented on src/glossary/index.md
> +Voir la [FAQ de l'API de Composition](/guide/extras/composition-api-faq) pour plus de détails.
```suggestion
Voir la [FAQ de la Composition API](/guide/extras/composition-api-faq) pour plus de détails.
```

2023-07-25 19:39 UTC, tisma95 commented on src/glossary/index.md
> +L'*API de Composition* est une collection de fonctions utilisées pour écrire des composants et des composables dans Vue.
Hello @edimitchel,
J'aurai dis pareil comme toi mais en regardant la doc je me suis rendu compte qu'il utilisait le terme API de composition comme ci-joint c'est pour rester cohérent que j'ai utilisé le même terme.
https://fr.vuejs.org/guide/introduction.html#api-styles
![image](https://github.com/vuejs-translations/docs-fr/assets/55036198/e46c0fe2-137f-487d-bd1b-b99c785ea754)

2023-07-25 19:39 UTC, tisma95 commented on src/glossary/index.md
> +Le terme est également utilisé pour décrire l'un des deux styles principaux utilisés pour écrire des composants, l'autre étant l'[API Options](#options-api). Les composants écrits à l'aide de l'API C
Commentaire pareil que précédent

2023-07-25 19:39 UTC, tisma95 commented on src/glossary/index.md
> +Voir la [FAQ de l'API de Composition](/guide/extras/composition-api-faq) pour plus de détails.
Commentaire pareil que précédent

2023-07-26 07:19 UTC, edimitchel commented on src/glossary/index.md
> +L'*API de Composition* est une collection de fonctions utilisées pour écrire des composants et des composables dans Vue.
Alors c'est une erreur ou un oubli, tu peux aligner là où c'est différent.
On garde Composition API / Options API

2023-07-26 07:24 UTC, edimitchel commented on src/glossary/index.md
> +L'*API de Composition* est une collection de fonctions utilisées pour écrire des composants et des composables dans Vue.
Pour le coup, c'était les premiers contenus traduits et la règle n'avait pas encore été établie, et on a oublié d'aligner

2023-07-26 15:03 UTC, tisma95 commented on src/glossary/index.md
> +L'*API de Composition* est une collection de fonctions utilisées pour écrire des composants et des composables dans Vue.
Pas de soucis merci pour la confirmation.

2023-07-26 20:42 UTC, edimitchel requested changes

2023-07-26 20:42 UTC, edimitchel commented on src/glossary/index.md
> +## API de Composition {#composition-api}
```suggestion
## Composition API {#composition-api}
```

2023-07-26 22:36 UTC, edimitchel commented on src/glossary/index.md
> +La '*Composition API* est une collection de fonctions utilisées pour écrire des composants et des composables dans Vue.
```suggestion
La *Composition API* est une collection de fonctions utilisées pour écrire des composants et des composables dans Vue.
```

2023-07-26 22:36 UTC, edimitchel approved these changes

2023-07-26 22:40 UTC, merged