docs(glossary): translate custom element #542
vuejs-translations/docs-fr pull request #544
Opened 2023-07-29 14:36 UTC by tisma95

custom element #542

https://github.com/vuejs-translations/docs-fr/issues/542

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

Je viens de voir sur la page de la doc des Web Component on utilise en français le mot Web Component https://fr.vuejs.org/guide/extras/web-components.html qui a un lien avec la page de MDN https://developer.mozilla.org/fr/docs/Web/API/Web_components qui lui utilise le terme Composants web selon vous @edimitchel / @tlagoda  quel terme nous utilisons Web Component comme en anglais ou Composant Web ?

Merci

2023-07-29 15:26 UTC, edimitchel commented
> @edimitchel / @tlagoda quel terme nous utilisons Web Component comme en anglais ou Composant Web ?

Alors ça dépend.
On a effectivement utilisé Web Components car ça reste un terme assez technique et souvent appelé comme ça oralement.
Sinon, il y a les Custom elements qui eux sont traduits Éléments personnalisés

2023-07-29 15:48 UTC, tisma95 commented
> > @edimitchel / @tlagoda quel terme nous utilisons Web Component comme en anglais ou Composant Web ?
> 
> Alors ça dépend. On a effectivement utilisé Web Components car ça reste un terme assez technique et souvent appelé comme ça oralement. Sinon, il y a les Custom elements qui eux sont traduits Éléments personnalisés

Pas de soucis merci on garde alors Web Components

2023-07-30 13:07 UTC, tlagoda reviewed
Voici quelques propositions; mais sinon ta trad me semble OK, bien noué!

2023-07-30 13:07 UTC, tlagoda commented on src/glossary/index.md
> +Un élément personnalisé est une caractéristique de la norme des [Web Components](#web-component), qui est mise en œuvre dans les navigateurs web modernes. Il s'agit de la possibilité d'utiliser un él
```suggestion
Un élément personnalisé est une fonctionnalité de la norme des [Web Components](#web-component), qui est mise en œuvre dans les navigateurs web modernes. Il s'agit de la possibilité d'utiliser un élément HTML personnalisé dans votre balisage HTML pour inclure un composant Web à cet endroit de la page.
```

2023-07-30 13:07 UTC, tlagoda commented on src/glossary/index.md
> +Vue dispose d'un support intégré pour le rendu des éléments personnalisés et permet de les utiliser directement dans les templates de composants Vue.
```suggestion
Vue prend en charge nativement le rendu des éléments personnalisés et permet de les utiliser directement dans les templates de composants Vue.
```

Proposition, à toi de voir!

2023-08-04 07:45 UTC, edimitchel requested changes

2023-08-04 07:45 UTC, edimitchel commented on src/glossary/index.md
> +Un élément personnalisé est une fonctionnalité de la norme des [Web Components](#web-component), qui est mise en œuvre dans les navigateurs web modernes. Il s'agit de la possibilité d'utiliser un élé
```suggestion
Un *élément personnalisé* est une fonctionnalité de la norme des [Web Components](#web-component), qui est mise en œuvre dans les navigateurs web modernes. Il s'agit de la possibilité d'utiliser un élément HTML personnalisé dans votre balisage HTML pour inclure un Web Component à cet endroit de la page.
```

2023-08-04 07:45 UTC, edimitchel commented on src/glossary/index.md
> +Les éléments personnalisés ne doivent pas être confondus avec la possibilité d'inclure des composants Vue en tant que balises dans le template d'un autre composant Vue. Les éléments personnalisés son
```suggestion
Les éléments personnalisés ne doivent pas être confondus avec la possibilité d'inclure des composants Vue en tant que balises dans le template d'un autre composant Vue. Les éléments personnalisés sont utilisés pour créer des Web Components, et non des composants Vue.
```

2023-08-04 21:22 UTC, edimitchel approved these changes

2023-08-04 21:22 UTC, merged