docs(inject): translate #546
vuejs-translations/docs-fr pull request #547
Opened 2023-07-29 15:02 UTC by tisma95

http://localhost:5173/guide/components/provide-inject.html#inject Translate missing translation in Composition API inject #546

https://github.com/vuejs-translations/docs-fr/issues/546

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-07-29 15:28 UTC, edimitchel requested changes

2023-07-29 15:28 UTC, edimitchel commented on src/guide/components/provide-inject.md
> +Le troisième paramètre indique la valeur par défaut à traiter comme une fonction d'usine.
```suggestion
Le troisième paramètre indique la valeur par défaut à traiter comme une fonction _factory_.
```

On a utilisé factory car ça fait penser au design pattern qui lui n'est habituellement pas traduit.

2023-07-30 13:03 UTC, tlagoda approved these changes

2023-07-30 20:20 UTC, edimitchel approved these changes

2023-07-30 20:20 UTC, merged