docs(glossary): component
vuejs-translations/docs-fr pull request #579
Opened 2023-08-12 21:57 UTC by edimitchel

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages

2023-08-17 10:43 UTC, tisma95 requested changes
good pour moi juste ``

2023-08-17 11:17 UTC, edimitchel commented
> good pour moi juste `` 

Càd où ça?

2023-08-17 12:04 UTC, tisma95 commented
> > good pour moi juste `` 
> 
> Càd où ça?

J'ai fait la modification dans le commit 22abe178e61f47856f7f5e01f2e5eb3a88ace3c3

2023-08-18 20:32 UTC, edimitchel commented
Merci @tisma95, la prochaine fois tu peux proposer une suggestion en commentaire.
CTRL(ou CMD) + G et modifier selon ce que tu veux proposer.

2023-08-18 20:32 UTC, merged