docs(menu): translate the menu header #580
vuejs-translations/docs-fr pull request #581
Opened 2023-08-14 21:47 UTC by tisma95

https://github.com/vuejs-translations/docs-fr/issues/580

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-08-14 21:55 UTC, edimitchel requested changes
T'en penses quoi @tlagoda ?

2023-08-14 21:55 UTC, edimitchel commented on .vitepress/config.ts
> +      text: 'Mise à l\'échelle',
Pas fan de la traduction.

Scaling up fait référence à montée en charge dans un environnement d'infrastructures informatique.
Mais là c'est plutôt une histoire de monter en difficulté d'apprentissage.

Du coup je dirai plutôt :


```suggestion
      text: 'Approfondir',
```

2023-08-14 21:59 UTC, tisma95 commented on .vitepress/config.ts
> +      text: 'Mise à l\'échelle',
Pas de soucis merci pour ta proposition j'ai eu des doutes concernant le bon terme je voulais aussi avoir votre avis sur le terme le mieux adapté Approfondir.

2023-08-15 21:33 UTC, edimitchel approved these changes

2023-08-15 21:33 UTC, merged