601 hoisting
vuejs-translations/docs-fr pull request #603
Opened 2023-09-02 09:36 UTC by tisma95

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

J'ai gardé le terme **hoisting** j'ai vu que dans la documentation de vue https://fr.vuejs.org/guide/extras/rendering-mechanism.html#static-hoisting on utilise le terme **Hissage** à voir si on veut remplacer dans le glossaire **hoisting** par **hissage**.

Merci

2023-09-03 21:54 UTC, edimitchel requested changes

2023-09-03 21:54 UTC, edimitchel commented on src/glossary/index.md
> +Le terme *hoisting* est utilisé pour décrire l'exécution d'une section de code avant qu'elle ne soit atteinte, avant d'autres codes. L'exécution est 'tirée vers le haut' à un point antérieur.
Je sais qu'on peut dire en français hissage pour _hoisting_, qu'en penses-tu ?
Sinon, mettre en italique le terme non traduit

2023-09-03 21:54 UTC, edimitchel commented on src/glossary/index.md
> +Dans le contexte de Vue, le compilateur de template applique le *static hoisting* pour améliorer les performances. Lors de la conversion d'un modèle en fonction de rendu, les VNodes correspondant au
```suggestion
Dans le contexte de Vue, le compilateur de template applique le *static hoisting* pour améliorer les performances. Lors de la conversion d'un template en fonction de rendu, les VNodes correspondant au contenu statique peuvent être créés une fois et réutilisés. Ces VNodes statiques sont décrits comme hissés parce qu'ils sont créés en dehors de la fonction de rendu, avant qu'elle ne s'exécute. Une forme similaire de hoisting est appliquée aux objets statiques ou aux tableaux générés par le compilateur de template.
```

2023-09-03 21:54 UTC, edimitchel commented on src/glossary/index.md
> +- [Guide - Mécanismes de rendu - Hissage statique](/guide/extras/rendering-mechanism.html#static-hoisting)
On avait effectivement utiliser le terme hissage, merci de garder ce terme là, quite à garder la traduction en anglais entre parenthèse

2023-09-03 21:58 UTC, tlagoda approved these changes
Mis à part les commentaires laissés par @edimitchel, je valide!

2023-09-06 19:12 UTC, edimitchel requested changes

2023-09-06 19:12 UTC, edimitchel commented on src/glossary/index.md
> +## hissage {#hoisting}
```suggestion
## hissage (ou _hoisting)_ {#hoisting}
```

2023-09-06 20:04 UTC, tlagoda commented
Si tu peux/veux, tu peux t'occuper des 2 issues qui me sont assignées je n'aurais pas l'occasion de les traiter prochainement
Bien joué pour ton travail 👍

2023-09-06 20:05 UTC, tlagoda submitted a review, later dismissed

2023-09-06 20:37 UTC, edimitchel requested changes

2023-09-06 20:37 UTC, edimitchel commented on src/glossary/index.md
> +## hissage (ou _hoisting)_ {#hoisting}
```suggestion
## hissage (ou _hoisting_) {#hoisting}
```

Pardon j'ai fait une faute

2023-09-08 20:29 UTC, edimitchel approved these changes

2023-09-08 20:29 UTC, merged