611 provide inject
vuejs-translations/docs-fr pull request #612
Opened 2023-09-06 19:40 UTC by tisma95

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-09-06 19:56 UTC, tlagoda submitted a review, later dismissed

2023-09-06 19:56 UTC, tlagoda commented on src/glossary/index.md
> +`provide` et `inject` sont parfois utilisés pour éviter le *prop drilling*. Ils peuvent également être utilisés comme un moyen implicite pour un composant de communiquer avec le contenu de son slot.
```suggestion
`provide` et `inject` sont parfois utilisées pour éviter le *prop drilling*. Elles peuvent également être utilisées comme un moyen implicite pour un composant de communiquer avec le contenu de son slot.
```

J'aurais mis au féminin comme c'est des fonctions

2023-09-06 19:56 UTC, tlagoda commented on src/glossary/index.md
> +`provide` peut également être utilisé au niveau de l'application, en rendant une valeur disponible pour tous les composants de cette application.
```suggestion
`provide` peut également être utilisée au niveau de l'application, en rendant une valeur disponible pour tous les composants de cette application.
```

2023-09-06 20:20 UTC, tisma95 commented on src/glossary/index.md
> +`provide` et `inject` sont parfois utilisés pour éviter le *prop drilling*. Ils peuvent également être utilisés comme un moyen implicite pour un composant de communiquer avec le contenu de son slot.
Possible qu'en penses tu @edimitchel ?

2023-09-06 20:21 UTC, tisma95 commented on src/glossary/index.md
> +`provide` peut également être utilisé au niveau de l'application, en rendant une valeur disponible pour tous les composants de cette application.
Possible qu'en penses tu @edimitchel  ?

2023-09-06 20:44 UTC, edimitchel commented on src/glossary/index.md
> +`provide` et `inject` sont parfois utilisés pour éviter le *prop drilling*. Ils peuvent également être utilisés comme un moyen implicite pour un composant de communiquer avec le contenu de son slot.
J'ai un autre avis

2023-09-06 20:46 UTC, edimitchel requested changes

2023-09-06 20:46 UTC, edimitchel commented on src/glossary/index.md
> +`provide` et `inject` sont parfois utilisés pour éviter le *prop drilling*. Ils peuvent également être utilisés comme un moyen implicite pour un composant de communiquer avec le contenu de son slot.
```suggestion
`provide` et `inject` sont un moyen parfois utilisé pour éviter le *prop drilling* ou également de manière implicite pour un composant de communiquer avec le contenu de son slot.
```

2023-09-06 20:47 UTC, tlagoda commented on src/glossary/index.md
> +`provide` et `inject` sont parfois utilisés pour éviter le *prop drilling*. Ils peuvent également être utilisés comme un moyen implicite pour un composant de communiquer avec le contenu de son slot.
ça ne se mouille pas 😛

2023-09-08 20:29 UTC, edimitchel approved these changes

2023-09-08 20:30 UTC, merged