632 reactive effect
vuejs-translations/docs-fr pull request #633
Opened 2023-09-13 20:16 UTC by tisma95

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-09-13 20:25 UTC, edimitchel requested changes

2023-09-13 20:25 UTC, edimitchel commented on src/glossary/index.md
> +Le terme est dérivé de 'effet secondaire'. L'appel à la fonction d'effet est un effet secondaire de la modification de la valeur de la propriété.
```suggestion
Le terme est dérivé de 'effet de bord'. L'appel à la fonction d'effet est un effet de bord de la modification de la valeur de la propriété.
```

2023-09-16 07:52 UTC, tlagoda reviewed
Ok pour @edimitchel 
Beau boulot!

2023-09-17 17:00 UTC, edimitchel approved these changes

2023-09-17 17:00 UTC, merged