640 ref
vuejs-translations/docs-fr pull request #641
Opened 2023-09-17 14:24 UTC by tisma95

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-09-17 17:03 UTC, edimitchel requested changes

2023-09-17 17:03 UTC, edimitchel commented on src/glossary/index.md
> +> Cette entrée concerne l'utilisation de `ref` pour la réactivité. Pour l'attribut `ref` utilisé dans les templates, voir plutôt [ref de template](#template-ref).
```suggestion
> Ceci concerne l'utilisation de `ref` pour la réactivité. Pour l'attribut `ref` utilisé dans les templates, voir plutôt [ref de template](#template-ref).
```

2023-09-17 17:03 UTC, edimitchel commented on src/glossary/index.md
> +Un `ref` fait partie du système de réactivité de Vue. C'est un objet avec une seule propriété réactive, appelée `value`.
```suggestion
Une `ref` fait partie du système de réactivité de Vue. C'est un objet avec une seule propriété réactive, appelée `value`.
```

Penser une référence

2023-09-17 18:31 UTC, tlagoda commented on src/glossary/index.md
> +> Cette entrée concerne l'utilisation de `ref` pour la réactivité. Pour l'attribut `ref` utilisé dans les templates, voir plutôt [ref de template](#template-ref).
On peut carrément traduire "Nous parlons ici de l'utilisation..."

2023-09-17 18:32 UTC, tlagoda requested changes

2023-09-17 18:32 UTC, tlagoda commented on src/glossary/index.md
> +Il existe différents types de ref. Par exemple, les refs peuvent être créés en utilisant `ref()`, `shallowRef()`, `computed()`, et `customRef()`. La fonction `isRef()` peut être utilisée pour vérifie
```suggestion
Il existe différents types de ref. Par exemple, les refs peuvent être créées en utilisant `ref()`, `shallowRef()`, `computed()`, et `customRef()`. La fonction `isRef()` peut être utilisée pour vérifier si un objet est une ref, et `isReadonly()` peut être utilisée pour vérifier si la ref permet la réaffectation directe de sa valeur.
```

2023-09-17 22:12 UTC, edimitchel commented on src/glossary/index.md
> +> Cette entrée concerne l'utilisation de `ref` pour la réactivité. Pour l'attribut `ref` utilisé dans les templates, voir plutôt [ref de template](#template-ref).
très clairement oui

2023-09-19 14:08 UTC, edimitchel commented on src/glossary/index.md
> +> Cette entrée concerne l'utilisation de `ref` pour la réactivité. Pour l'attribut `ref` utilisé dans les templates, voir plutôt [ref de template](#template-ref).
@tisma95 tu peux prendre la suggestion de Thibaut?

2023-09-20 16:31 UTC, edimitchel approved these changes

2023-09-22 06:41 UTC, tlagoda approved these changes

2023-09-22 06:41 UTC, merged