644 side effect
vuejs-translations/docs-fr pull request #645
Opened 2023-09-17 14:58 UTC by tisma95

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-09-17 17:13 UTC, edimitchel approved these changes

2023-09-17 17:13 UTC, edimitchel commented on src/glossary/index.md
> +Par exemple, dans le contexte du réglage d'une propriété comme `user.name = null`, on s'attend à ce que cela change la valeur de `user.name`. Si cela fait aussi quelque chose d'autre, comme déclenche
```suggestion
Par exemple, lors de l'affectation d'une propriété comme `user.name = null`, on s'attend à ce que cela change la valeur de `user.name`. Si cela fait aussi quelque chose d'autre, comme déclencher le système de réactivité de Vue, alors cela sera décrit comme un effet de bord. C'est l'origine du terme [effet réactif](#reactive-effect) dans Vue.
```

2023-09-17 17:13 UTC, edimitchel requested changes
Commentaire laissé

2023-09-19 19:24 UTC, edimitchel approved these changes

2023-09-22 06:40 UTC, tlagoda approved these changes
Beau boulot @tisma95 👏 
Par contre essaie de resolve les threads quand tu les as pris en compte, ça permet d'y voir plus clair 👍

2023-09-22 07:50 UTC, merged