feat: add vuetoronto23 banner (#646)
vuejs-translations/docs-fr pull request #647
Opened 2023-09-19 08:21 UTC by edimitchel

resolves #646
Cherry picked from https://github.com/vuejs/docs/commit/eba914e68eacceab35826e4aa8d017c80ad0ab49

2023-09-20 16:28 UTC, edimitchel commented on .vitepress/theme/components/Banner.vue
> +        >Register <span class="vt-time-now">Now</span></a
```suggestion
      <span class="vt-text-primary">VueConf Toronto</span>
      <span class="vt-tagline"> - Rejoignez la conférence Vue.js</span>
      | 9-10 Nov 2023 <span class="vt-place"> - Toronto, Canada</span>
      <a
        target="_blank"
        class="vt-primary-action"
        href="https://vuetoronto.com?utm_source=vuejs&utm_content=top_banner"
        >S'inscrire <span class="vt-time-now">Maintenant</span></a
```

2023-09-21 06:02 UTC, tlagoda requested changes

2023-09-21 06:02 UTC, tlagoda commented on .vitepress/theme/components/Banner.vue
> +      <span class="vt-text-primary">Use code</span> VUEJS
```suggestion
      <span class="vt-text-primary">Utilisez le code</span> VUEJS
```

2023-09-21 06:02 UTC, tlagoda commented on .vitepress/theme/components/Banner.vue
> +      <span class="vt-text-primary">to get 15% off</span>
```suggestion
      <span class="vt-text-primary">pour obtenir 15% de réduction</span>
```

2023-09-22 06:39 UTC, tlagoda approved these changes

2023-09-22 07:48 UTC, merged