chore: update link like english version #666
vuejs-translations/docs-fr pull request #667
Opened 2023-09-25 17:39 UTC by tisma95

https://github.com/vuejs/docs/commit/643f9cdea0e671bd0bed2718de8ecf72d725725a

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-09-25 20:42 UTC, edimitchel requested changes

2023-09-25 20:42 UTC, edimitchel commented on src/guide/essentials/event-handling.md
> -Le modificateur `.passive` est généralement utilisé avec les écouteurs d'événements de touche pour [améliorer les performances sur les périphériques mobiles](https://developer.mozilla.org/fr/docs/Web
Non on garde les urls vers la doc en français

2023-09-25 20:42 UTC, edimitchel commented on src/guide/essentials/event-handling.md
> -Le modificateur `.passive` est généralement utilisé avec les écouteurs d'événements de touche pour [améliorer les performances sur les périphériques mobiles](https://developer.mozilla.org/fr/docs/Web
À minima juste adapter l'URL si elle n'est plus bonne

2023-09-25 21:52 UTC, tlagoda commented on src/guide/essentials/event-handling.md
> +Le modificateur `.passive` est généralement utilisé avec les écouteurs d'événements de touche pour [améliorer les performances sur les périphériques mobiles](https://developer.mozilla.org/en-US/docs/
Mmmmh, pourquoi tu mets le lien anglais ?

2023-09-26 15:44 UTC, tisma95 commented on src/guide/essentials/event-handling.md
> -Le modificateur `.passive` est généralement utilisé avec les écouteurs d'événements de touche pour [améliorer les performances sur les périphériques mobiles](https://developer.mozilla.org/fr/docs/Web
Du coup la issue n'était pas nécessaire c'est le lien qui a été changé dans la doc.

2023-09-26 15:46 UTC, tisma95 commented on src/guide/essentials/event-handling.md
> +Le modificateur `.passive` est généralement utilisé avec les écouteurs d'événements de touche pour [améliorer les performances sur les périphériques mobiles](https://developer.mozilla.org/en-US/docs/
c'est un changement qui a été fait dans la doc anglaise  après si on garde la page française cette PR n'est pas nécessaire.

2023-09-26 20:21 UTC, edimitchel commented on src/guide/essentials/event-handling.md
> -Le modificateur `.passive` est généralement utilisé avec les écouteurs d'événements de touche pour [améliorer les performances sur les périphériques mobiles](https://developer.mozilla.org/fr/docs/Web
Ça dépend, vérifie si le lien fonctionne bien et que l'ancre existe bien dans 'a version française

2023-09-29 10:51 UTC, tlagoda approved these changes

2023-10-01 17:17 UTC, tisma95 commented on src/guide/essentials/event-handling.md
> -Le modificateur `.passive` est généralement utilisé avec les écouteurs d'événements de touche pour [améliorer les performances sur les périphériques mobiles](https://developer.mozilla.org/fr/docs/Web
Pour moi la version française pointe bien sur le même sujet que la version anglaise je dirai qu'il y'a aucun changement à faire pour cette issue @edimitchel .

2023-10-01 18:09 UTC, edimitchel commented on src/guide/essentials/event-handling.md
> +Le modificateur `.passive` est généralement utilisé avec les écouteurs d'événements de touche pour [améliorer les performances sur les périphériques mobiles](https://developer.mozilla.org/en-US/docs/
À ce moment-là on ferme la pr

2023-10-01 18:09 UTC, closed without merging