673 virtual dom
vuejs-translations/docs-fr pull request #674
Opened 2023-10-01 18:59 UTC by tisma95

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-10-01 19:12 UTC, edimitchel requested changes

2023-10-01 19:12 UTC, edimitchel commented on src/glossary/index.md
> +Chaque fois qu'un composant est redessiné, le nouvel arbre de VNodes est comparé à l'arbre de VNodes précédent et toutes les différences sont alors appliquées au DOM réel. Si rien n'a changé, le DOM
```suggestion
Chaque fois qu'un composant est rerendu, le nouvel arbre de VNodes est comparé à l'arbre de VNodes précédent et toutes les différences sont alors appliquées au DOM réel. Si rien n'a changé, le DOM n'a pas besoin d'être touché.
```

2023-10-02 07:16 UTC, tlagoda commented on src/glossary/index.md
> +Les navigateurs utilisent un arbre de nœuds pour représenter l'état actuel de la page. Cet arbre, et les API JavaScript utilisées pour interagir avec lui, sont appelés *document object model*, ou *DO
```suggestion
Les navigateurs utilisent un arbre de nœuds pour représenter l'état actuel de la page. Cet arbre, et les API JavaScript utilisées pour interagir avec celui-ci, représentent le *document object model*, ou *DOM*.
```

2023-10-02 07:17 UTC, tlagoda commented on src/glossary/index.md
> +Chaque fois qu'un composant est redessiné, le nouvel arbre de VNodes est comparé à l'arbre de VNodes précédent et toutes les différences sont alors appliquées au DOM réel. Si rien n'a changé, le DOM
```suggestion
Chaque fois qu'un composant est rerendu, le nouvel arbre de VNodes est comparé à l'arbre de VNodes précédent et toutes les différences sont alors appliquées au DOM réel. Si rien n'a changé, le DOM n'a pas besoin d'être modifié.
```

2023-10-02 20:14 UTC, edimitchel approved these changes

2023-10-02 20:14 UTC, merged