docs(composable): update restrictions text ##677
vuejs-translations/docs-fr pull request #678
Opened 2023-10-04 15:44 UTC by khylias

**Actions à effectuer :**

- [x] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [x] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [x] Mettre à jour le lien du menu  
  
- [x] Lier la PR à une issue  
      Closes #677
      
Remarques:
A single space was present in line 226. I took the initiative to remove it as other lines.

2023-10-04 20:33 UTC, edimitchel requested changes
Merci pour cette rectification mais je la trouve pour le coup pas idéale.

2023-10-04 20:33 UTC, edimitchel commented on src/guide/reusability/composables.md
> +Les composables ne peuvent être appelés uniquement dans `<script setup>` ou dans le hook `setup()`. Ils ne doivent être appelés que de manière **synchrone** dans ces contextes. Dans certains cas, vou
```suggestion
Les composables ne peuvent être appelés que dans `<script setup>` ou dans le hook `setup()`. Ils ne doivent être appelés que de manière **synchrone** dans ces contextes. Dans certains cas, vous pouvez également les appeler dans des hooks de cycle de vie comme `onMounted()`.
```
Je trouve cette tournure plus simple, tu penses quoi?

2023-10-05 09:55 UTC, khylias commented on src/guide/reusability/composables.md
> +Les composables ne peuvent être appelés uniquement dans `<script setup>` ou dans le hook `setup()`. Ils ne doivent être appelés que de manière **synchrone** dans ces contextes. Dans certains cas, vou
J'ai hésité entre les deux, si ça te semble plus naturel, je vais faire ça.

2023-10-05 10:04 UTC, edimitchel commented on src/guide/reusability/composables.md
> +Les composables ne peuvent être appelés uniquement dans `<script setup>` ou dans le hook `setup()`. Ils ne doivent être appelés que de manière **synchrone** dans ces contextes. Dans certains cas, vou
c'est plus light à lire ma suggestion, je te laisse la commiter :)

2023-10-05 10:06 UTC, edimitchel approved these changes

2023-10-05 10:06 UTC, merged