679 curotec partner update
vuejs-translations/docs-fr pull request #685
Opened 2023-10-11 08:38 UTC by tisma95

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-10-11 09:01 UTC, edimitchel requested changes

2023-10-11 10:17 UTC, edimitchel requested changes

2023-10-11 10:17 UTC, edimitchel commented on src/partners/partners.json
> +    "intro": "Travaillez avec une équipe qui comprend Vue.js de fond en comble. Les équipes de SaaS et d'entreprises font appel à Curotec pour des services d'exécution de projets et de renforcement d
Premier ordre pourrait être reformulé

2023-10-11 13:33 UTC, tisma95 commented on src/partners/partners.json
> +    "intro": "Travaillez avec une équipe qui comprend Vue.js de fond en comble. Les équipes de SaaS et d'entreprises font appel à Curotec pour des services d'exécution de projets et de renforcement d
As tu une idée ?

2023-10-11 13:37 UTC, edimitchel requested changes

2023-10-11 13:37 UTC, edimitchel commented on src/partners/partners.json
> +    "intro": "Travaillez avec une équipe qui comprend Vue.js de fond en comble. Les équipes de SaaS et d'entreprises font appel à Curotec pour des services d'exécution de projets et de renforcement d
```suggestion
    "intro": "Travaillez avec une équipe qui comprend Vue.js de fond en comble. Les équipes de SaaS et d'entreprises font appel à Curotec pour des services d'exécution de projets et de renforcement des développeurs Vue.js spécialisés.",
```

2023-10-11 20:40 UTC, tlagoda commented on src/partners/partners.json
> +    "intro": "Travaillez avec une équipe qui comprend Vue.js de fond en comble. Les équipes de SaaS et d'entreprises font appel à Curotec pour des services d'exécution de projets et de renforcement d
De qualité ?

2023-10-11 20:42 UTC, tlagoda commented on src/partners/partners.json
> +      "Nous disposons d'un modèle à tous les niveaux, avec des membres de l'équipe aux États-Unis, en Amérique latine et en Asie du Sud. Nous créerons un engagement flexible pour vos besoins en fonct
"Nous créerons un engagement flexible" me semble bizarre.
Je dirai "Nous nous engagerons de manière flexible", qu'en penses-tu?

2023-10-11 20:42 UTC, tlagoda commented on src/partners/partners.json
> +    "region": ["North America", "Latin America"],
à traduire ?

2023-10-11 20:43 UTC, tlagoda reviewed
Quelques retours sinon gg 👍

2023-10-15 14:23 UTC, tisma95 commented on src/partners/partners.json
> +      "Nous disposons d'un modèle à tous les niveaux, avec des membres de l'équipe aux États-Unis, en Amérique latine et en Asie du Sud. Nous créerons un engagement flexible pour vos besoins en fonct
Pas mal

2023-10-15 14:25 UTC, tisma95 commented on src/partners/partners.json
> +    "region": ["North America", "Latin America"],
Bien vu !

2023-10-15 14:37 UTC, edimitchel approved these changes

2023-10-15 14:38 UTC, merged