851 srcapisfc script setupmd
vuejs-translations/docs-fr pull request #852
Opened 2023-12-30 14:19 UTC by tisma95

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-12-30 21:59 UTC, tlagoda commented on src/api/sfc-script-setup.md
> +// OU: déclare la prop "modelValue" avec des options
```suggestion
// OU : déclare la prop "modelValue" avec des options
```

2023-12-30 21:59 UTC, tlagoda commented on src/api/sfc-script-setup.md
> +// OU: déclare la prop "count" avec des options
```suggestion
// OU : déclare la prop "count" avec des options
```

2023-12-30 22:00 UTC, tlagoda commented on src/api/sfc-script-setup.md
> +  // get() est omis car il n'est pas nécessaire ici
j'aurais mis get() au féminin, t'en penses quoi?

2023-12-30 22:00 UTC, tlagoda commented on src/api/sfc-script-setup.md
> +    // sinon, renvoyer la valeur telle quelle
```suggestion
    // sinon, renvoie la valeur telle quelle
```

2023-12-30 22:01 UTC, tlagoda commented on src/api/sfc-script-setup.md
> +// modèle par défaut avec options, les valeurs requises suppriment les valeurs indéfinies possibles
```suggestion
// modèle par défaut avec options, les valeurs requises suppriment les possibles valeurs indéfinies
```

2023-12-30 22:01 UTC, tlagoda requested changes
Quelques ajustements, mais bien joué à toi! 💪

2023-12-30 22:04 UTC, edimitchel requested changes

2023-12-31 16:11 UTC, tlagoda approved these changes

2024-01-01 22:32 UTC, edimitchel approved these changes

2024-01-01 22:32 UTC, merged