853 srcapicompile time flagsmd
vuejs-translations/docs-fr pull request #854
Opened 2023-12-30 14:53 UTC by tisma95

**Actions à effectuer :**

- [ ] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [ ] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [ ] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:

2023-12-30 22:14 UTC, edimitchel requested changes
Merci d'affecter les changements liés à cette traduction.
Dans le menu, j'ai employé une autre traduction que tu peux modifier également.

2023-12-30 22:14 UTC, edimitchel commented on src/api/compile-time-flags.md
> +# Indicateurs de temps de compilation {#compile-time-flags}
```suggestion
# Drapeaux pour la compilation {#compile-time-flags}
```

ou

```suggestion
# Indicateurs à la compilation {#compile-time-flags}
```

J'ai une préférence pour la seconde option.
Il faudrait faire une passe sur toutes les traductions liés à flags pour bien homogénéiser.
Merci d'appliquer les changements plus bas

2023-12-30 22:14 UTC, edimitchel commented on src/api/compile-time-flags.md
> +Lorsque l'on utilise Vue avec une étape de construction, il est possible de configurer un certain nombre d'indicateurs de compilation pour activer/désactiver certaines fonctionnalités. L'avantage de
```suggestion
Lorsque l'on utilise Vue avec des outils de build, il est possible de configurer un certain nombre d'indicateurs à la compilation pour activer/désactiver certaines fonctionnalités. L'avantage de l'utilisation des indicateurs à la compilation est que les fonctionnalités désactivées de cette manière peuvent être supprimées du paquet final via le *tree-shaking*.
```

2023-12-30 22:14 UTC, edimitchel commented on src/api/compile-time-flags.md
> +`@vitejs/plugin-vue` fournit automatiquement des valeurs par défaut pour ces indicateurs. Pour changer les valeurs par défaut, utilisez l'option de configuration [`define` option de configuration](ht
```suggestion
`@vitejs/plugin-vue` fournit automatiquement des valeurs par défaut pour ces indicateurs. Pour changer les valeurs par défaut, utilisez [l'option de configuration `define`](https://vitejs.dev/config/shared-options.html#define) de Vite :
```

2023-12-30 22:14 UTC, edimitchel commented on src/api/compile-time-flags.md
> +    // activer les détails de l'inadéquation de l'hydratation dans la version de production
```suggestion
    // activer les détails d'incohérences lors de l'hydratation dans la version de production
```

2023-12-30 22:19 UTC, tlagoda commented on src/api/compile-time-flags.md
> +- **Par défaut:** `false`
```suggestion
- **Par défaut :** `false`
```

2023-12-30 22:20 UTC, tlagoda commented on src/api/compile-time-flags.md
> +Lorsque l'on utilise Vue avec une étape de construction, il est possible de configurer un certain nombre d'indicateurs de compilation pour activer/désactiver certaines fonctionnalités. L'avantage de
```suggestion
Lorsque l'on utilise Vue avec une étape de construction, il est possible de configurer un certain nombre d'indicateurs de compilation pour activer / désactiver certaines fonctionnalités. L'avantage de l'utilisation des indicateurs à la compilation est que les fonctionnalités désactivées de cette manière peuvent être supprimées du paquet final via le *tree-shaking*.
```

je rajoute le "/", pour rester cohérent avec ce qui est fait ailleurs

2023-12-30 22:20 UTC, tlagoda commented on src/api/compile-time-flags.md
> +  Activer/désactiver les avertissements détaillés pour les erreurs d'hydratation dans les versions de production. Cela aura pour conséquence d'inclure plus de code dans le bundle, il est donc recomma
```suggestion
  Activer / désactiver les avertissements détaillés pour les erreurs d'hydratation dans les versions de production. Cela aura pour conséquence d'inclure plus de code dans le bundle, il est donc recommandé de ne l'activer qu'à des fins de débogage.
```

2023-12-30 22:20 UTC, tlagoda commented on src/api/compile-time-flags.md
> +`@vue/cli-service` fournit automatiquement des valeurs par défaut pour certains de ces indicateurs. Pour configurer/modifier les valeurs :
```suggestion
`@vue/cli-service` fournit automatiquement des valeurs par défaut pour certains de ces indicateurs. Pour configurer / modifier les valeurs :
```

2023-12-30 22:21 UTC, tlagoda reviewed
beau boulot

2024-01-01 21:59 UTC, edimitchel commented
Finalement je préfère _Indicateurs à la compilation_ plutôt que _Chapeaux pour la compilation_. Merci de rectifier :)

2024-01-03 05:59 UTC, tisma95 commented
> Finalement je préfère _Indicateurs à la compilation_ plutôt que _Chapeaux pour la compilation_. Merci de rectifier :)

çà doit être bon maintenant.

2024-01-03 12:27 UTC, edimitchel requested changes
Il manque la bonne traduction dans le menu (`config.ts`)

2024-01-06 11:51 UTC, edimitchel approved these changes

2024-01-06 11:51 UTC, merged