Fix typo
vuejs-translations/docs-fr pull request #908
Opened 2024-01-19 13:09 UTC by Gregcop1

**Actions à effectuer :**

- [X] Vérifier que le nombre de lignes supprimées égale le nombre de lignes ajoutées
- [X] Mettre en cohérence toute référence à la page traduite qui serait présente sur d'autres pages  
  
- [X] Mettre à jour le lien du menu  
  
- [ ] Lier la PR à une issue  
      Closes # 
      
Remarques:
Dois-je ouvrir une issue pour chacune des pages corrigées ? Là, j'ai fait un tour assez global sur le guide.

2024-01-20 10:25 UTC, tisma95 approved these changes
Merci beaucoup 👍

2024-01-21 22:32 UTC, edimitchel requested changes
Beau boulot, quelques petites choses à rectifier et ça sera bon !

Merci pour ce gros travail de rectification ! Très appréciable !

2024-01-21 22:32 UTC, edimitchel commented on src/guide/essentials/template-syntax.md
> +Les doubles moustaches interprètent les données comme du texte brut et non comme du HTML. Afin de produire du vrai HTML, vous devrez utiliser la directive [`v-html`](/api/built-in-directives#v):
```suggestion
Les doubles moustaches interprètent les données comme du texte brut et non comme du HTML. Afin de produire du vrai HTML, vous devrez utiliser la directive [`v-html`](/api/built-in-directives#v-html) :
```

2024-01-21 22:39 UTC, edimitchel commented
> Dois-je ouvrir une issue pour chacune des pages corrigées ? Là, j'ai fait un tour assez global sur le guide.

Non pas la peine, c'est une sorte de relecture qui était au programme initialement mais par manque d'effectif, nous avions fait l'impasse dessus.

2024-01-22 08:36 UTC, Gregcop1 commented on src/guide/components/props.md
> +Lorsqu'un prop est déclaré pour autoriser plusieurs types, les règles de conversion pour `Boolean` seront également appliquées. Cependant, il y a un avantage lorsque `String` et `Boolean` sont autori
J'ai vu le féminin et le masculin sur le projet, de ce fait, je vais compléter la PR avec l'harmonisation de tout ça.

2024-01-22 10:43 UTC, Gregcop1 commented
Je suis repassé sur les corrections demandées et l'harmonisation du genre pour "prop"

2024-01-22 19:37 UTC, edimitchel approved these changes

2024-01-22 19:37 UTC, merged